### ISSUE TITLE
Admin-specified anti-spam filter

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1002]
All I can think of right now is having a per-line regex for each type of spam to filter and ban.
A few automatic ones I can think of right now are:
1. Name/Time (or relative) No.(num)
If more than 2-3 of them are in post, it's spam.
2. Garbage text over (num) limit
3. newline spam

Don't bother with client filtering (send or receive), have server filter it first and last.

**Comment by bakape** [comment]
Best implement it publically instead.
Closed in favor of #777
