### ISSUE TITLE
Bad DB migration

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1005]
I had to do this in a vm, so it's a bit makeshift.
![Screenshot_20190312_124336](https://user-images.githubusercontent.com/30435868/54223623-e43d9d00-44c5-11e9-80f3-5e98834be278.png)
![Screenshot_20190312_124418](https://user-images.githubusercontent.com/30435868/54223669-fb7c8a80-44c5-11e9-8deb-0a429682f383.png)
![Screenshot_20190312_124403](https://user-images.githubusercontent.com/30435868/54223683-033c2f00-44c6-11e9-8de7-aaf99b6f4944.png)
![Screenshot_20190312_124351](https://user-images.githubusercontent.com/30435868/54223692-06cfb600-44c6-11e9-8164-d4622294051f.png)
Seems to be caused by this migration: https://github.com/bakape/meguca/blob/master/db/migrations.go#L1034

**Comment by bakape** [comment]
Odd that it does not trigger in tests. Is the VM fresh? Postgresql version?

**Comment by Chiiruno** [comment]
The VM is fresh. 
NixOS default for postgres post-17.09 is 9.6. https://github.com/NixOS/nixpkgs/blob/d04fedd71500703e86486f31e4a1b1289fb7c081/nixos/modules/services/databases/postgresql.nix#L170

**Comment by bakape** [comment]
Install postgresql >= 10 and try to reproduce.

**Comment by Chiiruno** [comment]
I can not reproduce on versions 10 or 11.
