### ISSUE TITLE
ffmpeg.c: In function 'codec_context':

### ISSUE THREAD

**Issue by CardealRusso** [bakape/meguca#1009]
github.com/bakape/thumbnailer
ffmpeg.c: In function 'codec_context':
ffmpeg.c:57:15: error: 'AVStream {aka struct AVStream}' has no member named 'codecpar'
     switch (st->codecpar->codec_id) {
               ^
ffmpeg.c:66:40: error: 'AVStream {aka struct AVStream}' has no member named 'codecpar'
         codec = avcodec_find_decoder(st->codecpar->codec_id);
                                        ^
ffmpeg.c:76:11: warning: implicit declaration of function 'avcodec_parameters_to_context' [-Wimplicit-function-declaration]
     err = avcodec_parameters_to_context(*avcc, st->codecpar);
           ^
ffmpeg.c:76:50: error: 'AVStream {aka struct AVStream}' has no member named 'codecpar'
     err = avcodec_parameters_to_context(*avcc, st->codecpar);
                                                  ^
github.com/chai2010/webp
gitlab.com/nyarla/go-crypt
github.com/aquilax/tripcode
github.com/bakape/meguca/parser
github.com/bakape/meguca/websockets/feeds
github.com/bakape/meguca/websockets
github.com/dimfeld/httptreemux
github.com/gorilla/handlers
github.com/andybalholm/cascadia
github.com/PuerkitoBio/goquery
golang.org/x/crypto/ssh/terminal
github.com/Sirupsen/logrus
github.com/otium/ytdl
github.com/kardianos/osext
github.com/sevlyar/go-daemon
Makefile:53: recipe for target 'server' failed
make: *** [server] Error 2

**Comment by bakape** [comment]
FFmpeg version?

**Comment by Konstanty** [comment]
For completeness, this is caused by using the default versions of libavcodec/libavutil in Ubuntu 16.04. Upgrading to a newer version fixes this.
