### ISSUE TITLE
Captcha antispam protection

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#1011]
- [x] Check for global ban
- [ ] Increment spam score by one image insertion

**Comment by bakape** [comment]
@Chiiruno Do something once in a while.

**Comment by Chiiruno** [comment]
![Screenshot_20190317_155300](https://user-images.githubusercontent.com/30435868/54497793-dc6a6800-48cc-11e9-95ea-d82e57486630.png)
That said, I'll see if I can tomorrow, when I'm not about to kill myself from lack of sleep.

**Comment by Chiiruno** [comment]
#1003 merged into this.
