### ISSUE TITLE
Unban message is bugged in client

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1012]
>moderation message thingy shits the bed when unban happens

May also be on client-side, but I wasn't in the thread as it happened.
![image](https://user-images.githubusercontent.com/30435868/54864642-020dcc00-4d28-11e9-9b19-f3d608518865.png)

**Comment by Chiiruno** [comment]
also be nice to ed onegai, he is nice barbarian

**Comment by bakape** [comment]
Looks client-side. The `post_moderation` table should not be affected by unbans.

**Comment by Chiiruno** [comment]
Yeah, and templates doesn't do 'undefined' either. I'm retarded.
Is the post mod-log entry in client not being updated for unban?
