### ISSUE TITLE
404 sql error

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1017]
![Screenshot_20190323_161857](https://user-images.githubusercontent.com/30435868/54871863-03bbac00-4d89-11e9-80fb-3dc774d4da6b.png)
Any page.

**Comment by bakape** [comment]
Where?

**Comment by Chiiruno** [comment]
Everywhere. Refresh.

**Comment by bakape** [comment]
Closed with 12dfa3d5b0f763bbad8f878105178c71e7eb46fe
