### ISSUE TITLE
Option to show r/a/dio and Eden in the now playing banner at the same time

### ISSUE THREAD

**Issue by medukatheguca** [bakape/meguca#1019]
It'd be nice to have both stations shown side by side by selecting _both_ as the option in the _Now Playing Banner_ selection box instead of having to toggle between the two

**Comment by bakape** [comment]
Would have to double the banner height though.

**Comment by medukatheguca** [comment]
They could be on the same line divided by a | if doubling the height is an issue. The tags aren't usually _that_ big and if they are, they could just be truncated once they reach half of the screen's width. Not sure if this would translate well to mobile, though.

**Comment by bakape** [comment]
It would look shit on mobile or when tiling the window to a reduced size.
The song indicator for one station already takes a lot of screen space.

**Comment by medukatheguca** [comment]
Not sure if you do this already for mobile but the text could scale down to make it at least sort of readable if the option for both stations is selected. Or it could just be a desktop only feature.

**Comment by bakape** [comment]
I guess. Well, do it then.

**Comment by medukatheguca** [comment]
I'm busy from job hunting right now but I'll work on this some time in the future
Expect a PR in #d7777 days

**Comment by bakape** [comment]
Well, I don't plan to tackle this next week and likely not the week after.
There are higher priority things to do even meguca-wise.

**Comment by medukatheguca** [comment]
Yea, no problem. I'll work on it when I have time.
