### ISSUE TITLE
Have meguca search path for background videos

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1020]
In the case of nixos, specifically my meguca package, where the www directory is immutable, it would be good to be able to point meguca to a directory in which meguca can read and serve to the user.
Related: https://github.com/NixOS/nixpkgs/pull/57527

**Comment by Chiiruno** [comment]
Similar to the images folder, that meguca generates, I think.

**Comment by Chiiruno** [comment]
Or, even we can reuse the images folder and add a videos folder inside, then change the specific handling we currently have to serve background videos.

**Comment by bakape** [comment]
Put those into config.json and as a CLI flag.

**Comment by Chiiruno** [comment]
dayo neeeee
Okay.

**Comment by Chiiruno** [comment]
ah I forgot about this
I reeaaaaly don't wanna do this but I guess I'll have to since nix bullshit.
I'll try to start on this today.
