### ISSUE TITLE
Infinite loading and error on surf

### ISSUE THREAD

**Issue by lc-guy** [bakape/meguca#1023]
>Can't find variable: BroadcastChannel

A guca mentioned something about apple. I guess this occurs in all webkit browsers?
I use surf sometimes when I want to have only meguca opened without the overhead of modern(tm) browsers. Would be nice if it was kept compatible with the site.

**Comment by bakape** [comment]
1) The BroadcastChannel issue should be fixed now.

> 2) Contact the Surf devs to ensure this.
