### ISSUE TITLE
Safari Cant find variable Broadcastchannel

### ISSUE THREAD

**Issue by askl56** [bakape/meguca#1025]
Hey,

Currently trying to fix this issue. I saw you made some changes here: 302d8be

What is the cause of the issue?

//askl56

**Comment by bakape** [comment]
Isn't it fixed already?

**Comment by askl56** [comment]
Nope. Got the error message this morning.

**Comment by bakape** [comment]
Odd. Well anyway, the cause is Safari being the spiritual successor to IE
and not supporting Broadcastchannel.

**Comment by askl56** [comment]
Is there a discord or Slack where we can talk?

**Comment by bakape** [comment]
No. Talk here.
