### ISSUE TITLE
Dual radio needs space after |

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1037]
![Screenshot_20190419_045702](https://user-images.githubusercontent.com/30435868/56419379-a9b2e700-625f-11e9-9781-e62e89a2bfea.png)

**Comment by bakape** [comment]
Then fix it.

**Comment by Chiiruno** [comment]
@RMiko did it, so he should.

**Comment by RMiko** [comment]
Oh, okay. I'll get to it in a couple of days, currently stuck on my laptop with a broken fan.
