### ISSUE TITLE
Scrub sekritpost from images

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1050]
I actually like image sekritposting, but instead of retarded autism wars, let's just scrub it on upload receive.

**Comment by Chiiruno** [comment]
Also has the benefit of cleaning images gucas upload.

**Comment by RMiko** [comment]
Sounds good, should be easy enough to do, I'll see what I can do tomorrow.

**Comment by Chiiruno** [comment]
I already assigned myself to it.

**Comment by RMiko** [comment]
Yeah, just as I finished my comment, oh well.

**Comment by Chiiruno** [comment]
Doesn't really rule out steno-graphically as anon mentions, but not much we can do about that.

**Comment by RMiko** [comment]
Well, image secret posting using the script is literally just plaintext at the end of file, and I dont think the people making the script would ever do anything more complicated than that. So its not really a problem.

**Comment by chiya-chan** [comment]
Make it an auto ban too.
Anyone who changes the original image hash (and thus lose tag mappings) deserves death.

**Comment by RMiko** [comment]
There is still the problem of stolen images

**Comment by Chiiruno** [comment]
No need for auto-ban, since server can just scrub it.
Stenography will be hard, if not impossible to detect though.

**Comment by Chiiruno** [comment]
>people making the script would ever do anything more complicated than that

I'm tempted to do that for the userscript, for shits and giggles.

**Comment by RMiko** [comment]
Chiiru no!

**Comment by chiya-chan** [comment]
They can just simply change the format to bypass the server scrubbing. Don't even need steganography.

**Comment by Chiiruno** [comment]
That's a good point.
Any thoughts on a more wide sweep to detect and scrub sekritposts in the image, and hopefully return the hash back to normal?

**Comment by chiya-chan** [comment]
I'm not familiar with image formats, but maybe there's some header information you can use to determine where the file should end, and compare that to where it actually ends.
Worst case scenario, you could try parsing the file like a decoder would, and compare the expected end to the actual end. But that's a lot of work and probably not worth it.

**Comment by Chiiruno** [comment]
Well, the userscript adds plaintext at the end of the file like @RMiko said, here's two examples from two files. (in plaintext)
- test004secret
- test3005secret
note the 004 and 005, that seems to be an indicator along with the "secret" plaintext.
I'll have to look into the actual userscript and how it works, though.

**Comment by chiya-chan** [comment]
The "secret" plaintext is just a magic to identify that the image contains sekrittext.
The 3 digits before "secret" is the length of the sekrittext.
And the text before the digits is the actual sekrittext.

**Comment by Chiiruno** [comment]
Right now, a quick fix would be to just quickly identify the magic, and if it exist, checks if there's a number inbetween 000 and 999 and remove all of that along with whatever the number of characters before it is as indicated by the number.

**Comment by Chiiruno** [comment]
To make this server performant, I'll just check the beginning and end of the file right now.

**Comment by chiya-chan** [comment]
>of the beginning

I don't think there's much point in that.

**Comment by Chiiruno** [comment]
Minimal overhead to prevent simply changing the position to the (easily detectable by userscript) beginning of the image.

**Comment by chiya-chan** [comment]
I'm pretty sure putting it at the beginning would break the image. The end is the only place they can put it without breaking it.

**Comment by Chiiruno** [comment]
Alright, fair enough.

**Comment by bakape** [comment]
>I'm pretty sure putting it at the beginning would break the image. The end
is the only place they can put it without breaking it.
Or in the meta information.
