### ISSUE TITLE
Fix nothing being logged to systemd's journal

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#1060]

**Comment by bakape** [comment]
Best log to local log file instead. Need to assert that actually sill happens.

**Comment by Chiiruno** [comment]
Meguca seems to log just fine to systemd journal when used as a service.
For non-service, see http://0pointer.de/blog/projects/journal-submit.html

**Comment by Chiiruno** [comment]
No, that's for ffmpeg errors it seems.
Perhaps change errors.log to meguca.log and either symlink to /var/log or log directory to /var/log?

**Comment by bakape** [comment]
Not needed anymore.
