### ISSUE TITLE
Investigate why captchouli raises image server start times

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#1073]
Service init should be mostly non-blocking. Can test this with a big tag list.

**Comment by Chiiruno** [comment]
I've noticed this with server restarts, I'll look into this as well.

**Comment by Chiiruno** [comment]
Also noticed this only happens with a big tag list.

**Comment by Chiiruno** [comment]
Problem is definitely in (auth) `LoadCaptchaServices`

**Comment by Chiiruno** [comment]
Probably because `Parallel` isn't run async, and server init depends on error from it.

**Comment by Chiiruno** [comment]
No, should only go through 3 tags at first, then do rest as async.

**Comment by Chiiruno** [comment]
Problem is `captchouli.NewService`.

**Comment by Chiiruno** [comment]
Okay, best option seems to be instead of doing `captchouli.NewService(opts)`, do the first 3 tags instead, then goroutine the rest, and log an error if it messes up.

**Comment by Chiiruno** [comment]
No, even better would be have a boolean if it's startup, if startup, only do first 3, then on other invocations do normal.
