### ISSUE TITLE
After docker installation login doesn't work

### ISSUE THREAD

**Issue by denisviklov** [bakape/meguca#1076]
After docker and docker compose installation if you try to login for the first time with admin & password nothing happens. path /all reload but user stays unauthorized. /login endpoint sends 200OK but without payload.

**Comment by bakape** [comment]
Is this on localhost:8000 or 127.0.0.1:8000 ?

**Comment by denisviklov** [comment]
No, it was and on public ip 45.x.x.x.x:8000 and 80 and with a domain name 9ch.me on 80 and on 443, the same behavior

**Comment by bakape** [comment]
Your cookie domain is mismatched. Yeah, setting it up is a bit backwards
right now with a new deloyment. I'll look into streamlining this later
today.

**Comment by denisviklov** [comment]
ok, thank you

**Comment by bakape** [comment]
Closed with ea760d2dcd0c3ba53d68692c858fac147a52a5ab

**Comment by JustinAnon** [comment]
What should I do to get it working?

**Comment by denisviklov** [comment]
@JustinAnon the problem is what it serves on 127.0.0.1:8000 and signing cookies for the same domain instead of your original domain. So, there are many workarounds and I used nginx option to rewrite cookie domain

**Comment by bakape** [comment]
Maybe be this can be fixed by adding nginx to docker-compose.yml? Related to #1078

**Comment by bakape** [comment]
No, I think that will impart too much configuration overhead. I'll look more into this.

**Comment by bakape** [comment]
@JustinAnon Fixed with 3a4f995d4a8f7631c188f23ff79eb646b5880921
