### ISSUE TITLE
Rewrite client in Rust

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#1084]
Use brunhild, after it has been updated to the more stateless architecture.

**Comment by Chiiruno** [comment]
Let's just do a rewrite from scratch, plan out meguca and it's tooling, use Rust for critical performance parts of client and server, including thumbnailer and captchouli.
Have Go handle most things, have typescript handle most things, use Rust for stuff that can be intensive.
Have Typescript handle most things, call Rust WASM for stuff that can be intensive.
Rust isn't really for this kind of thing.

**Comment by Chiiruno** [comment]
Websockets may be a good candidate for Rust.
