### ISSUE TITLE
Configurable mature prompt URL

### ISSUE THREAD

**Issue by edisonlee55** [bakape/meguca#1087]
I have already disabled the mature content option in server configure, but the warning is still showing up...(￣▽￣)

Also when a user clicks cancel, it redirects to an external link `gaiaonline.com`, could you add the config option in server configure to disable or change the link? Thanks!

I am running using:
- meguca 111b83d
- Docker 19.03.1, build 74b1e89
- Docker Compose version 1.24.1, build 4667896b
- Ubuntu 18.04.3 LTS
- With Cloudflare-proxied domain

**Comment by edisonlee55** [comment]
Sorry, the mature content option issue seems resolved.
But could you add the config option in server configure to disable or change the link when a user clicks cancel?
Thanks!

**Comment by bakape** [comment]
The warning persisting was likely due to browser cache. I can add an option to override or disable the cancel URL. 

- [ ] Add server config to change cancel URL
- [ ] Empty string is no redirect 
- [ ] Note this in tooltip

**Comment by edisonlee55** [comment]
I have used many different browsers with an incognito window or without incognito window. I have also delete caches and cookies.

But all with the same result. The warning will still pop up.

**Comment by bakape** [comment]
Does restating the server fix it?

**Comment by edisonlee55** [comment]
No, restating the server won't fix it.

**Comment by bakape** [comment]
Closed with #1090
