### ISSUE TITLE
Support browsers that don't support WebP

### ISSUE THREAD

**Issue by edisonlee55** [bakape/meguca#1088]
Thumbnail will not show on the real mobile device but will show on desktop and chrome dev tool device mode.

Screenshot:
![IMG_1002](https://user-images.githubusercontent.com/5277788/62635890-1961f480-b96b-11e9-8097-a84a831409f6.jpeg)

Device reproduce the bug:
- iPhone 7 Plus (iOS 12.4)
- Google Chrome iOS 76.0.3809.81

Server running using:
- meguca 111b83d
- Docker 19.03.1, build 74b1e89
- Docker Compose version 1.24.1, build 4667896b
- Ubuntu 18.04.3 LTS
- With Cloudflare-proxied domain

**Comment by bakape** [comment]
Safari (and by extension all iOS browsers) are currently the only platform that does not support Webp (or even WebM). Meguca uses Webp thumbnails for efficient compression while also preserving the alpha channel. Until support is added to Safari, iOS will not be able to display Webp or WebM on meguca.

That said, polyfills could be added specifically for Safari, if need be, but at a notable performance cost on that platform.
