### ISSUE TITLE
"docker-compose build" fails

### ISSUE THREAD

**Issue by hKDTh42qJ** [bakape/meguca#1098]
**Error:** Service 'meguca' failed to build: The command '/bin/sh -c go mod download' returned a non-zero code: 1

**Build log:**  https://pastebin.com/raw/Y8z1bgr5

Tested on clean Debian and Ubuntu installations.

**Comment by bakape** [comment]
Might have been a network failure. Did building fail repeatedly?

**Comment by hKDTh42qJ** [comment]
It was a network failure. Running a VM in bridge mode causes this to happen. Thank you
