### ISSUE TITLE
Batch liveposting

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1108]
Say, every 200ms meguca would propagate text from clients, to other clients.
The clients themselves would send every 400ms perhaps.
So, it would go something like this.
Client: tehe pero nyaa mukyu dumb shit -> wait 400ms to send to server
Server: Receive from multiple clients, wait 200ms and batch db operation for post insertion, then propagation to clients, wait another 200ms after this.
Clients receives this (for threads client is in) at the same relative time as everyone else on the site.
I think this would be good for anti-spam as well as more efficient for db operations, less sequential overhead, since if the site was extremely active, say over 2000 posters posting at once, it would batch these together without issue.

**Comment by Chiiruno** [comment]
This should also theoretically cover natural time lag due to geographic distances, it can always be tuned optimally.

**Comment by 9mil-craftsman** [comment]
I'm sorry but this is very stupid. Don't do this

**Comment by Chiiruno** [comment]
>I'm sorry but this is very stupid. Don't do this

Care to explain how this is very stupid?
This should keep liveposting nearly the same, and should reduce the amount of constant db operations.

**Comment by 9mil-craftsman** [comment]
>  Care to explain how this is very stupid?

no im not going to explain
its just dumb you have to believe me

**Comment by Chiiruno** [comment]
>no im not going to explain
its just dumb you have to believe me

I see.
Then die.

**Comment by Chiiruno** [comment]
Anyway, could also make a server flag to adjust client/server send/propagate time.
So you could make it 100ms for server and 200ms for client, perhaps.
Again, optimization, these are just ballpark figures.

**Comment by bakape** [comment]
Never rely on the client and we already do batching and defered writesserver-side. Read the damn code.

**Comment by Chiiruno** [comment]
Moved from anti-spam since it's invalid, I guess.
Also fucking where, I haven't seen shit for batching with liveposting, as in text insertion and propagation.

**Comment by Chiiruno** [comment]
Also this isn't relying on the client, since the server in my scenario would only insert and propagate every 400s or so, not only accept every 400s, all POSTs would be saved up in memory and written to db and propagated at once, instead of case-by-case.
Read my damn issue.

**Comment by Chiiruno** [comment]
No, I'm dumb.
I misunderstood the code, I was relying on what I read in the past and didn't connect that websockets through postBodyModMessage chan and it's related method use the cache, so assuming the cache writes to db in batches, this issue would be invalid.

**Comment by bakape** [comment]
Open post bodies are currently stored inside boltDB and flushed to postgres on post close. A deferred write buffer is coming in the next version. Websocket messages are also buffered and sent in batches each 100 ms.
