### ISSUE TITLE
Last 100 post cleanup non-continuous with lock to bottom

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1115]
Of course, the behavior works if you scroll up a bit and then back down, but perhaps not having it work when always locked to bottom voids the point?
The client should probably pop the earliest post past 100 when the latest new post is pushed, when using lock to bottom.
This is with Firefox 69.0, I have not tested this behavior with Chromium.

**Comment by Chiiruno** [comment]
In addition, it may be desirable to have the client request older posts when scrolling up, of course cleaning up the last 100 newer ones.

**Comment by bakape** [comment]
Subset of #643
