### ISSUE TITLE
Multi-server system to handle text input and image processing

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1116]
I think image processing may already be somewhat handled by imager being able to be a separate process, but I was thinking, "What if meguca had 10000 active users."
I think the server may tank pretty hard with liveposting.
So, for throughput-heavy processes currently handled in the main process, instead split up into N processes that can be run on other servers congruently.
It's just something I randomly thought of, maybe you might be interested in this line of thought.
Anyway, it'd go something like this.
master server top layer
N liveposting, image handling/processing, database slaves middle layer
N network slave bottom layer

**Comment by Chiiruno** [comment]
I guess the glue between the separate servers would be LAN TCP/UDP.

**Comment by Chiiruno** [comment]
Also, for single-server install, just use the processes as 1 each and work together with local message handling.

**Comment by Chiiruno** [comment]
websockets should probably be a separate process too now that I think about it.

**Comment by bakape** [comment]
Read up on I/O overhead and see the v7 branch.
