### ISSUE TITLE
Is there a JSON API?

### ISSUE THREAD

**Issue by catamphetamine** [bakape/meguca#1118]
A quick test of `https://chen2.org/a/catalog.json` says `404 Not Found`.
Does this engine currently support JSON API?
If it does then maybe I'd add it to the `imageboard` library some day.
https://github.com/catamphetamine/imageboard

**Comment by bakape** [comment]
It does, but the project is currently undergoing a substantial change of
data storage and retrieval architecture, so integrating with it is not very
sound. I removed the JSON API docs for that reason, as I was breaking them
too often.

**Comment by catamphetamine** [comment]
I see.
Refactoring is good.
Closing for now.
