### ISSUE TITLE
Last part of the setup fails

### ISSUE THREAD

**Issue by hawkoon** [bakape/meguca#1120]
Using the official installation guide, the last part (make) throws this error and consequentially the './meguca' command doesn't work.
![fail](https://user-images.githubusercontent.com/54553501/66596877-099aa280-eb9e-11e9-95b5-c377c06497c6.png)

**Comment by hawkoon** [comment]
OK updating to the latest Go version (1.13.1) fixed this issue. You might want to update the installation guide.

**Comment by hawkoon** [comment]
Also is the './meguca -a :80' command supposed to start the server on port 80? Because it doesn't work, it still starts on port 8000.

**Comment by hawkoon** [comment]
And last but not least: thumbnail generation isn't working.
![fail2](https://user-images.githubusercontent.com/54553501/66599041-aeb77a00-eba2-11e9-9aad-7f15ab1c0d52.png)

**Comment by bakape** [comment]
> Also is the './meguca -a :80' command supposed to start the server on port 80? Because it doesn't work, it still starts on port 8000.

Yes, I'll update the installation guide. It's all done with config.json now.



> And last but not least: thumbnail generation isn't working.
> ![fail2](https://user-images.githubusercontent.com/54553501/66599041-aeb77a00-eba2-11e9-9aad-7f15ab1c0d52.png)

What browser + version?
