### ISSUE TITLE
Post quote should not green text after post quote

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1132]

**Comment by bakape** [comment]
Why not?

**Comment by Chiiruno** [comment]
Because it's a context error, in normal usage at least.
>`>>`12 asdasdas

should not be green for 'asdasdas'.
Usually, and more properly, it's
>`>>`12
asdasdas

**Comment by bakape** [comment]
I think it should, because the line starts with a `>`.

**Comment by Chiiruno** [comment]
Well, if you say so.
