### ISSUE TITLE
Unfinished involuntary post close

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1134]
The post itself does not go through to the server, I'm not entirely sure character submission does either.
No captchas have been triggered either time, not really sure what's going on.
Possibly userscript, hasn't happened before the update recently.

**Comment by bakape** [comment]
Was the post 15m old?

**Comment by Chiiruno** [comment]
No, fresh post, just closes on it's own in the middle of typing.

**Comment by bakape** [comment]
Invalid, until it can be reproduced without userscript.
