### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by hawkoon** [bakape/meguca#1139]
When will Pale Moon be supported? I hate having to use Chrome or Opera to be able to access the control panel.
![pale_moon](https://user-images.githubusercontent.com/54553501/68079467-59aa0500-fdea-11e9-8623-a2229eb3a008.png)

**Comment by ubone** [comment]
this is a joke right

**Comment by bakape** [comment]
>When will Pale Moon be supported?

Never, unless Palemoon starts supporting modern technologies.

**Comment by nekto-nekto** [comment]
https://github.com/Chiiruno/meguca_old/issues/3#issuecomment-554768387
