### ISSUE TITLE
Client-side plugin system

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1149]
Would be good for letting user-defined javascript/wasm to execute in the browser and have access to everything in the client, better for things like the userscript.
Just have to make sure it's secure.

**Comment by Chiiruno** [comment]
Could just expose functions, but I like this idea better, more modular, fits the theme.

**Comment by Chiiruno** [comment]
Implements client-side part of #1056

**Comment by bakape** [comment]
>a fucking plugin system with an API and walls of exposed hooks

You write it and you fix it and all the shit using it every time I break the API. Then, OK.

**Comment by Chiiruno** [comment]
There should be some fairly safe static stuff like posts, but yeah, that shouldn't be a real issue.
The main goal is to allow user WASM.
This is for v1(7,8?) or after v1 anyway.

**Comment by Chiiruno** [comment]
Ah, this would be a good way to handle most commands too, something along these lines we could keep the server itself very minimal, have the client itself mainly handle communication between server, and API plugins.
Server could have default types in the db for different counters and other similar commands, that thread owner can enable/disable.

**Comment by Chiiruno** [comment]
Could even handle megutv and cinema this way too.

**Comment by Chiiruno** [comment]
Maybe even allow shared tags with a "shared_megutv" type syntax for cross-thread db value sharing.
OP or staff with permissions that OP assigns would have to allow these threads to write to the db, though.

**Comment by Chiiruno** [comment]
Might be more efficient to do "{options}tag".

**Comment by Chiiruno** [comment]
Tags will likely be JSON right? We can just do `[tag: "megutv", options [rw: true]]`

**Comment by Chiiruno** [comment]
Actually, no need to have read/write, we can just have the thread choose which thread to share from, like this
```json
{
  "12345": {
    "megutv": {
      "from": [ "12346", "12348" ],
    }
  }
}
```

**Comment by Chiiruno** [comment]
Now here's the question, if thread A which is not a megutv thread pulls from thread B which is, should thread A include the pull that thread B pulls from thread C?

**Comment by bakape** [comment]
You're overthinking this. If you want hooks specifically for meguTV, sure. An entire plugin system is gigantic overkill. 

Commands will always be parsed on the server for security reasons and I'm not dynamically loading random binaries onto the server.

**Comment by Chiiruno** [comment]
>dynamically loading random binaries onto the server

lol what
I think there's a misunderstanding, the idea is to have commands and most similar features be handled client-side with a plugin, and of course server admin can specify the main plugin.
Then, to have the server have a set of generic types that can be inserted into the db that the thread can use, there will be nothing foreign inserted into the server or db.

**Comment by Chiiruno** [comment]
So, OP would specify command X that stores generic type Y (which is specified in this repo, not foreign) in the DB, and depends on client-side plugin Z. The thread will work without the plugin for the client, just command X will not show.
Server can send default plugin that you specify.
This way, we keep client and server very generic, probably speed things up, and allow greater extend-ability for all sites that use this.

**Comment by Chiiruno** [comment]
To be clear, the server will not host foreign client-side plugins.

**Comment by Chiiruno** [comment]
Server won't be parsing commands for instance, that will be handled client-side, server just sends the basic text, eg: "asasasasd\n#d7777", which client parses. Saves server resources.

**Comment by Chiiruno** [comment]
And, client will not send parsed commands, client sends on post complete just the regular text too.

**Comment by Chiiruno** [comment]
counters and other retrieved values can be stored in thread config hash and auto fetched on new post, would probably be ideal.

**Comment by Chiiruno** [comment]
Actually that's dumb and pointless, I'll come back to this when I'm sober.

**Comment by bakape** [comment]
> Server won't be parsing commands for instance, that will be handled client-side, server just sends the basic text, eg: "asasasasd\n#d7777", which client parses. Saves server resources.

Need I remind you the client can not be trusted and the server will still host at least some of the parsing. In that case, there would need to be merging of parsed output and fuck that. 



> Actually that's dumb and pointless, I'll come back to this when I'm sober.

I see.

**Comment by Chiiruno** [comment]
Yeah, there would be some problems if we had to fetch from the db each and every post, we would still need parsing and caching.
I'll need to rethink this, I feel it can work and be very efficient, but it needs more thought.

**Comment by bakape** [comment]
As I said, it needs a lot of thought. Plugin systems are generally
something that hooks into FUCKING EVERYTHING the base application does.
