### ISSUE TITLE
Automatic brotli (or gzip if desired) compression cache

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1154]
https://github.com/google/ngx_brotli
Nginx can make good use of brotli_static assuming say, images/src, images/thumbs, or folders in www are compressed and have the .br extension.
This will reduce CPU overhead for dynamic gzip/brotli conversion nginx does live, and result in a "compress once and forget" optimization.
Probably have meguca compress images and other things to brotli, serve in the same folders, client should decode as normal.

**Comment by Chiiruno** [comment]
A script can actually take care of this.

**Comment by bakape** [comment]
Compressing already compressed media like JPEG, PNG, WEBP almost always
leads to an increase in file size. I see no point and I'm sure NGINX
already does gzip caching of hot resources.

**Comment by Chiiruno** [comment]
Yeah, it's more for compression-friendly filetypes is what I found out too.
