### ISSUE TITLE
Read Early-Data header to prevent 0-RTT replay attacks.

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1155]
Probably return 425 on certain routes if early.
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_early_data

**Comment by bakape** [comment]
Explain further!

**Comment by Chiiruno** [comment]
https://blog.cloudflare.com/even-faster-connection-establishment-with-quic-0-rtt-resumption/
In router, read header for certain routes, if Early-Data header exists or contains the wrong value, return 425.

**Comment by bakape** [comment]
I don't think we have or ever will have any non-idempotent operations that do not check against global state. What could an attacker even eachieve with a replay-again attack?

**Comment by Chiiruno** [comment]
I'm not really sure if we don't have any non-idempotent operations, honestly.
Maybe we're fine.
