### ISSUE TITLE
Firefox 71 fails on site load

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1159]
![Screenshot_20191205_230750](https://user-images.githubusercontent.com/30435868/70297608-6d170a00-17b4-11ea-8d57-2794dbf8e031.png)
![Screenshot_20191205_230800](https://user-images.githubusercontent.com/30435868/70297609-6d170a00-17b4-11ea-8af2-5730c3f50363.png)
Tried with extensions disabled, same thing.
Also tried both fresh and non-fresh, seems to be a firefox issue.

**Comment by Chiiruno** [comment]
...except the part where it works on my Windows VM.
Strange, I've tried it with a whole fresh profile and all the cache/configs deleted too.

**Comment by Chiiruno** [comment]
Never mind, I think this may be some problem on my side.

**Comment by Chiiruno** [comment]
![Screenshot_20191205_232716](https://user-images.githubusercontent.com/30435868/70298328-e7488e00-17b6-11ea-95bd-b5d0cc7aba58.png)
Well, I did get this on private window.
I think firefox 71 may just be bugged beyond repair. Time to switch to chromium, ugh.

**Comment by bakape** [comment]
This is a 10yo bug - IndexedDB does not work in FF private mode. I that is
not private mode, they simply broke it completely.

**Comment by Chiiruno** [comment]
Yeah, tried on both normal and private.
FF is fucked all the way to fuckland now.
![shrug madotsuki](https://user-images.githubusercontent.com/30435868/70307951-e40dcc00-17cf-11ea-97f2-13536f35c358.jpg)
