### ISSUE TITLE
can't post pictures

### ISSUE THREAD

**Issue by peteblank** [bakape/meguca#1168]
Hey guys, let me start by saying that you guys have done a great job making this. 
I can't seem to find the meguca imageboard though.
It'd be a shame if you guys gave up on the project. 
Anyways I tried to install it on my machine it doesn't show the infinity symbol and I can't post pictures.
All I get is pic related. 
![Screenshot_2020-04-12 meguca](https://user-images.githubusercontent.com/46042807/79054488-61aa8280-7c6f-11ea-855e-b00bde3b70c1.png)

**Comment by bakape** [comment]
RTFM
