### ISSUE TITLE
v7: WebAssembly is not defined

### ISSUE THREAD

**Issue by hawkoon** [bakape/meguca#1181]
Installed v7 for fun. Getting this error in my browser:

> ReferenceError: WebAssembly is not defined

Related to this code:

`!function(e){function t(t){for(var n,_,o=t[0],c=t[1],u=0,b=[];u<o.length;u++)_=o[u],Object.prototype.hasOwnProperty.call(r,_)&&r[_]&&b.push(r[_][0]),r[_]=0;for(n in c)Object.prototype.hasOwnProperty.call(c,n)&&(e[n]=c[n]);for(i&&i(t);b.length;)b.shift()()}var n={},r={0:0};var _={};var o={3:function(){return{"./index_bg.js":{__wbg_getItem_08cba7eaeaee125e:function(e,t,r,_){return n[2].exports.Q(e,t,r,_)},__wbindgen_object_drop_ref:function(e){return n[2].exports.ld(e)},__wbg_new_0d50725e1ae68303:function(){return n[2].exports.Ab()},__wbindgen_string_new:function(e,t){return n[2].exports.od(e,t)},__wbg_push_46274b393147c746:function(e,t){return n[2].exports.Vb(e,t)},__wbg_generateKey_8146c73c715d4456:function(e,t,r,_){return n[2].exports.J(e,t,r,_)},__wbg_instanceof_Object_42d4e98f6a3c8730:function(e){return n[2].exports.ob(e)},__wbg_instanceof_Window_17fdb5cd280d476d:function(e){return n[2].exports.qb(e)},__wbg_get_f2faf882de3801f1:function(e,t){return n[2].exports.X(e,t)},__wbg_instanceof_Promise_174178d0c527edd5:function(e){return n[2].exports.pb(e)},__wbindgen_is_string:function(e){return n[2].exports.fd(e)},__wbindgen_string_get:function(e,t){return n[2].exports.nd(e,t)},__wbg_instanceof_CryptoKey_b02bd2dacea4b3c6:function(e){return n[2].exports.jb(e)},__wbg_exportKey_f8c4d936a5b528f1:function(e,t,r,_){return n[2].exports.F(e,t,r,_)},__wbg_new_3d94e83f0a6bf252:function(e){return n[2].exports.Cb(e)},__wbg_target_f6e8223f5b843ce6:function(e){return n[2].exports.Gc(e)},__wbg_instanceof_Element_410cf941ddd00d8b:function(e){return n[2].exports.kb(e)},__wbg_tagName_7a365cf2774b3613:function(e,t){return n[2].exports.Fc(e,t)},__wbg_classList_26cad35d60a907de:function(e){return n[2].exports.n(e)},__wbg_toggle_6c22d2596d990cf9:function(e,t,r){return n[2].exports.Mc(e,t,r)},__wbg_preventDefault_df37cc956d4ebefa:function(e){return n[2].exports.Sb(e)},__wbg_button_7bf8d297518275a6:function(e){return n[2].exports.k(e)},__wbindgen_number_new:function(e){return n[2].exports.jd(e)},__wbg_new_1879686750283650:function(e){return n[2].exports.Bb(e)},__wbg_getDate_2de16c1382eb758b:function(e){return n[2].exports.L(e)},__wbg_getMonth_6fd25e0040cfe8de:function(e){return n[2].exports.S(e)},__wbg_getFullYear_b93a733405fddf9a:function(e){return n[2].exports.O(e)},__wbg_getDay_ab7e75d539427bcb:function(e){return n[2].exports.M(e)},__wbg_getHours_cf6819fded5580b6:function(e){return n[2].exports.P(e)},__wbg_getMinutes_e090f52803593f2e:function(e){return n[2].exports.R(e)},__wbg_getSeconds_253e62f786773ec2:function(e){return n[2].exports.U(e)},__wbg_clearTimeout_0ae96176fb8a2d80:function(e,t){return n[2].exports.q(e,t)},__wbg_clearTimeout_ef4ff11df3d8e727:function(e,t){return n[2].exports.r(e,t)},__wbindgen_cb_drop:function(e){return n[2].exports.Rc(e)},__wbg_abort_5d7c3efa42c3a26b:function(e){return n[2].exports.e(e)},__wbg_removeEventListener_003b13762a00969d:function(e,t,r,_,o){return n[2].exports.bc(e,t,r,_,o)},__wbg_clearInterval_fa3605f6de4a3b4f:function(e,t){return n[2].exports.p(e,t)},__wbg_clearInterval_8fc3ceaa5b5b1936:function(e,t){return n[2].exports.o(e,t)},__wbg_crypto_ca6283e6a0198dab:function(e){return n[2].exports.y(e)},__wbg_getRandomValues_4e0354b1f3d14f64:function(e,t,r){return n[2].exports.T(e,t,r)},__wbg_importKey_461c6e8e184d7900:function(e,t,r,_,o,c,u){return n[2].exports.fb(e,t,r,_,o,c,u)},__wbg_sign_1bdae36825c032ce:function(e,t,r,_,o,c){return n[2].exports.zc(e,t,r,_,o,c)},__wbg_length_2e324c9c0e74a81d:function(e){return n[2].exports.ub(e)},__wbindgen_memory:function(){return n[2].exports.hd()},__wbg_buffer_eb5185aa4a8e9c62:function(e){return n[2].exports.j(e)},__wbg_set_d4d7629a896d4b3e:function(e,t,r){return n[2].exports.qc(e,t,r)},__wbg_toString_9f010a1c375de556:function(e){return n[2].exports.Lc(e)},__wbg_text_39a4ddf8fca1ea2a:function(e){return n[2].exports.Ic(e)},__wbg_arrayBuffer_74898c32f31aed64:function(e){return n[2].exports.i(e)},__wbg_status_5aa511c8aa1732bf:function(e){return n[2].exports.Cc(e)},__wbg_headers_9753444e56c26bcd:function(e){return n[2].exports.bb(e)},__wbg_document_c26d0f423c143e0c:function(e){return n[2].exports.B(e)},__wbg_querySelector_9cf023db23245913:function(e,t,r){return n[2].exports.Wb(e,t,r)},__wbg_lastChild_4add591e64b65966:function(e){return n[2].exports.sb(e)},__wbg_removeChild_d8035999cf171601:function(e,t){return n[2].exports.ac(e,t)},__wbg_new_d6227c3c833572bb:function(){return n[2].exports.Gb()},__wbg_set_6a666216929b0387:function(e,t,r){return n[2].exports.pc(e,t,r)},__wbg_addEventListener_3526086a053a131e:function(e,t,r,_,o){return n[2].exports.f(e,t,r,_,o)},__wbindgen_cb_forget:function(e){return n[2].exports.Sc(e)},__wbg_setInterval_b5b6859ec7e84914:function(e,t,r){return n[2].exports.lc(e,t,r)},__wbg_setInterval_037ab21c1449ece3:function(e,t,r){return n[2].exports.kc(e,t,r)},__wbg_now_91bb099d0ca251fd:function(){return n[2].exports.Ob()},__wbg_getElementById_df597d226f179219:function(e,t,r){return n[2].exports.N(e,t,r)},__wbg_instanceof_HtmlElement_8306a9fea71295d9:function(e){return n[2].exports.lb(e)},__wbg_offsetHeight_f69f0b2a08f3f697:function(e){return n[2].exports.Pb(e)},__wbg_documentElement_b3096283c6e729e2:function(e){return n[2].exports.A(e)},__wbg_scrollHeight_ba1c4578ac6dfb29:function(e){return n[2].exports.ec(e)},__wbg_scroll_a935b38fe8ffc236:function(e,t,r){return n[2].exports.gc(e,t,r)},__wbg_error_20ef23c2407793d3:function(e){return n[2].exports.D(e)},__wbg_new_88111bd0fdc13599:function(){return n[2].exports.Fb()},__wbg_signal_e752a58356b4b025:function(e){return n[2].exports.Ac(e)},__wbindgen_object_clone_ref:function(e){return n[2].exports.kd(e)},__wbg_fetch_703c4a4c693cf2cd:function(e,t,r){return n[2].exports.G(e,t,r)},__wbg_fetch_782ea005fc12211a:function(e,t,r){return n[2].exports.H(e,t,r)},__wbg_next_d2c829783697bd8e:function(e){return n[2].exports.Nb(e)},__wbg_done_a16709ea72553788:function(e){return n[2].exports.C(e)},__wbg_value_3093fb48085878da:function(e){return n[2].exports.Nc(e)},__wbg_from_83cf58103f34d499:function(e){return n[2].exports.I(e)},__wbg_get_5fd9dd78e47d6ed2:function(e,t){return n[2].exports.V(e,t)},__wbg_alert_8141c4835bfa8669:function(e,t,r){return n[2].exports.g(e,t,r)},__wbg_code_6ef342e504d4a37b:function(e){return n[2].exports.u(e)},__wbg_reason_a56ab9320f386929:function(e,t){return n[2].exports.Yb(e,t)},__wbg_message_c5541f3ef3d7613d:function(e,t){return n[2].exports.xb(e,t)},__wbg_data_de0b17a02fa3acad:function(e){return n[2].exports.z(e)},__wbg_hidden_b2aef3ee1a6cdd80:function(e){return n[2].exports.cb(e)},__wbg_navigator_b79fae9fb8efd473:function(e){return n[2].exports.zb(e)},__wbg_onLine_cf16c7831f05a9ea:function(e){return n[2].exports.Qb(e)},__wbg_setTimeout_306a4abb69f2ceea:function(e,t,r){return n[2].exports.nc(e,t,r)},__wbg_setTimeout_78ef5ef9cc48797e:function(e,t,r){return n[2].exports.oc(e,t,r)},__wbg_close_07ec78bacf7e8f1f:function(e){return n[2].exports.t(e)},__wbg_readyState_a05eebdc8022e90c:function(e){return n[2].exports.Xb(e)},__wbg_send_494cf3a7493cca42:function(e,t,r){return n[2].exports.ic(e,t,r)},__wbg_location_55774a0e1fed1144:function(e){return n[2].exports.wb(e)},__wbg_protocol_0030b41f28aeb6ff:function(e,t){return n[2].exports.Tb(e,t)},__wbg_host_6c14a7dfcff1e850:function(e,t){return n[2].exports.eb(e,t)},__wbg_new_3fb4884954862378:function(e,t){return n[2].exports.Db(e,t)},__wbg_setbinaryType_fa05f52027657f2f:function(e,t){return n[2].exports.rc(e,t)},__wbg_innerHeight_91035c3a853be26f:function(e){return n[2].exports.hb(e)},__wbindgen_number_get:function(e,t){return n[2].exports.id(e,t)},__wbg_scrollIntoView_b2b7598dea6a56b2:function(e){return n[2].exports.fc(e)},__wbg_click_3b9a7794e3ac6e30:function(e){return n[2].exports.s(e)},__wbg_setvolume_8ef0336a7e7613ac:function(e,t){return n[2].exports.yc(e,t)},__wbg_setItem_535f63295c5e7cec:function(e,t,r,_,o){return n[2].exports.mc(e,t,r,_,o)},__wbg_subtle_61ff87cb1711070b:function(e){return n[2].exports.Ec(e)},__wbg_pathname_db18adb1b44a41ac:function(e,t){return n[2].exports.Rb(e,t)},__wbg_hash_1f7108ce4ab5e5a0:function(e,t){return n[2].exports.ab(e,t)},__wbg_requestAnimationFrame_284f4f875590aa84:function(e,t){return n[2].exports.cc(e,t)},__wbg_history_2bd386a1e700a297:function(e){return n[2].exports.db(e)},__wbg_pushState_975ea60d9a21e778:function(e,t,r,_,o,c){return n[2].exports.Ub(e,t,r,_,o,c)},__wbg_setscrollRestoration_35b1ec8be57b0e08:function(e,t){return n[2].exports.uc(e,t)},__wbg_innerHTML_5ccbebf45da6c1ea:function(e,t){return n[2].exports.gb(e,t)},__wbg_newwithform_535a389645be5f5d:function(e){return n[2].exports.Ib(e)},__wbg_get_af45921f597bdb6d:function(e,t,r){return n[2].exports.W(e,t,r)},__wbg_getAll_67e2348fcb45d41b:function(e,t,r){return n[2].exports.K(e,t,r)},__wbg_length_0f0e68fde7e14c19:function(e){return n[2].exports.tb(e)},__wbg_localStorage_09146b4f48d49bc9:function(e){return n[2].exports.vb(e)},__wbg_new_59cb74e423758ede:function(){return n[2].exports.Eb()},__wbg_stack_558ba5917b466edd:function(e,t){return n[2].exports.Bc(e,t)},__wbg_error_4bb6c2a97407129a:function(e,t){return n[2].exports.E(e,t)},__wbg_Window_f826a1dec163bacb:function(e){return n[2].exports.b(e)},__wbindgen_is_undefined:function(e){return n[2].exports.gd(e)},__wbg_WorkerGlobalScope_967d186155183d38:function(e){return n[2].exports.d(e)},__wbg_self_c0d3a5923e013647:function(){return n[2].exports.hc()},__wbg_window_7ee6c8be3432927d:function(){return n[2].exports.Qc()},__wbg_globalThis_c6de1d938e089cf0:function(){return n[2].exports.Y()},__wbg_global_c9a01ce4680907f8:function(){return n[2].exports.Z()},__wbg_newnoargs_8aad4a6554f38345:function(e,t){return n[2].exports.Hb(e,t)},__wbg_call_1f85aaa5836dfb23:function(e,t){return n[2].exports.l(e,t)},__wbindgen_debug_string:function(e,t){return n[2].exports.cd(e,t)},__wbindgen_throw:function(e,t){return n[2].exports.pd(e,t)},__wbindgen_rethrow:function(e){return n[2].exports.md(e)},__wbg_then_300153bb889a5b4b:function(e,t,r){return n[2].exports.Jc(e,t,r)},__wbg_resolve_708df7651c8929b8:function(e){return n[2].exports.dc(e)},__wbg_then_8c23dce80c84c8fb:function(e,t){return n[2].exports.Kc(e,t)},__wbg_nextSibling_f1e7154ee59f6a7d:function(e){return n[2].exports.Lb(e)},__wbg_setnodeValue_ab4d09a5c9b583a3:function(e,t,r){return n[2].exports.tc(e,t,r)},__wbg_createTextNode_756ffaca4044be42:function(e,t,r){return n[2].exports.x(e,t,r)},__wbg_appendChild_3d4ec7dbf3472d31:function(e,t){return n[2].exports.h(e,t)},__wbg_insertBefore_e617280513985f61:function(e,t,r){return n[2].exports.ib(e,t,r)},__wbg_namespaceURI_35b1c4eab9150629:function(e,t){return n[2].exports.yb(e,t)},__wbg_createElement_44ab59c4ad367831:function(e,t,r){return n[2].exports.w(e,t,r)},__wbg_createElementNS_74ac818c77233fe4:function(e,t,r,_,o){return n[2].exports.v(e,t,r,_,o)},__wbg_setAttribute_1e9980589f904db6:function(e,t,r,_,o){return n[2].exports.jc(e,t,r,_,o)},__wbg_instanceof_HtmlInputElement_9e9349535b986dc4:function(e){return n[2].exports.mb(e)},__wbg_instanceof_HtmlTextAreaElement_af4dc0571f10534b:function(e){return n[2].exports.nb(e)},__wbg_removeAttribute_ab1ad95ea7761680:function(e,t,r){return n[2].exports.Zb(e,t,r)},__wbg_settype_ccacb981913395e5:function(e,t,r){return n[2].exports.vc(e,t,r)},__wbg_setvalue_eb5415236467cd34:function(e,t,r){return n[2].exports.xc(e,t,r)},__wbg_setchecked_795fe0b967d5d996:function(e,t){return n[2].exports.sc(e,t)},__wbg_setvalue_8bb8ffbd27a7ffda:function(e,t,r){return n[2].exports.wc(e,t,r)},__wbg_cancelAnimationFrame_c319aff8384d65c2:function(e,t){return n[2].exports.m(e,t)},__wbg_stopPropagation_71c3dbce6a10eea7:function(e){return n[2].exports.Dc(e)},__wbg_value_c2fd875fedc14f57:function(e,t){return n[2].exports.Pc(e,t)},__wbg_value_7ffe1d058e13aa75:function(e,t){return n[2].exports.Oc(e,t)},__wbg_textContent_11e88e9f262e569b:function(e,t){return n[2].exports.Hc(e,t)},__wbg_iterator_f89e8caf932523b1:function(){return n[2].exports.rb()},__wbindgen_is_function:function(e){return n[2].exports.dd(e)},__wbindgen_is_object:function(e){return n[2].exports.ed(e)},__wbg_next_3d6c9b2822b18fae:function(e){return n[2].exports.Mb(e)},__wbg_newwithstrsequencesequence_4aaf8aca7255ab0a:function(e){return n[2].exports.Kb(e)},__wbg_newwithstrandinit_48a2ea56c3a4ef8e:function(e,t,r){return n[2].exports.Jb(e,t,r)},__wbg_Window_b3da3e322112ea6e:function(e){return n[2].exports.a(e)},__wbg_WorkerGlobalScope_0bc96aa4b1059188:function(e){return n[2].exports.c(e)},__wbindgen_closure_wrapper1014:function(e,t,r){return n[2].exports.Tc(e,t,r)},__wbindgen_closure_wrapper257:function(e,t,r){return n[2].exports.Zc(e,t,r)},__wbindgen_closure_wrapper255:function(e,t,r){return n[2].exports.Yc(e,t,r)},__wbindgen_closure_wrapper251:function(e,t,r){return n[2].exports.Wc(e,t,r)},__wbindgen_closure_wrapper253:function(e,t,r){return n[2].exports.Xc(e,t,r)},__wbindgen_closure_wrapper1682:function(e,t,r){return n[2].exports.Uc(e,t,r)},__wbindgen_closure_wrapper2485:function(e,t,r){return n[2].exports.Vc(e,t,r)},__wbindgen_closure_wrapper259:function(e,t,r){return n[2].exports.ad(e,t,r)},__wbindgen_closure_wrapper891:function(e,t,r){return n[2].exports.bd(e,t,r)}}}}};function c(t){if(n[t])return n[t].exports;var r=n[t]={i:t,l:!1,exports:{}};return e[t].call(r.exports,r,r.exports,c),r.l=!0,r.exports}c.e=function(e){var t=[],n=r[e];if(0!==n)if(n)t.push(n[2]);else{var u=new Promise((function(t,_){n=r[e]=[t,_]}));t.push(n[2]=u);var b,f=document.createElement("script");f.charset="utf-8",f.timeout=120,c.nc&&f.setAttribute("nonce",c.nc),f.src=function(e){return c.p+""+({}[e]||e)+".js"}(e);var i=new Error;b=function(t){f.onerror=f.onload=null,clearTimeout(a);var n=r[e];if(0!==n){if(n){var _=t&&("load"===t.type?"missing":t.type),o=t&&t.target&&t.target.src;i.message="Loading chunk "+e+" failed.\n("+_+": "+o+")",i.name="ChunkLoadError",i.type=_,i.request=o,n[1](i)}r[e]=void 0}};var a=setTimeout((function(){b({type:"timeout",target:f})}),12e4);f.onerror=f.onload=b,document.head.appendChild(f)}return({1:[3]}[e]||[]).forEach((function(e){var n=_[e];if(n)t.push(n);else{var r,u=o[e](),b=fetch(c.p+""+{3:"2772b53451479fbc3731"}[e]+".module.wasm");if(u instanceof Promise&&"function"==typeof WebAssembly.compileStreaming)r=Promise.all([WebAssembly.compileStreaming(b),u]).then((function(e){return WebAssembly.instantiate(e[0],e[1])}));else if("function"==typeof WebAssembly.instantiateStreaming)r=WebAssembly.instantiateStreaming(b,u);else{r=b.then((function(e){return e.arrayBuffer()})).then((function(e){return WebAssembly.instantiate(e,u)}))}t.push(_[e]=r.then((function(t){return c.w[e]=(t.instance||t).exports})))}})),Promise.all(t)},c.m=e,c.c=n,c.d=function(e,t,n){c.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},c.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},c.t=function(e,t){if(1&t&&(e=c(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(c.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var r in e)c.d(n,r,function(t){return e[t]}.bind(null,r));return n},c.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return c.d(t,"a",t),t},c.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},c.p="/assets/client/",c.oe=function(e){throw console.error(e),e},c.w={};var u=window.webpackJsonp=window.webpackJsonp||[],b=u.push.bind(u);u.push=t,u=u.slice();for(var f=0;f<u.length;f++)t(u[f]);var i=b;c(c.s=0)}([function(e,t,n){n.e(1).then(n.bind(null,1)).catch(console.error)}]);`

**Comment by hawkoon** [comment]
Also I **strongly** urge you not to require users to have WebAssembly enabled in their browser to use Meguca v7 since that's still a very experimental feature and not present in every browser nor enabled by default in any browser.

**Comment by bakape** [comment]
I know. Master is broken ATM. Big patch for post parsing in progress. Any
fixes before that are pointless.
