### ISSUE TITLE
error: could not compile `syn`.

### ISSUE THREAD

**Issue by headhunterbr** [bakape/meguca#1198]
Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name syn /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.18/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C codegen-units=1 --cfg 'feature="clone-impls"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="extra-traits"' --cfg 'feature="full"' --cfg 'feature="parsing"' --cfg 'feature="printing"' --cfg 'feature="proc-macro"' --cfg 'feature="quote"' --cfg 'feature="visit"' --cfg 'feature="visit-mut"' -C metadata=681088f6bce562dc -C extra-filename=-681088f6bce562dc --out-dir /root/meguca/target/release/deps -L dependency=/root/meguca/target/release/deps --extern proc_macro2=/root/meguca/target/release/deps/libproc_macro2-586bc3e7576e9c1a.rmeta --extern quote=/root/meguca/target/release/deps/libquote-6deb81264cff71ae.rmeta --extern unicode_xid=/root/meguca/target/release/deps/libunicode_xid-facdb14fde0a9dbc.rmeta --cap-lints allow --cfg syn_disable_nightly_tests` (signal: 9, SIGKILL: kill)
Makefile:29: recipe for target 'websockets' failed
make: *** [websockets] Error 101

**Comment by bakape** [comment]
master branch is currently broken. Will be fixed some time this week. If
you want to deploy, use the v6 branch, as noted in the README.
