### ISSUE TITLE
panic: migration error: 78 -> 79: pq: syntax error at or near "cascade"

### ISSUE THREAD

**Issue by headhunterbr** [bakape/meguca#1204]
panic: migration error: 78 -> 79: pq: syntax error at or near "cascade"

goroutine 1 [running]:
main.main()
        /root/meguca/main.go:10 +0x44

**Comment by bakape** [comment]
Is this still an issue with Docker builds fixed?

**Comment by headhunterbr** [comment]
> Is this still an issue with Docker builds fixed?

now i cant even compile on a 256mb ram vps
but ty for attentrion

**Comment by bakape** [comment]
256MB is too little either way, unless you plan to disable upload
processing. That eats a lot of CPU cycles and memory in bursts.
