### ISSUE TITLE
please select an item in the list

### ISSUE THREAD

**Issue by peteblank** [bakape/meguca#1205]
![Screenshot from 2020-06-20 23-15-05](https://user-images.githubusercontent.com/46042807/85206436-5a2ce700-b34c-11ea-8dc1-481e9dccefab.png)
I managed to run docker this time, so its fixed.
I'm digging it there is just one issue. 
It won't let me post because of pic related.
What should i do?

**Comment by peteblank** [comment]
oh I clicked on anonymize and it made it go away. nvm.
Btw how do I enable captchas?

**Comment by bakape** [comment]
See the blinking icons in the top right corner? Explore them! You can't
post, because there are no boards to post on.

**Comment by peteblank** [comment]
solved
