### ISSUE TITLE
 Network Error (tcp_error)

### ISSUE THREAD

**Issue by peteblank** [bakape/meguca#1206]
So I managed to make meguca work on my computer but whenever i upload it to the cloud it gives me this error. 
I asked linode and they said it had something to do with the ports but they didn't go into more detail.
I feel like I'm very close to being able to run it. 
My server instance is 1 cpu, 1 gb of ram, ubuntu 20.04 LTS.
![Screenshot from 2020-06-22 12-14-09](https://user-images.githubusercontent.com/46042807/85250942-310e7280-b482-11ea-99de-759da5cdea74.png)

**Comment by bakape** [comment]
What are you using as a reverse proxy?

**Comment by peteblank** [comment]
I don't even know what a reverse proxy is tbh.
I just followed the installation instructions.-_-
But I'm using linode as a webhost atm.

**Comment by bakape** [comment]
VPS?

**Comment by peteblank** [comment]
Well I'm using cloud hosting.

**Comment by bakape** [comment]
A VPS or some sort of docker host?

**Comment by peteblank** [comment]
vps

**Comment by bakape** [comment]
Then you need a reverse proxy like NGINX to host on a privileged port. See
the dice for an example.

**Comment by peteblank** [comment]
Do I set it to port 8000?

**Comment by peteblank** [comment]
Wew lad I did it I don't know how but I did it.
http://95.111.193.40:8000/technology/catalog
Thank you bakape. I still have a few more questions though if that's okay.

**Comment by bakape** [comment]
Sure

**Comment by peteblank** [comment]
Well like how do I enable the captcha and how do I make it so not everyone can just register and change things?
Also I checked the site on my phone and it removed the css.

**Comment by peteblank** [comment]
okay nvm I solved it
