### ISSUE TITLE
I can't reply or delete posts on chromium

### ISSUE THREAD

**Issue by peteblank** [bakape/meguca#1207]
It works on firefox though.
Also it'd be nice if I was able to sticky threads.

**Comment by peteblank** [comment]
Btw is there a way to set meguca to port 80?

**Comment by peteblank** [comment]
well just when I got the site working and posted it on 4chan I got ranged banned.
Looks like my site won't see the light of day and I can't be bothered to try to bypass 4chan's bans. 
Here's my site nonetheless.
techchan.xyz

**Comment by bakape** [comment]
That's normal. Advertising any other chan is bound to get you banned.

**Comment by bakape** [comment]
>I can't reply or delete posts on chromium
Browser version, OS, have you tried with addons disabled?

**Comment by peteblank** [comment]
Well they unbanned me but literately nobody has posted except one person complaining about the notification. 
I can't think of another place to advertise the site thought.
Anyways I'm using
Chromium Version 81.0.4044.138 (Developer Build) Fedora Project (64-bit) and I just have two add ons, metamask and gnome-look.

**Comment by bakape** [comment]
Current stable Chromium is 83.

**Comment by GarfieldsPipe** [comment]
> I can't think of another place to advertise the site thought.

Shill it on large altchans like 9chan.tw/b/, 8chnl.net/b/, 8kun.top/random/ etc.

**Comment by peteblank** [comment]
Uh it works now.
Never mind.
