### ISSUE TITLE
connection status

### ISSUE THREAD

**Issue by peteblank** [bakape/meguca#1209]
So I know I have been asking a lot of dumb questions, sorry about that.
Anyways I'm almost done with the site, I set up the reverse proxy and cloudflare I just have one issue.
The connection status keeps connecting and disconnecting so I can't reply to the threads.
Here's the site
https://techchan.xyz/

**Comment by peteblank** [comment]
solved it.

**Comment by MCMXCIII** [comment]
how did you solve this?

**Comment by bakape** [comment]
Are you using a reverse proxy of some sort? If yes, make sure it has a long request lifetime set. The default is usually something like 1 minute.

**Comment by MCMXCIII** [comment]
I have set my response time to 300 seconds and I am in a constant state of connecting I am looking for anything I might be doing wrong I tried looking in logs but couldnt find anything. Any help is appreciated.

**Comment by MCMXCIII** [comment]
Nevermind Got it.

For anyone reading this don't be me make sure **WEBSOCKETS ARE ENABLED.**
