### ISSUE TITLE
Errors loading Meguca using .onion in Tor Browser

### ISSUE THREAD

**Issue by hawkoon** [bakape/meguca#1218]
I've set up a .onion for my Meguca site, but when I open the site with Tor Browser the console shows me errors:
```
Error loading IndexedDB. All further DB access will be ignored db.ts:64:11
    open db.ts:64
DOMException: "A mutation operation was attempted on a database that did not allow mutations." db.ts:65:11
    open db.ts:65
TypeError: db is undefined
3 db.ts:172:11
TypeError: db is undefined
```

Note that this happens with the default settings, I have JavaScript enabled in my browser.

**Comment by bakape** [comment]
Firefox bug with IndexedDB in private tabs that has not been fixed in 7
years: https://bugzilla.mozilla.org/show_bug.cgi?id=944918
Not my problem.
