### ISSUE TITLE
Any thoughts on QuicTransport?

### ISSUE THREAD

**Issue by ibis85** [bakape/meguca#1229]
https://web.dev/quictransport/

It's still an experimental feature, but just wondering what your thoughts are about it if you have any. It's UDP, so if it were included maybe the WebSocket could still remain as the authoritative transport. Do you think it could offer any potentially significant real/perceived latency reduction, or would it not be worth it?

**Comment by bakape** [comment]
Don't see any point.
>Do you think it could offer any potentially significant real/perceived
latency reduction, or would it not be worth it?
Probably not.
