### ISSUE TITLE
Frequently uploaded file caching

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#1251]
On imageboards, a lot of files are reuploaded.
Why not make a counter in the db for file hashes, delete db entry on last included thread deletion on a weekly or bi-weekly basis if the counter limit has not been reached, and do not delete files or db counter for hash that are reuploaded, or attempted to if the db counter for that hash reaches a certain amount?

Upload original file -> server hashes it
Attempts to upload same file -> client hashes it, sends hash to server -> increments hash counter -> if over X do not allow normal deletion of file or db hash counter for X amount of time (eg: a week), flag for deletion after X amount of time if no attempt to reupload.

**Comment by bakape** [comment]
But we already do that? See `processRequest()` and `UploadImageHash()`.

**Comment by Chiiruno** [comment]
Yeah, on second thought, this might be useless or have very little benefit over what we have now.
What I described was a bit different, but yeah.
