### ISSUE TITLE
How to become admin?

### ISSUE THREAD

**Issue by MCMXCIII** [bakape/meguca#1273]
hen entering the password the page refreshes and I dont receive a 403 but I am not sure how to reach the admin panel.... I am confused am I missing something?

**Comment by bakape** [comment]
Does the infinity menu in the top right corner show up?

**Comment by MCMXCIII** [comment]
The menu appears and I can login with the default but after that nothing happens?

I just wanted to know if I was missing something I can see in the source where the button is but nothing happens on the browser?

**Comment by Kamuso** [comment]
Can you check if the login cookies are being set?
To do this, open the browser developer tools, go to the application tab, and look at the cookies in the storage section. The relevant cookies you're looking for are loginID and session.

**Comment by bakape** [comment]
Some screenshots would be nice as well.

**Comment by MCMXCIII** [comment]
I aint seeing no cookies at all I have a video for you as well.

https://user-images.githubusercontent.com/31150823/107860647-62bbbb80-6e0e-11eb-9121-9782d529c881.mp4

**Comment by bakape** [comment]
Yeah, we did have changes in cookie setting recently. This is a bug. Perhaps the cause is being on port 8000. I'll look into this.

**Comment by bakape** [comment]
Tried on a fresh container - can't reproduce. 

@MCMXCIII Could you post the response headers of the `/api/login` request? Should be something like this 
![Screenshot_20210221_204626](https://user-images.githubusercontent.com/7851952/108635100-03048680-7486-11eb-90f9-18d42c6c8a10.png)

**Comment by MCMXCIII** [comment]
Trying this on a fresh container in docker.

**Comment by MCMXCIII** [comment]
I tried in a new container and still nothing. @bakape I am not sure if this means much but I am using v6. Should I be using another version?

I will follow this up with a video in a few hours of exactly what I am doing.

Thanks for your help.

**Comment by MCMXCIII** [comment]
> 
> 
> Tried on a fresh container - can't reproduce.
> 
> @MCMXCIII Could you post the response headers of the `/api/login` request? Should be something like this
> ![Screenshot_20210221_204626](https://user-images.githubusercontent.com/7851952/108635100-03048680-7486-11eb-90f9-18d42c6c8a10.png)

This returns a 404 for me???

**Comment by Kamuso** [comment]
@MCMXCIII 
> This returns a 404 for me???

You aren't meant to navigate to that url. You need to open the developer tools again and go to the network tab. Make sure you have the "Preserve log" checkbox near the top enabled. Try logging in again with the network tab open and look for the entry named login. Click on it and look for the response header.
![network](https://user-images.githubusercontent.com/43774246/108729049-0b120400-7522-11eb-86df-da433c88222e.png)

I think it would also be helpful if you ran ``git log`` from the meguca source directory, so we can see if you're running an up-to-date version of v6.

**Comment by MCMXCIII** [comment]
Checking this now

**Comment by MCMXCIII** [comment]
Sorry for the late reply after checking I don't have a login entry.

**Comment by MCMXCIII** [comment]
Actually I found it here

![Login Cookie](https://user-images.githubusercontent.com/31150823/114625689-a309af80-9c80-11eb-9942-90843d29c9c3.PNG)

**Comment by MCMXCIII** [comment]
@Kamuso @bakape  can you show me what the admin panel is supposed to look like?

**Comment by Kamuso** [comment]
Yeah that's the cookies on http issue. It's already been fixed, so update your v6 branch. It might also be a good idea to use https from now on.

>can you show me what the admin panel is supposed to look like?

The panel where you log in gets changed to this. Also if the account has moderation privileges, the panel at the bottom right appears.
![image](https://user-images.githubusercontent.com/43774246/115433858-eb384d00-a1ff-11eb-88ef-c4833706ea95.png)

**Comment by MCMXCIII** [comment]
Thanks for fixing this! Makring this as closed.
