### ISSUE TITLE
NPM wrong build code?

### ISSUE THREAD

**Issue by MCMXCIII** [bakape/meguca#1291]
I recently ran into an error on branch V6 and I received the following(attached in the screenshot)

I am running on Ubuntu 21.04
and attempting to run on docker.

Please advise?
<img width="612" alt="Issue error" src="https://user-images.githubusercontent.com/31150823/131158590-2c3480a6-93bb-4efa-9c1e-14c75519d809.PNG">

**Comment by tokkerdemalion** [comment]
The base image switched to bullseye at some point which broke it for me.
Forcing node 10 fixed it. `RUN apt-get install -y nodejs=10.\*`

**Comment by bakape** [comment]
CI also passes, so that fixed it.
