### ISSUE TITLE
Feature request: IDs and moderation actions by ID

### ISSUE THREAD

**Issue by maq33** [bakape/meguca#1296]
This feature would be interesting and useful.

Even more if the imageboard has Tor/I2p support.

Let's suppose someone floods the chan, deleting all the posts could affect other posts and threads that was made by Tor/I2P since all the addresses made by them are 127.0.0.1.

Deleting only threads and posts by ID would affect only the matched IDs, not IPs.

Obviously, this feature would require Cookies to work with.

**Comment by bakape** [comment]
Cookies can be easily faked by the client and thus not usable as an ID. Current poster IDs are generated from IPs, and thus this request is redundant in v6. v7 uses public keys for identification, so this will come as a given.
