### ISSUE TITLE
Feature request: Captcha mechanism that doesn't require JavaScript

### ISSUE THREAD

**Issue by maq33** [bakape/meguca#1298]
A captcha mechanism that doesn't require JavaScript would be good for users that are worried about privacy leaks in their browsers by JavaScript, particularly good for using with Tor/I2P.

The captcha could be applied for thread and post creation.

**Comment by bakape** [comment]
Already there. Try loading a page with JS disabled.

**Comment by maq33** [comment]
I went to https://megu.ca/all and I could see it.

Thanks.
