### ISSUE TITLE
Better duplicate detection

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#134]
Implement the http://manpages.ubuntu.com/manpages/precise/man1/findimagedupes.1p.html algorythm through successive imagemagick calls

**Comment by bakape** [comment]
We have progress. What we need to do now is change duplicate detection on the database level. Store the hashes as binary strings (may need to shorten) and XOR them to check for similarity. The storage and expiration model needs thought.

**Comment by bakape** [comment]
On second thought, do we need it?

**Comment by reiclone** [comment]
Maybe in the future? Right now it probably just serves to make avatarfags get more images.

**Comment by bakape** [comment]
Probably. How do  we go about hash expiration though? Are you familiar with redis?

**Comment by reiclone** [comment]
Not really, I only looked through it to understand how meguca worked.
