### ISSUE TITLE
Reimplement sound webm overlays

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#140]
- Client-side in imager.js
- Use Open Iconic icons (might as well use SVG)

**Comment by bakape** [comment]
- Also for MP3 and other files with sound

**Comment by Chiiruno** [comment]
Is this still relevant/needed?

**Comment by bakape** [comment]
Might be. It's a nice little thing to warn the user in a more noticable way
about a file having sound.

**Comment by Chiiruno** [comment]
I'll add this to my TODO then.
Like last time, unless you want to get to this soon for some reason.

**Comment by bakape** [comment]
Personally, I notice the little audio symbol in the header just fine but
other people might want this. As for implementation -  a transparent SVG
overlay over the thumbnail is probably best.

**Comment by Chiiruno** [comment]
Would you mind creating the SVG, or have an SVG we can use?
If not, any ideas on what it should loog like?

**Comment by bakape** [comment]
For consistency best just to use the ones in openiconic. All our icons are
from there. I think a light gray is best for theme neutrality.

**Comment by Chiiruno** [comment]
Got it.

**Comment by Chiiruno** [comment]
On second thought, and a little googling, this is more trouble than it's worth, for somethings anons are easily aware of anyway.
@bakape Needed, or can I close this?

**Comment by bakape** [comment]
Close
