### ISSUE TITLE
missing js for persona login

### ISSUE THREAD

**Issue by vampiricwulf** [bakape/meguca#148]
I guess it's not actually that, it's that it loads your libs AFTER it loads login.js, which makes login.js:
Uncaught ReferenceError: $ is not defined login.js?v=2:6

**Comment by vampiricwulf** [comment]
Fixed on mine with https://github.com/vampiricwulf/tanoshiine/commit/75ecc3b741f3aab5349ec1959342051d7d55ed56#diff-1

**Comment by bakape** [comment]
Yup, forgot about that. Thanks.
