### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by bakaonto** [bakape/meguca#149]
It would be nice to have a read-only, JSON API like [vichan's one](https://github.com/vichan-devel/vichan-API/blob/master/README.md) so we could track down threads and posts more easily.

If it were "compatible" with vichan's one, one could make simple changes to [Clover](https://github.com/Floens/Clover) and have a totally usable Android client for any doushio-based IB.

**Comment by bakape** [comment]
Is viichan's API actually compatible with current 4chan apps?

**Comment by vampiricwulf** [comment]
Exodus on fdroid is for vichan iirc.

**Comment by bakaonto** [comment]
>Is viichan's API actually compatible with current 4chan apps?

The (few) incompatibilities that exist are marked on the page I posted. Is that much of a problem? It could be 4chan based too, or a mix of they

>Exodus on fdroid is for vichan iirc.

Yes, I meant that one. thanks

**Comment by bakape** [comment]
Can be done. If we have an API, might as well make it viichan compatible. 
Will supersede bakape#125
