### ISSUE TITLE
image's timestamp "time ago"

### ISSUE THREAD

**Issue by bakaonto** [bakape/meguca#153]
Like implemented on here: https://github.com/Pashe/8chanX/blob/2-0/8chan-x.user.js#L1015

It would show something like "3 months ago" based on timestamps from filenames

**Comment by bakape** [comment]
I don't understand what exactly this does.

**Comment by bakaonto** [comment]
It's common to save files with UNIX filestamp filenames that are created on IBs, right?
Say the filename is 1313088564296.jpg. The code I posted above shows that it was created 4 years ago (more exactly, at 08/11/2011, 6:49pm)

**Comment by bakape** [comment]
Oh, that. We assign the original name to all downloads, so the timestamp name is only preserved, if you specifically right click on the image and save as. So most images will be save with their original name. More so, since the image can be renamed, I don't really see the use of it.
