### ISSUE TITLE
redis errors from index.js

### ISSUE THREAD

**Issue by theBladeee** [bakape/meguca#165]
https://gist.github.com/theBladeee/66fccdd1b46c12a5d9f2

Will no longer launch after a reboot. Updated Redis to the most recent version and still no luck.

**Comment by bakape** [comment]
Hmm, probably redis sorted set issue after an unclean shutdown. We should try isolating the key in question. Try enabling BOARDS in config.js one by one, until you find the board with the corrupt zset. We don't have many global zset keys, so it's probably a board-specific one.

**Comment by bakape** [comment]
I seem to have isolated the issue to the `tag:${board_index}:${affected_board}:threads` key. If the problem is affecting production, you can use `RENAME` to get the affected key out of the way, but preserve all the boards threads. Disable `ARCHIVE` in `./config.js` in that case. You can later merge the sets back together, once we know the exact cause. I'll look into what exactly is causing the error.

**Comment by theBladeee** [comment]
Redid the config and its throwing more weird errors now.

https://gist.github.com/theBladeee/c48d42a5c788232ac3ba

**Comment by theBladeee** [comment]
Never mind, restart fixed it. Seems to be working now. Making sure the config is properly set after a fresh install seems to be doing good.

**Comment by theBladeee** [comment]
What is the graceful way to shutdown the server.js? It seems to throw the original error every time I try to restart it.

**Comment by bakape** [comment]
>Redid the config and its throwing more weird errors now.
https://gist.github.com/theBladeee/c48d42a5c788232ac3ba
You had another server running. Port was taken.

If you don't care about your threads, just do a `redis-cli flushdb`. I'll track down the bug, when I have more time.

**Comment by theBladeee** [comment]
Yeah I have done that, but it seems to throw the error on next startup.

Thanks.

**Comment by bakape** [comment]
Your `THREAD_EXPIRY` setting in `config.js` was not set for all boards. Will now default to 1 week, if unset. If the bug still occurs, reopen the issue.
