### ISSUE TITLE
Image upload queue

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#168]
Like with 4chan x, only it uploads images on demand. Display the queue in the corner and later allow reshuffling. Mostly backbone work.

**Comment by Chiiruno** [comment]
This seems pointless, unless you want to spam meguca for some reason.
Why would you implement this, when a user could just write a small script to do this?

**Comment by Chiiruno** [comment]
Also I don't think this would look good with the current upload form, unless you had really small thumbnails for the queued images.

**Comment by bakape** [comment]
Agreed.
