### ISSUE TITLE
Fully localisable client 

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#180]
The server is pretty much done. Once the core UI of the client is finalised, we can softcode the strings and functions.

**Comment by bakape** [comment]
Closed with 872d52eaff6e57893005ea80295966beabac6400

@underr 
Everything client-facing should be localisable now, except for the websocket error codes. I think it's best, if we keep those in English for debugging. Mind updating the PT_BR language pack, when you have the time? And tell me, if something is missing. Thanks in advance.

**Comment by underr** [comment]
Done, please tell me if I forgot something.
