### ISSUE TITLE
Dormant Functionality List: scroll.followLock(func)

### ISSUE THREAD

**Issue by KoinoAoi** [bakape/meguca#212]
followLock(func), formerly with_dom(func), is a function that allows for locking the screen in place. It gets the current position of the page, runs the function in the parameter, and then adjusts the page according to its lock position. Because of this, it needs to be added to just about everything that adds height to the page. 
**Areas where followLock(func) are noticeably not added**
- When a post is created via an inserted image rather than text
- As a post is updated with new lines
- When the Horizontal Posting option is deselected

**Comment by KoinoAoi** [comment]
- image expansion

**Comment by bakape** [comment]
>When the Horizontal Posting option is deselected

Related to CSS, not HTML. Can't be helped.
