### ISSUE TITLE
/all/ board

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#286]
For congregating every thread from all boards.

**Comment by sketchgithub** [comment]
on the /all/ board we should be able to create a new thread and decide what board it goes on, search all boards, and hide threads from a certain board.

Does a money incentive help speed the process of this being possible?

**Comment by bakape** [comment]
>money

Nope. But you can of course find someone and pay him. The codebase is large, but not that obfuscated to prevent anyone else from jumping in.

**Comment by bakape** [comment]
Note: Still need thread filtering and searching
