### ISSUE TITLE
Image Expansion Defaults in common/options

### ISSUE THREAD

**Issue by sketchgithub** [bakape/meguca#288]
when i edit common/options.js and add default: true, to the image expansion and replace it nothing happens.

also, how does meguca tell if the user is on mobile or not?

**Comment by bakape** [comment]
Follow standard JavaScript object notation, so `default: true,`. 

https://github.com/bakape/meguca/blob/master/server/web/html.js#L197-L201

**Comment by sketchgithub** [comment]
/* IMAGE HOVER EXPANSION */
                {
                        id: 'imageHover',
                        default: true,
                        load: notMobile,
                        tab: 0,
                },
                {
                        id: 'webmHover',
                        default: true,
                        load: notMobile,
                        tab: 0,

i have this there and still nothing

**Comment by bakape** [comment]
Did you restart the server?
