### ISSUE TITLE
Threads order doesnt update when you post on a thread

### ISSUE THREAD

**Issue by sketchgithub** [bakape/meguca#289]
the order of the thread doesnt update on your screen unless someone else posts on one.

Also, is it possible to lock the focus onto what thread your typing in?

**Comment by bakape** [comment]
>the order of the thread doesnt update on your screen unless someone else posts on one.

It does update. The page simply does not scroll to keep the screen from constantly bumping. Unless, you found some sort of bug. 

>Also, is it possible to lock the focus onto what thread your typing in?

Doesn't that already happen? Explain further.
