### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by sketchgithub** [bakape/meguca#290]
How do i make a backup of all my changes to ive made to the config files and then reinstall them on a new server? just in case my server dies

**Comment by bakape** [comment]
Just copy the files in `config/` and upload them somewhere. `scp` is one option. If you also want to transfer images, copy over `www/{mid,src,thumb}`. For copying the database over use http://stackoverflow.com/questions/6004915/how-do-i-move-a-redis-database-from-one-server-to-another

**Comment by sketchgithub** [comment]
i use scp to copy but how do i upload the backups somewhere and then download and replace the config files? I currently use nano in ssh to edit everything. not sure whats recommended.

**Comment by bakape** [comment]
Copy them over to your machine and then place them back.
