### ISSUE TITLE
:^) pattern to filter breaks posting.

### ISSUE THREAD

**Issue by NIXOYE** [bakape/meguca#294]
tried to have :^) filtered and it broke posting completely. Not sure if an issue is the right thing to open but i want this placed in the comment section of filters along with no spaces or new lines allowed as patterns to filter.

**Comment by bakape** [comment]
I don't seem to understand. It says right [here] (
https://github.com/bakape/meguca/blob/master/config/examples/hot.js#L84)
that whitespace is not allowed in the patterns.

**Comment by vampiricwulf** [comment]
Post your filter section of your config.

**Comment by bakape** [comment]
Was resolved as a syntax error in configs

**Comment by vampiricwulf** [comment]
That's what I thought.

**Comment by vampiricwulf** [comment]
Maybe you should add a comment above the filter section for them to use http://regexr.com/ to test their filters first.

**Comment by bakape** [comment]
No real point. Configuration files should be written under the assumption the reader is somewhat technical. For those kind of things, you need configuration webUI, with pretty buttons and menus and setting validation, and cleaner defaults, and automatic applying. We are getting there.
