### ISSUE TITLE
Can't log in admin panel

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#297]
I installed meguca on Debian 7 x64, with this script https://raw.githubusercontent.com/bakape/meguca/master/scripts/deploy.sh.
Everything works fine, but I can't log in the admin panel.
Every time I try to log in, I see the error - Bad Persona.
What am i doing wrong?
I tried to use a different email, different browsers (chrome, opera, firefox, ie), tried to reboot redis, edit the configuration files. Nothing helps.

**Comment by bakape** [comment]
What is your domain and PERSONA_AUDIENCE setting? Using HTTPS?

**Comment by serofir** [comment]
Thanks dude, that is was my mistake. (I forgot change this string)
Two days of headache.
You just solved the problem, thank you very much.

**Comment by bakape** [comment]
No problem.
