### ISSUE TITLE
Npm crash when I try to use commands  (rolls.join)

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#298]
I was tried to test some functions, like : 

#flip - Coinflip
#8ball - An 8ball
#pyu - Missle launcher
#pcount - Launch count

and maked new thread with them.

But then, npm was crashed, i restart service.
When i go to section  - /this_is_section_where_i_tested_commands/ , npm crashed again.
Again, and again.
How I can fix it?

Error.log : 

{"date":"Mon Oct 19 2015 20:31:27 GMT+0200 (CEST)","process":{"pid":14988,"uid":1000,"gid":1000,"cwd":"/home/meguca/server","execPath":"/usr/bin/nodejs","version":"v4.2.1","argv":["/usr/bin/nodejs","/home/meguca/server/index"],"memoryUsage":{"rss":72142848,"heapTotal":50497280,"heapUsed":47130696}},"os":{"loadavg":[0.02490234375,0.01904296875,0],"uptime":583870},"trace":[{"column":16,"file":"/home/meguca/server/common/util.js","function":"readableRegularDice","line":283,"method":null,"native":false},{"column":9,"file":"/home/meguca/server/common/util.js","function":"Object.readable_dice","line":264,"method":"readable_dice","native":false},{"column":24,"file":"/home/meguca/server/common/oneesama.js","function":"OneeSama.parseHashes","line":460,"method":"parseHashes","native":false},{"column":11,"file":"/home/meguca/server/common/oneesama.js","function":"OneeSama.breakHeart","line":397,"method":"breakHeart","native":false},{"column":10,"file":"/home/meguca/server/common/oneesama.js","function":"OneeSama.resolveState","line":375,"method":"resolveState","native":false},{"column":11,"file":"/home/meguca/server/common/oneesama.js","function":"OneeSama.fragment","line":345,"method":"fragment","native":false},{"column":8,"file":"/home/meguca/server/common/oneesama.js","function":"OneeSama.body","line":315,"method":"body","native":false},{"column":9,"file":"/home/meguca/server/common/oneesama.js","function":"OneeSama.monogatari","line":139,"method":"monogatari","native":false},{"column":20,"file":"/home/meguca/server/common/oneesama.js","function":"OneeSama.section","line":110,"method":"section","native":false},{"column":24,"file":"/home/meguca/server/server/render.js","function":"Board.onThread","line":269,"method":"onThread","native":false}],"stack":["TypeError: rolls.join is not a function","    at readableRegularDice (/home/meguca/server/common/util.js:283:16)","    at Object.readable_dice (/home/meguca/server/common/util.js:264:9)","    at OneeSama.parseHashes (/home/meguca/server/common/oneesama.js:460:24)","    at OneeSama.breakHeart (/home/meguca/server/common/oneesama.js:397:11)","    at OneeSama.resolveState (/home/meguca/server/common/oneesama.js:375:10)","    at OneeSama.fragment (/home/meguca/server/common/oneesama.js:345:11)","    at OneeSama.body (/home/meguca/server/common/oneesama.js:315:8)","    at OneeSama.monogatari (/home/meguca/server/common/oneesama.js:139:9)","    at OneeSama.section (/home/meguca/server/common/oneesama.js:110:20)","    at Board.onThread (/home/meguca/server/server/render.js:269:24)"],"level":"error","message":"uncaughtException: rolls.join is not a function","timestamp":"2015-10-19T18:31:28.065Z"}

**Comment by bakape** [comment]
Could I get the list of keys likely responsible for crashing? Run `redis-cli keys *${offending_post_number}*` and post result please.

**Comment by bakape** [comment]
I have reproduced the bug. Fix pending.

**Comment by serofir** [comment]
redis-cli keys *${offending_post_number}*
(error) ERR wrong number of arguments for 'keys' command

redis-cli keys *${195}*
(error) ERR wrong number of arguments for 'keys' command

redis-cli keys *{195}*
(empty list or set)

**Comment by bakape** [comment]
I meant that as `redis-cli *195*`. Not that it matters anymore. Found the
problem. Will fix this evening.
