### ISSUE TITLE
Upload Progress %

### ISSUE THREAD

**Issue by vampiricwulf** [bakape/meguca#304]
https://github.com/zeMirco/express-upload-progress
or w.e.
% Received currently is worthless as it just sits at saying Uploading then suddenly says 100% Received for a fraction of a second when the upload finishes.

**Comment by bakape** [comment]
That's because of proxy buffering.

**Comment by vampiricwulf** [comment]
Ah, so if you wanted to get around that, then you'd have to use [this](https://www.nginx.com/resources/wiki/modules/upload_progress/)?

**Comment by bakape** [comment]
Possibly, unless there is some other proxy in between.

**Comment by vampiricwulf** [comment]
Gotcha
