### ISSUE TITLE
Unable to log in admin

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#305]
I can not go to the admin panel.
Error "Bad persona", I tried everything.
I tried to change an account on persona.org.
Tried to change passwords, change browsers, nothing helps.
The problem appeared after reinstalling Windovs.
On the old OS, I used the browser Google Chrome.

**Comment by bakape** [comment]
Are you certain only your machine and not the server has changed? What
browsers have you tried?

**Comment by serofir** [comment]
The server has not changed.
I tried Google Chrome (the latest version)
Firefox (latest version)

**Comment by bakape** [comment]
Have you tried logging in from other devices.

**Comment by serofir** [comment]
I did not try to enter the system with other devices.

**Comment by bakape** [comment]
Then do so, so we can confirm this as a non-server issue.

**Comment by serofir** [comment]
Bad persona.

**Comment by serofir** [comment]
Succes!
After 1000 tries.

/issue

**Comment by bakape** [comment]
I think I can confirm this as a temporary issue with Mozillas Persona service.
