### ISSUE TITLE
Security settings

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#308]
How do I need to configure my own server to protect it from hacking?
For example, I just installed script by ../scripts/deploy.sh , then what should I do to improve the security of the server?
How to configure Iptables? What ports make open, and which are close? It is necessary to install fail2ban? What are tips of author in terms of security?

**Comment by bakape** [comment]
There is nothing specific about meguca security wise. All general practices apply.
Default ports are fine. Never used fail2ban, but SSH keys with passwords disabled is probably a better solution.
