### ISSUE TITLE
how to add infinite scrolling function?

### ISSUE THREAD

**Issue by metalbug** [bakape/meguca#313]
and i want single character real-time display
dont display after the space
how to do this?

**Comment by bakape** [comment]
What exactly do you mean? Infinite board page scrolling? That will become
pointless with v2, which is currently in development. As for character-size
commits to server, that would require a rewrite of the current text parser,
post submission form and database commit mechanism.

**Comment by metalbug** [comment]
yea, thanks I'm looking forward to V2, and Because of the use of Chinese, the input of the text can not be displayed in real time,So it takes a single character to display in real time

**Comment by bakape** [comment]
>Chinese
Oh, I see.  I can think if something, when I get home.

Also, did you already write a Chinese language pack or need help with it?

**Comment by bakape** [comment]
Is this for a Chinese imageboard or just posting some Chinese alongside English?

**Comment by metalbug** [comment]
Yes, I want to build a Chinese imageboard.
But I'm just in the local test, I did do a localization of doushio.
Your new version meguca I have not tested.
When I test, I will be a Chinese language packet to you, it is very simple.

**Comment by bakape** [comment]
Many subtle things break with per-character commits, as expected. Not going to implement this now, but support for Chinese and other less whitespaced languages will be included in version 2, which is projected to be ready next summer. For now you will sadly have to make do with commits only after spaces and Enter. 

>Your new version meguca I have not tested.

Do you mean you have not tested meguca in general (only doushio)? 

>When I test, I will be a Chinese language packet to you, it is very simple.
Sure, Pull Request or just drop me the files in some manner (the Chinese equivalent of the ones in `./lang/`). Adding them to the project, so others could benefit is always good.

**Comment by bakape** [comment]
Done.
