### ISSUE TITLE
Support for non-white-space-delimited  languages like Chinese and Japanese

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#314]
Involves a configuration option, that commits all but the last two characters, instead of words. Needs parser support. 

Forked from #313

**Comment by Lightsockie** [comment]
What about when you're inputting the kana, before you convert it to a kanji (or even katakana). If you have it set to two characters, then won't it grab half the word and result in lotsa errors? 
Like if you're typing バカペ, if it grabs the last two, then you'll get ばカペ. Of course, this is taking for granted what's actually happening during that "input" mode. Maybe the webpage doesn't even know about the different characters before their "set". 

Maybe a fix would be finding the longest character word and setting the limit to that (including particles, prolly, so +2). Unless it's smart enough to know about the "hanging input", then might I suggest a cutoff of four, incase you're trying to input a four-kanji word (the cap, I think for any one word).

No idea for Chinese tho

**Comment by bakape** [comment]
Moving the cutoff is trivial. No clue about Chinese. Asking @metalbug for details.

**Comment by bakape** [comment]
Superseded by #355
