### ISSUE TITLE
[code] tags on selected boards

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#316]
Breaks live posting. Should have a setting to enable this only on /g/-like boards or it will be abused more.

**Comment by Lightsockie** [comment]
Would it be possible to add other optional tags? I'm not sure how it looks behind the scene, but can I declare a custom tag and have it just do "something"? Much like I'd guess the [code] tag would just apply some specific formatting

 Specifically, I want to do a [math] tag. I'm thinking it'd be easiest with [jsMath](http://www.math.union.edu/~dpvc/jsmath/), like what /sci/ does. One thing that might be a hitch that if for whatever reason it can't display the math font, it'll default to images. This should only break formatting though (if it all), and not have problems ripple further out, ya?

I know the tags thing is prolly very low priority right now. I haven't even read too deeply on the jsMath subject (or how /sci/ keeps it sane/unabused, for that matter). Just wondering if it's something that /might/ be possible down the line

**Comment by bakape** [comment]
I'll look into it, when it's time to implement those.
