### ISSUE TITLE
How to setup Nginx + Meguca

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#323]
I tried to make them work together, but it's not working.
When I open site, there no pics, and static, only plain text and 404 error on pics.
May be some one can help me?
What I do wrong?

index.js

	SERVE_STATIC_FILES: false,
	SERVE_IMAGES: false,

imager.js

	MEDIA_URL: '../',

nginx.conf
http://codepad.org/BDHIKd96

default (nginx)
http://codepad.org/QBFMV2Rk

**Comment by bakape** [comment]
You have both config files enabled at the same time?

**Comment by serofir** [comment]
Yes, sorry I very newbie in this thing.

**Comment by bakape** [comment]
Have a look at http://nginx.org/en/docs/beginners_guide.html and
https://www.nginx.com/resources/admin-guide/reverse-proxy/ .  Though,  if
you are using Apache already and are familiar with it,  there is little
reason (aside from better performance and less memory usage) to use nginx
instead of Apache for the reverse proxy and asset serving.

**Comment by serofir** [comment]
Okay.
I read the instructions above.

I tried with

server {
    listen 80;

    server_name my_site.com;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
		proxy_buffering off;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

Not working.

Maybe I physically do not understand how to make it work. 
But I configured before many times Apache (php module) + Nginx and everything worked perfectly.

**Comment by bakape** [comment]
Does `nginx -t` print anything useful?

**Comment by serofir** [comment]
root@vds:~# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by bakape** [comment]
Hmm, post the output of `tree /etc/nginx`

**Comment by serofir** [comment]
/etc/nginx
/etc/nginx
├── conf.d
│   └── example_ssl.conf
├── fastcgi_params
├── koi-utf
├── koi-win
├── mime.types
├── naxsi_core.rules
├── naxsi.rules
├── nginx.conf
├── nginx.conf.dpkg-old
├── proxy_params
├── scgi_params
├── sites-available
│   └── default
├── sites-enabled
│   └── default
├── uwsgi_params
└── win-utf

**Comment by bakape** [comment]
And all the `server{}` blocks are written in `sites-enabled/default`?

**Comment by serofir** [comment]
sites-enabled/default   http://codepad.org/eM349ypz

**Comment by bakape** [comment]
Looks Okay. You did restart nginx, right?

**Comment by serofir** [comment]
Yes.

**Comment by bakape** [comment]
Not something I can diagnose remotely. Are you already familiar with Apache?
