### ISSUE TITLE
Actually publish the package to npm

### ISSUE THREAD

**Issue by Mithgol** [bakape/meguca#329]
While `package.json` currently [says](https://github.com/bakape/meguca/blob/022f1c580bf9b018399e8bf631ce36628d5acbd5/package.json#L2) that `meguca` is the package's name, this name seems to be [available](https://www.npmjs.com/package/meguca) (not taken) on npm. An attempt of `npm install meguca -g` would fail (or worse, might eventually install some other package).

**Comment by bakape** [comment]
npm does not have good support for distributing standalone executable packages and is more geared towards tools and libraries. Since there is little reason for anyone to ever use npm to install meguca, I see no reason to publish it there.

**Comment by bakape** [comment]
Furthermore don't ever install node modules globally. It's a bad security practice.
