### ISSUE TITLE
Working in cheap NAT ipv4 OpenVZ VPS

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#334]
Can it (meguca) work on cheap VPS, without dedicated ip?
For example 
http://dollarvz.com/ 
http://lowendspirit.com/locations.html
and other?

There are some reserved ports, and reverse proxy.

**Comment by bakape** [comment]
I am not knowledgeable enough about networking to know, if being behind a NAT has any effect, but from a hardware point of view the 512 MB RAM option might be enough with small load and low maximum image file size.
