### ISSUE TITLE
Persona going the way of the dodo

### ISSUE THREAD

**Issue by Lightsockie** [bakape/meguca#335]
My better half pointed this out:
Persona is no longer actively developed by Mozilla. Mozilla has committed to operational and security support of the persona.org services until November 30th, 2016.

On November 30th, 2016, Mozilla will shut down the persona.org services. Persona.org and related domains will be taken offline.

https://developer.mozilla.org/en-US/Persona

Not sure if you're up on this or not, didn't see an issue about it

**Comment by bakape** [comment]
Well aware. Version 2 will have an inhouse authentication solution.
