### ISSUE TITLE
"Normal posting" mode switch

### ISSUE THREAD

**Issue by Bozunee** [bakape/meguca#336]
A button that can switch between real time post updating and the typical chan posting.

Real time post updates after 2 words is cool and all, but I've noticed it really has a big impact on bandwidth consumption and general pace with other programs running at times.
Some button that can just let you post in a normal chan way would be a great solution.

**Comment by bakape** [comment]
This has been discussed before and the conclusion was that the setting has to be consistent with all users to not cause some serious bugs and complications. At most, it can be board-specific setting. So it can be a server-side setting, but no more.

**Comment by bakape** [comment]
Superseded by #358
