### ISSUE TITLE
Deploy.sh

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#348]
404 error https://raw.githubusercontent.com/bakape/meguca/master/scripts/deploy.sh
Where I can download this script?

**Comment by bakape** [comment]
The script was removed due to some changes in how we deploy, but I think I can resolve those now. Will need to test this. Will do so some time this week.

**Comment by serofir** [comment]
Cool. 
Also may be in future something more simple, for example one-click installation in Docker or Vargrant?
And tiny FAQ, how to install Meguca on cheap VDS (digitalocean, vultr, or scaleway) manual.

**Comment by bakape** [comment]
There are VPS prividers,  that offer one click Docker installation?
I might also look into droplets.

**Comment by serofir** [comment]
For example scaleway.com has Imagehub ( https://www.scaleway.com/imagehub/ ), with images of diffirent software one click installation.  There are Docker image too ( https://www.scaleway.com/imagehub/docker/ ) Digitalocean has one-click apps ( https://www.digitalocean.com/features/one-click-apps/ )  and vultr ( https://www.vultr.com/apps/ )

**Comment by serofir** [comment]
All of them has one-click docker installation.
There is a small flaw in Scaleway c1 3euro/m tariff has ARM processor, some applications it will not work.
If you want to use Scaleway servers, best offer will be new tariff's (VPS VC1 S 3euro/m) with x86 processor's. 
 (https://www.online.net/en/dedicated-cloud )

**Comment by bakape** [comment]
I'll look into Docker then. Could also use it to compile v2. That provably means removing the deploy script,  because it would be a less clean solution.  

I have never tested this, but meguca should run just fine on ARM.

**Comment by bakape** [comment]
You should be now able to use `wget -q -O- https://raw.githubusercontent.com/bakape/meguca/stable/scripts/deploy.sh | bash -`.
Will look into Docker at a later date.

**Comment by bakape** [comment]
We now provide binaries of releases (including for Windows). This is now redundant.
