### ISSUE TITLE
Optimised inhouse binary websocket protocol

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#356]
Short concise typed websocket messages with heavy usage of enums and bit masking bools. 
String encoding and optional field practices need thought.

**Comment by bakape** [comment]
No longer planned. JSON is good enough for now.

**Comment by bakape** [comment]
Open for implementation again after the move to Postgres. Will probably implement once in Rust and compile to server, asm.js and WASM.

**Comment by Chiiruno** [comment]
Should probably write a short standard for this inside of docs, in a markdown file before implementation.
As for the C++ client, honestly it may be smarter to just wait for Rust 2.0, so we (I'll help out) could do this in tandem with thumbnailer.

**Comment by bakape** [comment]
I'll get to the C++ client eventually. There are simply some big changes
you want to implement first before that to reduce useless work.

**Comment by bakape** [comment]
Wait, is Rust 2.0 actually coming?

**Comment by Chiiruno** [comment]
No clue, but I would guess within a year and a half.

**Comment by bakape** [comment]
Any sources on this?

**Comment by Chiiruno** [comment]
Not particularly, that's why it's a guess.

**Comment by Chiiruno** [comment]
Is this worth it vs just using gzip compression?
Doesn't TLS automatically compress contents as part of the encryption process? (Actually, that may only be the transport container)

**Comment by bakape** [comment]
It is, considering we batch our messages.

**Comment by bakape** [comment]
We could use Cap'n Proto and keep the server end on the Go side with https://github.com/capnproto/go-capnproto2.

**Comment by Chiiruno** [comment]
This looks pretty cool.
I say go for it.

**Comment by Chiiruno** [comment]
Why?

**Comment by Chiiruno** [comment]
You amaze me.

**Comment by bakape** [comment]
I forgot how I wanted to make it a mix of binary and gzipped JSON.

**Comment by bakape** [comment]
Done on master for a while now.
