### ISSUE TITLE
Blank Page Upon Install.

### ISSUE THREAD

**Issue by princessGasmask** [bakape/meguca#365]
I've just freshly installed using the pre-compiled Windows version 2.0. I have both rethinkDB and Meguca.exe running. The only feedback I get on Meguca is "Listening on localhost:8000."

http://puu.sh/pWBEA/9d9081c725.png

This is the output from RethinkDB. 

http://puu.sh/pWBGu/3e7f4db630.png

This is what I get in-browser. Cannot create a new user or a new thread using the keyboard shortcuts. Essentially no feedback.

**Comment by bakape** [comment]
As written in the README and the tag on the release, v2 is currently in early alpha. The binaries are meant more as a preview for developers than end users. As written in the README, download the [latest release](https://github.com/bakape/meguca/releases/latest) for any production usage. 

A more or less stable beta release of v2 can be expected in August.
