### ISSUE TITLE
Hideable image banners

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#367]
Configured by board owner and overridable by client.

**Comment by turtle5** [comment]
Are static image banners currently supported? What are the necessary changes?

**Comment by bakape** [comment]
Static banners can be added by uncommenting the block in `go/src/templates/board.qtpl` and setting the URL for the banner. Run `make server` after that. It's currently disabled, because I intend for those to be board-specific and the uploading of banners is not implemented yet.
