### ISSUE TITLE
builder.js error

### ISSUE THREAD

**Issue by runnerman2** [bakape/meguca#369]
Hello,when i try to node builder.js,i get error Error: Cannot find module './config' , I installed a module config , but I got the same error
<i>Ubuntu 16.04 x86_64</i> . node.js 6 ,node-gyp , imagemagick , redis installed

**Comment by bakape** [comment]
Did you run `npm install`? That should have copied the default configuration files.

**Comment by runnerman2** [comment]
Yes , the same error

**Comment by bakape** [comment]
Just tried with a fresh clone. Works fine here. Okay. Are you using vagrant or a Linux machine? Can you post the output of `ls -R ./config/`?

**Comment by bakape** [comment]
`npm install` run in the root directory installs all dependency npm modules automatically. Those are listed in `package.json`.
