### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by ozu-kun** [bakape/meguca#370]
Give me URL of Admin-panel please.

**Comment by bakape** [comment]
There is no URL pointing to the admin panel. It is overlaid over the regular UI. To access it type in the value of [config.LOGIN_KEYWORD](https://github.com/bakape/meguca/blob/stable/config/examples/index.js#L93) into the email field.  Default is "misaki". Assuming Persona is properly configured, you will be able to login with one of the emails set in [config.staff](https://github.com/bakape/meguca/blob/stable/config/examples/index.js#L86-L91).

**Comment by ozu-kun** [comment]
Dialing config.LOGIN_KEYWORD I got nothing. But there was an inscription "Invoke your Persona".

**Comment by bakape** [comment]
Yes, that is how you log in. Thankfully, this will be much simpler, when v2
hits stable.

**Comment by ozu-kun** [comment]
Now he writes Bad Persona. Why?

**Comment by bakape** [comment]
Most probably your PERSONA_AUDIENCE is not properly set.
What address are you serving the page from?
Did you set your email to the admin field of [staff](
https://github.com/bakape/meguca/blob/stable/config/examples/index.js#L86-L91
)?

**Comment by ozu-kun** [comment]
Tell me more please, how to log in? step by step.

**Comment by bakape** [comment]
It differs slightly, depending on whether you are already trying to set it up on a website or just testing things on your local machine. Which one is it?
