### ISSUE TITLE
How to add language?

### ISSUE THREAD

**Issue by tunayuyar** [bakape/meguca#372]
Hi,

I copied en_GB folder and changed folder name tr_TR and changed in the config to tr_TR but it throws bunch of errors.

Is there anything i need to change or ?

Thanks.

**Comment by bakape** [comment]
Could you post the errors?

**Comment by tunayuyar** [comment]
TypeError: Cannot read property 'common' of undefined
   at Board.initOneeSama (render.js:49:10)
   at Board.RenderBase (render.js:32:8)
   at Board (render.js:223:3)
   at html.js:64:3
   at Layer.handle [as handle_request] (/home/python/meguca-1.9.5/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/python/meguca-1.9.5/node_modules/express/lib/router/route.js:131:13)
   at Yakusoku.<anonymous> (html.js:59:4)
   at Yakusoku.g (events.js:286:16)
   at emitTwo (events.js:106:13)
   at Yakusoku.emit (events.js:191:7) 

I suspected Turkish characters first but replaced the file common.js (in tr_TR folder) with the en_GB one, same result. I should be doing something wrong.

**Comment by tunayuyar** [comment]
Also please note that meguca is running in virtualbox/ubuntu , on windows dedicated server. IIS does reverse proxy stuff.

Also getting this warning when running normaly:"mnemonizer: IP not valid: x.x.x:53985(port)

http://live.tahta.ch

**Comment by bakape** [comment]
To add a language pack you don't need to change any of the server code. Lets see...
1) Copy `lang/en_GB` as `lang/tr_TR`
2) In tr_TR go over the files and replace the string keys. For example `anon: 'Anonymous',` becomes `anon: 'WhateverAnonymousIsInTurkish',`
3) Add `'tr_TR'` to the `LANGS` array in `config/index.js` and change `DEFAULT_LANG` to `'tr_TR'`
4) Run `npm install` from meguca's root directory
5) Restart the server, if running
Meguca should now be almost translated to Turkish. There are some minor details, but I'll tell you about those, when the above is done.

**Comment by bakape** [comment]
>Also getting this warning when running normaly:"mnemonizer: IP not valid: x.x.x:53985(port)

Seems VirtualBox is rewriting some IPs in a non-standard way. This shouldn't affect anything much, while you're still testing on your PC.

**Comment by tunayuyar** [comment]
Now I see what Im missing I did not do the 4th step, let me check. 

Also Im not testing, looks stable and Im intending to use it on production.

**Comment by tunayuyar** [comment]
yes it work now, but a minor problem plural additions are in english 

english = day / turkish = gün 

days & güns - should be gün**ler**

anyways this is enough for now.

**Comment by bakape** [comment]
Yes, those currently require a little bit of JS. I'll write those later today. Mind uploading or PR-ing your translations, so I can add them all to the project proper?

**Comment by tunayuyar** [comment]
I only translated user facing side, I will upload when I complete all.

**Comment by tunayuyar** [comment]
Hi,

Hope this works

http://d.l3x.pw/index.php?f=157acada67689e

**Comment by bakape** [comment]
Done. If anything seems off, feel free to reopen this issue.
