### ISSUE TITLE
How to install meguca new

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#382]
I see >Go, TypeScript and RethinkDB new things.
The last time I installed it, it was a bit different. (redis, node.js)
It was a simple script automatic installation, writing on the bash. How to install this program now quickly and easily, for example on Debian 7? Any scripts or step-up guides? Maybe docker containers or something for regular user.

**Comment by bakape** [comment]
There are no deployment scripts at this moment and I don't plan to introduce any. There is also less need for that now, because we provide binary releases (also for windows).

**Comment by bakape** [comment]
Assuming you have no further questions.
