### ISSUE TITLE
Images won't expand to full-size.

### ISSUE THREAD

**Issue by princessGasmask** [bakape/meguca#383]
I'm on windows 10 using the pre-built binary. Everything else works, including animated thumbnails. My only issue is that I cannot expand images to full-size, and upon clicking an image thumbnail, it simply downloads the file rather than expanding it in the script.

**Comment by bakape** [comment]
I think image expansion is not implemented yet in ​the latest binary. I
will release the next version in a few days, once I work out the bugs. You
could wait or compile it yourself.

**Comment by princessGasmask** [comment]
Ah, okay. Thank you for the reply. I'll wait until then!

**Comment by bakape** [comment]
@princessGasmask
published v2.3.0 just now
