### ISSUE TITLE
Error on updating to 2.3

### ISSUE THREAD

**Issue by princessGasmask** [bakape/meguca#384]
![capture](https://cloud.githubusercontent.com/assets/5853862/19216165/6d179c92-8d77-11e6-81cd-a2c65f319b17.PNG)

**Comment by princessGasmask** [comment]
Realized this is probably due to a needed npm install or update.

**Comment by bakape** [comment]
If you are using the precompiled packages, there should be no need for npm. Just extract the archive, start RethinkDB and run meguca(.exe). Of course you need ffmpeg installed on Linux/OS X.

**Comment by princessGasmask** [comment]
both rethink and meguca are running, the same way I did when I used 2.2. Although, according to the error message, it's trying to call an assets folder that doesn't exist.

**Comment by bakape** [comment]
Windows, right? What does the console print when you run the exe?

**Comment by princessGasmask** [comment]
![capture](https://cloud.githubusercontent.com/assets/5853862/19216368/499aaef6-8d7e-11e6-8f59-55871b236126.PNG)

**Comment by princessGasmask** [comment]
I tried using 127.0.0.1 and it worked. I usually use localhost. Huh.

**Comment by bakape** [comment]
I assume that is something in your hosts file or windows being retarded. Please close, if there are no further issues.

**Comment by princessGasmask** [comment]
Indeed. Thanks for your help.
