### ISSUE TITLE
meguca: error while loading shared libraries: libavcodec-ffmpeg.so.56

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#387]
I tried use compiled binary release v2.3.0, and it not working.
root@vps:~/meguca# ./meguca help
./meguca: error while loading shared libraries: libavcodec-ffmpeg.so.56: cannot open shared object file: No such file or directory

FFmpeg all ready installed.
Debian 7.

root@vps:~/meguca# ffmpeg
ffmpeg version 1.0.10 Copyright (c) 2000-2014 the FFmpeg developers
  built on Oct 10 2016 07:43:38 with gcc 4.7 (Debian 4.7.2-5)
  configuration: --enable-gpl --enable-nonfree --enable-libfaac --enable-libgsm --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-zlib --enable-postproc --enable-swscale --enable-pthreads --enable-x11grab --enable-libdc1394 --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb
  libavutil      51. 73.101 / 51. 73.101
  libavcodec     54. 59.100 / 54. 59.100
  libavformat    54. 29.104 / 54. 29.104
  libavdevice    54.  2.101 / 54.  2.101
  libavfilter     3. 17.100 /  3. 17.100
  libswscale      2.  1.101 /  2.  1.101
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100

**Comment by bakape** [comment]
Hmm, yeah. The binaries fall apart, if you have a different version of ffmpeg installed. I'll compile some static binaries later today.

**Comment by bakape** [comment]
Replaced the binaries for v2.3.0 with statically linked ones. Should work fine now on any linux/x86_64 distribution.
