### ISSUE TITLE
compiling meguca: video.go:20: not enough arguments in call to d.AVFormat

### ISSUE THREAD

**Issue by sserenade** [bakape/meguca#388]
Hello,

I'm trying to compile meguca for myself after the binary release failed to work for me. (It was just a blank page on load with some errors in system.js about state_1.boards being null, str being undefined or el being null)

Anyway, I compiled ffmpeg with the required dependencies and installed the dev libraries needed.

Here's the error:

github.com/bakape/meguca/imager
.build/src/github.com/bakape/meguca/imager/video.go:20: not enough arguments in call to d.AVFormat
Makefile:52: recipe for target 'server' failed
make: *** [server] Error 2

I've looked at the source at length but I'm afraid I don't know much about go. This is a great project and I hope to see development continue as it has. Any help is appreciated.

**Comment by bakape** [comment]
Sorry, I was working on the ffmpeg bindings and did not switch the project fully over yet. Should have done that in another branch in retrospect. That is fixed. 

But the binary release not working is another issue. Looking into that now.

**Comment by bakape** [comment]
v2.4.1 published with the fix.
