### ISSUE TITLE
Hello, I got a strange error

### ISSUE THREAD

**Issue by cam-peterson** [bakape/meguca#391]
Hello I got this error when I view my instance of meguca: `json: unsupported type: map[int64]websockets.timestampedPost`

Do you know what could be causing it?

I am using version 1.6 of golang.

**Comment by RaymondSchnyder** [comment]
Sorry if i open this again, but how did you resolv this?

**Comment by bakape** [comment]
The README clearly states you need Go 1.7 or greater.
