### ISSUE TITLE
Type 'Timer' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by cam-peterson** [bakape/meguca#392]
I got this error: `client/connection.ts(197,2): error TS2322: Type 'Timer' is not assignable to type 'number'.`

Changing to `window.setTimeout` fixed it. https://github.com/Microsoft/TypeScript/issues/842#issuecomment-252445883

**Comment by bakape** [comment]
Yeah, just got it after upgrading Typescript. Seems like a regression, but fixed.
