### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#394]
fixed

**Comment by bakape** [comment]
Which RethinkDB version have you installed?

**Comment by serofir** [comment]
rethinkdb 2.2.6~0wheezy (GCC 4.6.3)

**Comment by bakape** [comment]
It seems the latest version is not available on wheezy (understandable, wheezy is 3 years old). Switch to jessie/ubuntu or compile the latest release (2.3.5) yourself.
