### ISSUE TITLE
 :8000: bind: address already in use

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#395]
root@vds:~/meguca# ./meguca debug
2016/11/12 20:48:18 listening on :8000
2016/11/12 20:48:18 error starting web server: listen tcp :8000: bind: address already in use

Clean server, new install.

Debian 8
rethinkdb 2.3.5~0jessie (GCC 4.9.2)
node v7.1.0

**Comment by serofir** [comment]
root@vds:~/meguca# ffmpeg -v
ffmpeg version N-82324-g872b358 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --enable-gpl --enable-libass --enable-libtheora --enable-libvorbis --enable-libx264 --enable-nonfree --enable-shared --enable-libopus --enable-libmp3lame --enable-libvpx --enable-libfdk_aac --enable-libx265 --enable-sdl
  libavutil      55. 36.100 / 55. 36.100
  libavcodec     57. 66.101 / 57. 66.101
  libavformat    57. 57.100 / 57. 57.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 66.100 /  6. 66.100
  libswscale      4.  3.100 /  4.  3.100
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100

**Comment by bakape** [comment]
Please at least Google the errors.  If it says the address is already in use, then something is fucking already using it.

**Comment by serofir** [comment]
Google says nothing, also no one can use it, because it clean server, okay?

**Comment by serofir** [comment]
After reboot server it start, but not working at all.

2016/11/12 21:35:20 websockets: my_IP_here:58052: websocket: origin not allowed
2016/11/12 21:35:21 websockets: my_IP_here:58054: websocket: origin not allowed
2016/11/12 21:35:22 websockets: my_IP_here:58055: websocket: origin not allowed
2016/11/12 21:35:23 websockets: my_IP_here:58056: websocket: origin not allowed
2016/11/12 21:35:24 websockets: my_IP_here:58057: websocket: origin not allowed
2016/11/12 21:35:26 websockets: my_IP_here:58058: websocket: origin not allowed
2016/11/12 21:35:28 websockets: my_IP_here:58059: websocket: origin not allowed
2016/11/12 21:35:31 websockets: my_IP_here:58060: websocket: origin not allowed

**Comment by serofir** [comment]
When i go to my_server_ip:8000 - i see meguca trying to connect, but always disconnected, again and again.

**Comment by bakape** [comment]
See `./meguca --help`. Specifically, the origin flag must match your outer access origin, if not accessing from localhost (`my_server_ip:8000`).

**Comment by serofir** [comment]
Ok, it works now. Thank you.
