### ISSUE TITLE
Board deletion

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#402]
How to delete board?
I don't see anything about it, i see button to make board, ok, but how to delete?

How to delete thread, post, pic, etc?
How to be mod, and moderate board?
No any information about this funcionality.

**Comment by bakape** [comment]
Not implemented yet.

**Comment by serofir** [comment]
It's a bit shocking.

**Comment by bakape** [comment]
I am basically the only developer and work on meguca in my free time. Nothing shocking there.

**Comment by serofir** [comment]
Your Meguca - awesome thing, thank you for working with it.
I hope someday we will celebrate the release.
