### ISSUE TITLE
errors when trying to run or update meguca

### ISSUE THREAD

**Issue by NIXOYE** [bakape/meguca#410]
after following all the install instructions here https://github.com/bakape/meguca/blob/master/docs/installation.md

I try
>./meguca -a :80

but I get 
>2016/12/20 00:07:26 error connecting to RethinkDB: gorethink: dial tcp 127.0.0.1:28015: getsockopt: connection refused

and when I do 
>make update_deps all

I get
>make: *** No rule to make target 'update_deps'.  Stop.

**Comment by bakape** [comment]
What distribution and version?

What do `which rethinkdb` and `/etc/init.d/rethinkdb status` print?

**Comment by NIXOYE** [comment]
>which rethinkdb
gives

>/usr/bin/rethinkdb

and 
>/etc/init.d/rethinkdb status

gives

>rethinkdb: instance1: stop/waiting

**Comment by bakape** [comment]
What does `service rethinkdb start` print?

**Comment by NIXOYE** [comment]
nothing

**Comment by bakape** [comment]
Try `/etc/init.d/rethinkdb start` and see if meguca starts now.

**Comment by NIXOYE** [comment]
yup :D 
could you update the instructions page with that and also include the fact the install commands have to be run as root?
