### ISSUE TITLE
changing html for frontpage and adding a homepage

### ISSUE THREAD

**Issue by NIXOYE** [bakape/meguca#411]
How do i change the html of the frontpage so i can change the name of the board from /all/ to something else and so i can add a banner image so i can serve my webcomic so people can communicate while reading it.

Also, I'd like to be able to add a homepage like on Meguca v1
and id like to be able to add links to the top left corner to external sites like on meguca v1

**Comment by bakape** [comment]
>change the name of the board from /all/ to something else

/all/ is hardcoded and I don't think it should be a configurable option. That would introduce more complexity and an extra hard desync point between the server, database and clients. If  you really need to change it, replace all occurrences in the server and client source code. 

>add a banner
Banners

**Comment by NIXOYE** [comment]
>homepage
I'd like to be able to have dynamic elements but if not I'd settle for a static page

**Comment by bakape** [comment]
Since you want something custom, you'll have to write it yourself either way. Dynamic would be complicated, static is as simple as editing text though.

**Comment by NIXOYE** [comment]
Ok so how do i just do a static page

**Comment by bakape** [comment]
You write an HTML file and serve it to all root requests to your site via
reverse proxy configuration.
