### ISSUE TITLE
changing default settings

### ISSUE THREAD

**Issue by NIXOYE** [bakape/meguca#412]
I'd like to change the default settings on my instance so relative timestamps is enabled by default and to disable saucenao by default.

I'd also like to be able to change the default commands to start and finish a post. I want to submit a post with ctrl+enter and start a new post with ctrl+N (if its not possible to use ctrl I'd like to submit a post with alt+enter)

**Comment by bakape** [comment]
To change defaults modify `client/options/specs.ts` and recompile the client with `make client`. 

>Ctrl

Ctrl keybinds are traditionally much more tied to the operating system and browser, so their use in application keybinds is best avoided. To change the default key you can also just modify the same file as above.

**Comment by NIXOYE** [comment]
ctrl+enter is pretty traditional for submitting posts in forums though
i.e github
if its too much trouble i'll settle for alt+enter though, thanks

**Comment by bakape** [comment]
Well, all keybinds are currently Alt+<key> and I don't plan on changing that. But changing just the <key> default value is trivial, as described above.

**Comment by NIXOYE** [comment]
Ok sounds good thanks 💜

**Comment by NIXOYE** [comment]
@bakape where can i find what the numbers mean in relation to the keys?

**Comment by bakape** [comment]
http://keycode.info/
