### ISSUE TITLE
Custom per-board spoiler images

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#431]

**Comment by Chiiruno** [comment]
This will result in porn and goatse/gore spoiler images that can't be turned off in work mode, unless you force work mode to use the default spoiler image.

**Comment by bakape** [comment]
There technically is a NSFW setting in the board options. We could tie it
to that,

**Comment by Chiiruno** [comment]
No, I mixed up work mode with something else and deleted my post.
Just ignore my dumb comment for this issue.

**Comment by bakape** [comment]
No longer applicable to v7.
