### ISSUE TITLE
Add setting to permanently hide deleted posts

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#437]

**Comment by bakape** [comment]
Unneeded, as it introduces a censorship vector.

**Comment by Lightsockie** [comment]
How about a setting to toggle their display? tbh when I'm a dumb phone poster (and can't use macros) I'll sometimes repost the same image a few times (or the wrong image), and the lil trash can is kinda an eyesore. So if a user can toggle their display, we still get that aesthetic imageboard, but with the option to see the censorship overlay.

**Comment by bakape** [comment]
Yeah, this could work as an opt-in client-side option.
