### ISSUE TITLE
Remove exif data from images

### ISSUE THREAD

**Issue by tamamoe** [bakape/meguca#493]
from >>2022961 and >>2022958

(not that guy, but thought i'd post this anyway since i have nothing better to do)

**Comment by bakape** [comment]
I am against modifying the source image in any way. I want the image you download from meguca to be exactly as it was originally uploaded. Let's say you download an image from some other imageboard or a booru, or wherever. Now, after you upload it to meguca, it will no longer match the image from the source. You won't be able to use non-fuzzy image search to track the image to it's source and find any related information. For those using meguca for image-sharing this is crucial. If you need EXIF stripped for privacy reasons, do it manually.
