### ISSUE TITLE
/assets/es6/main.js Error - url as comment

### ISSUE THREAD

**Issue by phyziqx** [bakape/meguca#536]
Hiya,

This line,
```javascript
const url = "https://noembed.com/embed?url=" + el.getAttribute("href"), [data, err] = yield util_3.fetchJSON(url);
```
needs the // escaped otherwise the rest of the line is parsed as a comment
```javascript
const url = "https:\/\/noembed.com/embed?url=" + el.getAttribute("href"), [data, err] = yield util_3.fetchJSON(url);
```

**Comment by phyziqx** [comment]
Actually this applies in MANY locations!....
All instances of http(s):// in /www/js/es6/main.js   need to be properly escaped

**Comment by bakape** [comment]
What? The // is inside a string literal. Why would it ever be parsed as a comment?

**Comment by phyziqx** [comment]
@bakape not sure, but that is what is happening in chrome for me, after escaping string all works well.
This occurs when running via a reverse proxy and not when navigating to the IP directly

**Comment by bakape** [comment]
What reverse proxy? Your reverse proxy is probably tampering with the JS. Those are not comments to proper JS parsers. Consider submitting a bug report to your reverse proxy project.

**Comment by phyziqx** [comment]
@bakape I'm using nginx locally and then to cloudflare, pretty common use case.
Pretty much using your provided nginx example config as well.
No matter, I modified the js to function properly in my case. Being such a common case I thought it best to pass on what i found.

**Comment by bakape** [comment]
What nginx version are you using? Did you enable any JS processing CF-side like minification?
