### ISSUE TITLE
Support Casbin as the authorization module

### ISSUE THREAD

**Issue by hsluoyz** [bakape/meguca#560]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current authorization in go/src/meguca/server/admin.go. I can make PR if needed. Let me know if there's any question:) Thanks.

**Comment by bakape** [comment]
Casbin seems nice, but I don't see the point of using it for meguca at this time. Meguca already has a static hierarchical RBAC, and I don't plan to enable board owners to add more roles. Meguca also uses PostgreSQL, there might be incompatibilities with the MySQL adapter.

**Comment by bakape** [comment]
Closing as stale.

**Comment by hsluoyz** [comment]
Hi @bakape ,

I thing you made a good point. Just for a update, Casbin just added support for PostgreSQL via the [Xorm-adapter](https://github.com/casbin/xorm-adapter). Xorm is a ORM that supports a number of DBS which include PostgreSQL.
