### ISSUE TITLE
Cannot change admin password & broken css on boards

### ISSUE THREAD

**Issue by ewhal** [bakape/meguca#563]
CSS breaks on boards http://localhost:8000/b/
`GET http://localhost:8000/assets/css/.css `
![imgur](https://i.imgur.com/e3QiuXx.png)

Receive this error when submitting change password for admin
```
fetch.ts:15 POST http://localhost:8000/html/change-password 405 (Method Not Allowed)
(anonymous)	@	fetch.ts:15
(anonymous)	@	main.js:6
__awaiter	@	main.js:2
postJSON	@	fetch.ts:14
(anonymous)	@	common.ts:47
(anonymous)	@	main.js:6
__awaiter	@	main.js:2
postResponse	@	common.ts:43
send	@	password.ts:13
submit	@	forms.ts:54
FormView.on.e	@	forms.ts:29
```

**Comment by bakape** [comment]
Fixed password changing and the CCS error was due to new boards not setting default theme on creation. If you click `Configure Board` > `/b/` and simply submit the form as it is, /b/ will have a default theme set now. Any board created after this will have a default theme properly set.
