### ISSUE TITLE
Open board configuration, after creating a board

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#567]

**Comment by Chiiruno** [comment]
A board owner should be able to open the configuration himself, this doesn't seem to have any real positive effect, and potentially a negative effect if the board owner leaves the tab open and walks away.

**Comment by bakape** [comment]
>if the board owner leaves the tab open and walks away.
Session is still active. BO is a bwaaka then.

**Comment by Chiiruno** [comment]
>Session is still active. BO is a bwaaka then.

Good point. BO is a bwaaaka.

**Comment by bakape** [comment]
No longer applicable to v7.
