### ISSUE TITLE
ffmpeg: Operation not permitted

### ISSUE THREAD

**Issue by Miao14** [bakape/meguca#568]
When uploading a webm you get "ffmpeg: Operation not permitted", also you can only select upload max size for images and not the webms.

**Comment by Miao14** [comment]
It seems to be any kind of webm really from the tests i have done.

**Comment by bakape** [comment]
Okay, what OS is the server running/was compiled on? 
What is the output of `ffmpeg -version`?

**Comment by Miao14** [comment]
ffmpeg:
[meguca@DK8 ~]$ ffmpeg -version
ffmpeg version 2.6.8 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-4)
configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfaac --enable-nonfree --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
libavutil      54. 20.100 / 54. 20.100
libavcodec     56. 26.100 / 56. 26.100
libavformat    56. 25.101 / 56. 25.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 11.102 /  5. 11.102
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  1.100 /  1.  1.100
libpostproc    53.  3.100 / 53.  3.100

OS: Centos7.2

**Comment by bakape** [comment]
Meguca requires at least ffmpeg 3.1, but 3.2 is recommended.

**Comment by Miao14** [comment]
Seems to be fixed, although i would like to point out that while installing ffmpeg 3.2 its still require ffmpeg2.8-devel because of ./meguca: error while loading shared libraries: libavcodec.so.56: cannot open shared object file: No such file or directory
Thank you for the help.

**Comment by bakape** [comment]
That is most likely a CentOS-specific problem.

**Comment by ffchinajoy** [comment]
error.c
  { EERROR_TAG(EPERM),             "Operation not permitted" }

you do not have the right of webcam ?
