### ISSUE TITLE
Thread deletion doesn't trigger cache update

### ISSUE THREAD

**Issue by Kagami** [bakape/meguca#578]
Here is thread deletion SQL: https://github.com/bakape/meguca/blob/master/go/src/meguca/db/sql/upkeep/delete_thread.sql
Here is board counter SQL: https://github.com/bakape/meguca/blob/master/go/src/meguca/db/sql/boards/board_counter.sql

It won't bump the `replyTime` thus deleted threads will persist in the cached pages.

**Comment by bakape** [comment]
Is that much of a problem? Any other bump to the board will cause refresh and the thread will no longer be displayed. It will still remain in the cache though, until the cache reaches the memory limit and expunges it. Hmm, maybe purge a thread from the cache on `sql.ErrNoRows`?

**Comment by Kagami** [comment]
>Is that much of a problem?

Well, it's kind of annoying if you want to delete few threads on a slow board.

>on sql.ErrNoRows

When this would be raised?

I'm thinking about `pg_notify('thread_deleted', id)` and cleaning board cache for that id.

Or maybe bump `replyTime` of first thread on the board. This won't work if we want to delete last thread.

Or add field `replyTime` to the boards table.

What do you think?

**Comment by bakape** [comment]
> When this would be raised?
When a thread is accessed directly, not through a board page. Admittedly,
that won't be too often.

>pg_notify('thread_deleted', id)
Yes, that sounds best. I'll go with that, but instead of clearing the
entire board cache, should probably just delete all cached pages for that
thread and rebuild the board cache without it, and clear the catalogue
cache. Thoughts?

**Comment by Kagami** [comment]
Sounds good.
