### ISSUE TITLE
Thumbnailing taking too much time without high resource usage

### ISSUE THREAD

**Issue by vaguiners** [bakape/meguca#590]
Any uploaded file takes too long in the thumbnailing process. Even mp3 songs. By monitoring the server, I saw that it uses almost nothing of the cpu during the process.

**Comment by bakape** [comment]
Are there any reverse proxies between the client and the server? Progress detection is done client-side, so reverse proxies will make you believe the server is already processing the file, when it's only been uploaded to the proxy.
