### ISSUE TITLE
Image cleanup might happen during post creation

### ISSUE THREAD

**Issue by Kagami** [bakape/meguca#592]
If I understand correctly, there is a race between post creation and unused images cleanup. Things might go like this:

1. [WriteImage](https://github.com/bakape/meguca/blob/a5df568200b1dce2f50e217e5772483226385e41/go/src/meguca/db/images.go#L28) new image
2. [deleteUnusedImages](https://github.com/bakape/meguca/blob/a5df568200b1dce2f50e217e5772483226385e41/go/src/meguca/db/upkeep.go#L194) removes just written image
3. [getImage](https://github.com/bakape/meguca/blob/a5df568200b1dce2f50e217e5772483226385e41/go/src/meguca/websockets/post_creation.go#L361) fails because there is no such image anymore

Am I right? What's the best fix for this in your opinion? Maybe `deleteUnusedImages` shouldn't return images with an enty in `image_tokens` table?

**Comment by bakape** [comment]
You're right. If the cleanup runs between [these 2 calls](https://github.com/bakape/meguca/blob/a5df568200b1dce2f50e217e5772483226385e41/go/src/meguca/websockets/post_creation.go#L83-L101), then a race can occur.

Best solution would probably be to rearrange the calls a bit and call `db.UseImageToken()` and `db.InsertPost()`/`db.InsertThread()` in the same transaction. Thoughts?

**Comment by Kagami** [comment]
Even if `UseImageToken` and `InsertPost` are in the same transaction, cleanup will still remove image created by previous HTTP `/api/upload` call and post creation will fail, won't it?

**Comment by bakape** [comment]
See the [SQL query](https://github.com/bakape/meguca/blob/a5df568200b1dce2f50e217e5772483226385e41/go/src/meguca/db/sql/upkeep/delete_unused_images.sql#L4). `/api/upload` always allocates an image insertion token. As long as there is at least one of those, the image should not be deleted.

**Comment by Kagami** [comment]
Ah, right, I looked at the previous version of this query.
Yes, keeping `UseImageToken` and `Insert*` in single tx should fix the race.
