### ISSUE TITLE
Hash command calculations

### ISSUE THREAD

**Issue by vaguiners** [bakape/meguca#595]
perform mathematical calculations and etc. and with a number limitation on the answer to not shit at all

**Comment by bakape** [comment]
What?

**Comment by vaguiners** [comment]
#1+1
Answer: 2

**Comment by bakape** [comment]
Why the fuck can't you use a calculator?

**Comment by vaguiners** [comment]
It was an example. It could be something a little more complete like wolfram

**Comment by bakape** [comment]
Then use fucking wolfram. An imageboard is not a fucking scientific calculator.
