### ISSUE TITLE
link from filename is not from cdn

### ISSUE THREAD

**Issue by vaguiners** [bakape/meguca#596]
that's it

**Comment by vaguiners** [comment]
It's the same thing in google search and saucenao

**Comment by bakape** [comment]
Yes, and? Neither of those are imageboards. Appealing to authority is a
shitty argument to begin with.

**Comment by vaguiners** [comment]
im talking about the "Image root override" option.

**Comment by bakape** [comment]
Oh, that. It can't be from the CDN, because it would violate CORS and that disables a bunch of things, including saving with the original file name.

**Comment by vaguiners** [comment]
so this option is fucking useless?

**Comment by bakape** [comment]
It works for thumbnails and expanded images, which is most of the traffic.

**Comment by vaguiners** [comment]
What if the images are accessible only by the changed link?

**Comment by bakape** [comment]
CORS restrictions apply.
