### ISSUE TITLE
Per page board cache

### ISSUE THREAD

**Issue by Kagami** [bakape/meguca#597]
Currently when client requests some board page after server restart, all threads of this board will be queried and placed to the cache: https://github.com/bakape/meguca/blob/3fc8f53d3fca47b7d6b7361a5c209fc990cf7129/go/src/meguca/server/cache.go#L108-L120
This might be huge amount of data and SQL requests if you have a lot of long-lived threads, e.g. 100+ pages.

I think it would be better to query data only for the page client currently requested and request more as soon as they are needed.

**Comment by bakape** [comment]
Good point. How would you change the current system to implement this?

**Comment by Kagami** [comment]
Seems like `boardCache` frontend is only getting called from `boardPageCache` in order to fetch specific page. So it would probably be enough to request `threadCache` for thread IDs of single page.

**Comment by bakape** [comment]
Maybe calculate which thread goes into which page, but defer the fetches of individual threads till the page is requested?

**Comment by Kagami** [comment]
Sounds good.

**Comment by Kagami** [comment]
I've implemented this in cutechan:
https://github.com/cutechan/cutechan/blob/5472071/go/src/meguca/server/cache.go#L65-L112

**Comment by bakape** [comment]
Oh, thank you, but I currently have plans for reworking feeds to contain
live-syncing caches, so the current cache design will become mostly
redundant then.

On 2 May 2018 12:13 pm, "Kagami Hiiragi" <notifications@github.com> wrote:

I've implemented this in cutechan:
https://github.com/cutechan/cutechan/blob/5472071/go/src/meguca/server/cache.go#L65-L112

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/bakape/meguca/issues/597#issuecomment-385914712>, or mute
the thread

**Comment by Kagami** [comment]
>reworking feeds to contain live-syncing caches

I'm curious, how would that work?

**Comment by bakape** [comment]
Yes, all HTML will be built on the client-side and almost all data will be
retrieved through websockets. You can see a (somewhat broken) partial
implementation on meguca right now, if you add a `wasm=true` query
parameter to the URL. Unless the data race keeps triggering and it crashes
with an out of bounds memory access each time. I'm working on it.

**Comment by Kagami** [comment]
I see. I don't like full-blown SPA because they're slower to render on refresh. DOM API is not fast and it takes quite noticeable time before JavaScript kicks in.

**Comment by bakape** [comment]
WASM

**Comment by Kagami** [comment]
WASM can't use DOM API directly, you need to use slow interop via JS.

**Comment by bakape** [comment]
Yes, but you still gain speed, if you spend more time on internal
calculations than pure DOM writes (+ some FFI overhead).

**Comment by Kagami** [comment]
What are interval calculations?

It would be interesting to see benchmarks but I suppose first-time render of served HTML will be faster than WASM + data. The former is much more optimized by the browser itself, the latter will have to go through several additional abstraction layers.

**Comment by bakape** [comment]
>What are interval calculations?
Anything that has to be done between dumping changes to the DOM. In
meguca's case it is a fair amount of parsing and diffing, that happens
almost on every keypress + state management/updates.

>t would be interesting to see benchmarks
Remind me in 6 months or so.
>first-time render of served HTML will be faster than WASM + data
True.

**Comment by bakape** [comment]
Still can be done, if post DOM is pre-rendered and state serialized in C++ on the server.

**Comment by bakape** [comment]
Boards dropped from v7.
