### ISSUE TITLE
Typescript is broken

### ISSUE THREAD

**Issue by barney1511** [bakape/meguca#609]
Pulled from the main branch since version 4.4.0 was giving me client build errors despite the fact that I have all dependencies.

Built on Debian 9 with no issues and it's exposed to the web properly, however any buttons or modals driven by typescript simply do nothing.

The loading gif is looping ad infinitum. Here is a screencap of the errors in the developer menu.

![4a7c32a1f2f61a0c5eba1576226eba85](https://user-images.githubusercontent.com/7857755/32740824-dafd73a0-c8ac-11e7-91ae-c6433dc74319.png)

If there's anything else I can provide, feel free.

**Comment by bakape** [comment]
Pushed a fix for one of the errors. See, if anything changes.

**Comment by barney1511** [comment]
Building currently. FYI, your site just broke as well, same issues more or less. You might wanna look into it.

**Comment by barney1511** [comment]
One of the issues is gone yeah, but it doesn't change anything. It's just gone from the console.

**Comment by bakape** [comment]
Seems like the issue was with minification, should be fixed now.
