### ISSUE TITLE
Option to disable upload of pics when no administrator or moderator  online

### ISSUE THREAD

**Issue by CardealRusso** [bakape/meguca#612]
but let post texts

**Comment by bakape** [comment]
Could you explain the reasoning and how exactly you think this could work?

**Comment by CardealRusso** [comment]
You see, I'm not a programmer. It's pretty normal for small imageboards that are starting now to suffer raid of cp to be knocked over.

You only need to verify that the moderator or administrator is logged in. If nobody is (also check if they are in idle), disable image upload. To not create so many frustrations, do not prevent the user from posting with image, letting it post but only the text? Will be processed and the image will be discarded.
If you can only create topic with images, use a predefined generic image.

If you can do something more advanced it would be good. Let the image be sent by the user and the image be registered in the post. In the post will be the generic image and will become the image sent by the user as soon as a moderator or administrator logs in.

There must be other, more efficient ways of applying that idea.

For example, all images uploaded are usually available, but wait for some moderator or administrator to see them on the topic. If nobody (mod / adm) sees the image in less than (some time), swap for the generic image and change the original url of the image until it is seen.

What matters is to prevent image raid while there are no online team members

**Comment by CardealRusso** [comment]
It is necessarily restrictive for many imageboard owners. But most important of all is that this should be an option and of course deactivated by default

**Comment by bakape** [comment]
Yes, but I am thinking if there is some better solution, that still achieves the goal, but without being as damaging to regular posting.
