### ISSUE TITLE
FRQ: Board specific language

### ISSUE THREAD

**Issue by nehalem9001** [bakape/meguca#619]
I'd like to have a board specific language settings.

**Comment by bakape** [comment]
This used to be an option, but it severely complicated caching. Currently with our hybrid server-client rendering, this would be too taxing. I'd like to delay this until the client is rewritten in C++ and all post-related and moderation-related rendering is done client-side. This would allow us to reduce what is rendered and cached server-side. 

After the rewrite is complete, it can become both a board-level option (if the user has no override language set)  and a user-level option. As a downside, rendering without JS enabled would always use the default server language.

**Comment by bakape** [comment]
Language is now server-global.
