### ISSUE TITLE
Canceling unconfirmed post when 'live' feature is enabled.

### ISSUE THREAD

**Issue by nehalem9001** [bakape/meguca#621]
I've noticed, the post can be cancelled only before anything is written into the text area. After that only 'Done' button is present. Is it possible to change this behaviour? Is this a consequence of something with database or that state machine on client side?

**Comment by bakape** [comment]
I can actually. The post ID will still be used, but I can add a websocket command to remove the post, while it is still open. 
As an extra, posts with no text can be automatically removed on closing.
