### ISSUE TITLE
webp support?

### ISSUE THREAD

**Issue by CardealRusso** [bakape/meguca#646]
is that possible?

**Comment by bakape** [comment]
Does Firefox support webp yet?

**Comment by CardealRusso** [comment]
Make it like most people with some sanity and forget the existence of Firefox.
It still does not support Webp, and this is one of the endless reasons why this SJW browser is little (really very little) used nowadays. His only service is to be a standard browser on some Linux distributions, but few people use it natively.

Firefox today is what Internet Explorer 6 was one day, a browser with the only utility of downloading another browser.

Desktop usage: 
http://gs.statcounter.com/browser-market-share
Firefox: 5.66%
https://analytics.wikimedia.org/dashboards/browsers/#all-sites-by-browser
Firefox: 7.4%

Mobile usage
http://gs.statcounter.com/browser-market-share/mobile/worldwide/
Less than 1%

**Comment by bakape** [comment]
Yes, but there are more FF users among imageboard users than in general.

**Comment by CardealRusso** [comment]
This is not true, and you are being unfair.

**Comment by bakape** [comment]
I administrate an imageboard, so perhaps I would know something about it,
no?

**Comment by CardealRusso** [comment]
How about showing us some sources? Just talk anyone can.
It is simply impossible.

I particularly use Ungoogled-Chromium and I think that anyone who goes imageboard and has a modicum of intellect should not use anything else.

**Comment by bakape** [comment]
> How about showing us some sources? Just talk anyone can.

I don't datamine my users, but I do ask for the used browser on any bug
report. A sizable number of those are from Firefox.

>It is simply impossible.
>anyone who goes imageboard and has a modicum of intellect should not use
anything else

Hot opinions.

**Comment by CardealRusso** [comment]
>I don't datamine
So, you have no trustable source for your information.

You preach free will in meguca but you actually decide what pleases you.

**Comment by Chiiruno** [comment]
@bakape I would like to see webp support, and I'm not really concerned with firefox.
Does the current image manipulation chain support webp?

**Comment by bakape** [comment]
>Does the current image manipulation chain support webp?
Yes.
>Will this be implemented in mainline meguca?
No, because currently only Chromium and derived browsers support webp.

**Comment by Chiiruno** [comment]
@bakape So we're not going full "fuck firefox", then?

**Comment by bakape** [comment]
It still kinda works with the latest version. The parts that don't are
caused by FireFox bugs, i. e., functionality that they claimed to work but
does not in actuality. This will essentially make meguca only function as
an imageboard for Chromium browsers.

**Comment by Chiiruno** [comment]
Well, I guess since the site is served via HTTP from the server to the client (browser), we do have to ensure at least a minimal ability to work.
But honestly, I can't say I'd mind if meguca only functioned fully for Chromium, and noscript for firefox.

**Comment by bakape** [comment]
It won't function on NS FF.

**Comment by Chiiruno** [comment]
I know, but if you hated Firefox enough, you could just have to load a thumbnail saying to use Chromium.
Well, don't take me seriously, I'm just being stupid now.
