### ISSUE TITLE
2hu (and other anime girl) captcha

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#662]
It's annoying enough to work.

**Comment by bakape** [comment]
Better just adapt our current captcha lib.

**Comment by Chiiruno** [comment]
https://github.com/dchest/captcha seems to be number-only, would we have to rewrite it?

**Comment by bakape** [comment]
That's the plan - cut out the parts that matter and inline in our own
module.

**Comment by bakape** [comment]
To consider: 
>https://patents.google.com/patent/US20090328163A1/en

@Chiiruno What do you think?

**Comment by Chiiruno** [comment]
Seems pointless, any anti-captcha bot worth its salt will just get the captcha from a still frame and figure it out from there.
Also looks like hell to implement.

**Comment by Chiiruno** [comment]
Unless it's letter/number by letter/number, but honestly it wouldn't be too hard for a bot to figure that out either.

**Comment by bakape** [comment]
What if the captcha never fully appears during any frame? Granted that is
security by obscurity.

**Comment by Chiiruno** [comment]
Then the bot would be programmed to splice two or more frames together.

**Comment by bakape** [comment]
What other challenge can we use in place of recognizing text characters?
2hu captcha is sounding more and more desirable with time. But it should be
something comletable in 10s or less. Should probably dig around for more
papers.

**Comment by Chiiruno** [comment]
Not really sure, but even as far as the 2hu captcha goes, there's still the possibility that the bot might be able to "find" danmaku and avoid them, but I'm not sure if that's possible without memory reads. I guess it's possible to get the color of the danmaku and trace them off of that, but who knows if that's time-efficient enough to work.
Yeah, I was thinking 10 seconds or less too, I'll have to tweak it as I go along to find what's best.

**Comment by bakape** [comment]
Maybe some other simpler (and simpler to program) minigame as an
alternative? What could work while still being moderately hard for bots and
resistant enough against classic captcha solving services (those are
probably almost all image-based)?

**Comment by Chiiruno** [comment]
I hate to admit it, but contextual captcha is a good option, but I don't want google scripts anywhere near meguca if possible. Of course, implementing ourselves would be pointless, since the whole point of google captcha is that it's more or less random each time, so a bot can't build a list of passable images.

Noscript google captcha would be an option, but I wouldn't want any part of it, the whole thing with google captcha leaves a sour taste in my mouth.

It really depends on the threat model, and as far as I can tell, 2hu captcha should be enough, I don't think someone is going to build a fucking memory reading hack for an image board.

**Comment by Chiiruno** [comment]
Well, the best way to fool a computer is context, as well as human feeling and pattern recognition.
I feel that goes beyond the scope of meguca though.
Do you want to pioneer some ridiculous captcha that can't be solved until an advanced enough AI develops that can tell these human-specific contexts?

**Comment by bakape** [comment]
Ideally I would want to build a reusable library and let it loose.

**Comment by bakape** [comment]
I want to find a paper with a good idea and implement it to some extent.

**Comment by Chiiruno** [comment]
Of course, 2hu captcha will be a Rust and Rust/WASM library for everyone.
I wouldn't be surprised if fucking 4chan implemented it if it got popular enough.

>I want to find a paper with a good idea and implement it to some extent.

Try asking on /g/, or even 8/tech/, you'll be able to multiply your search net.

**Comment by bakape** [comment]
Or alternatively do something really dumb like unicode emoji captcha. Just need a decent rendering and image transformation filter then.

**Comment by Chiiruno** [comment]
Bots will probably be able to detect emoji with ease, since there's a lot of repeated patterns.

**Comment by bakape** [comment]
Okay, I'll mull this over some more today. Need to go now.

**Comment by Chiiruno** [comment]
Itterashai~

**Comment by Chiiruno** [comment]
Ties into #778

**Comment by bakape** [comment]
But noscript google captcha in a contained iframe is a pretty decent
alternative.

**Comment by Chiiruno** [comment]
Like I said, I can't deny it on it's technical merit. I just don't want to be part of it, I don't really want that cancer to infest meguca. Just make sure it's restricted as much as possible if you do it, please.
Try asking meguca about this during busier hours, or maybe I will if I'm awake, some gucas might be able to give some good ideas.

**Comment by Chiiruno** [comment]
Oh, there is one problem with noscript captcha, if you use umatrix, you have to turn off 'spoof `referrer` header', or else the captcha will endlessly cycle or error.

**Comment by bakape** [comment]
Wait, does cropping an image prevent it from being detected on saucenow? Let's check.

**Comment by bakape** [comment]
No, cropping won't work. What is non-lossy (in terms of depicted objects) way to render an image undetectable by iqdb and saucenao?

**Comment by bakape** [comment]
Let's say you have this set of images: https://gelbooru.com/index.php?page=post&s=list&tags=1girl+cirno+rating%3asafe
How do you make them undetectable though IQDB, saucenao and other image search engines while still retaining enough information to identify Cirno? We could do cropping with account to some false negatives, maybe.

**Comment by bakape** [comment]
>https://github.com/hybridgroup/gocv
>https://github.com/nagadomi/lbpcascade_animeface

I'm fucking doing this.

**Comment by bakape** [comment]
Ideas:
- 3x3 grid
- pull randomly from gelboorus with '1girl rating:safe $2hu_name'
- performance:
  - always pull 2/3 of processed images from cache - 1/3 is always freshly generated, if any unused images in the source  
  - store cache on disk with max size (bytes) and LRC pruning

- on connection problems fall back to cache-only mode 
- make it work 100% noscript
  - possible usability improvements
- separate library
  - include API server for easy deployment
  - AGPL bitches!
- shill on 4chan to inspire botnet hate

**Comment by bakape** [comment]
Work will proceed in https://github.com/bakape/anicha. This issue will refer to integrating anicha with meguca.

**Comment by Chiiruno** [comment]
>be gone for 3 hours
>work on computer internals
>a fucking project

Well, okay. At least I can work on the (my) 2hu captcha at a more leisurely pace now.
This seems a bit more sane anyway, and a hell of a lot easier to implement.

**Comment by Chiiruno** [comment]
>How do you make them undetectable though IQDB, saucenao and other image search engines while still retaining enough information to identify Cirno? We could do cropping with account to some false negatives, maybe.

Changing to color slightly probably. Unless their neural net can detect that too.

**Comment by Chiiruno** [comment]
3 of the blocks should be the correct answer, so 6 other blocks are random 2hus, but 3 are say, Cirno.
These blocks should be randomized in order.
Admin should set, since spam prevention is a site-wide issue, and it's possible to find characters that there are very few of, so some BO could set it to someone like that and bypass a lot of the captcha by less possibilities.

**Comment by Chiiruno** [comment]
Also if there's only like 3 images for a character, it would be possible for all of them to be it, and that would confuse the user.

**Comment by bakape** [comment]
> > be gone for 3 hours
> > work on computer internals
> > a fucking project

Such is life.

**Comment by Chiiruno** [comment]
Should probably have an example (different than correct images) image of the correct character in the top like in google captcha, since it's unreasonable to expect everyone to know every possible anime character.
Not so much a problem with 2hus, but honestly I'd do it with that too.

**Comment by bakape** [comment]
That opens up one more botting vector though - NN that detects the same
character.

**Comment by Chiiruno** [comment]
Maybe there's a better way, perhaps information on what kind of sex or hair color or long/short hair or type of dress.
There has to be some sort of information available.
It might be possible to reuse tags to some extent.

**Comment by Chiiruno** [comment]
We could possibly do this without even naming the character by having 3 images containing the same character as defined by the server being the correct answer, with all the others being other characters, and possibly more than one of the same possible wrong characters.

**Comment by Chiiruno** [comment]
Another option to reduce possibilities of a bot matching, would be to have the 9x9 grid have all different characters, with only one of them being the correct one.

**Comment by bakape** [comment]
Oh, that's a good point.

**Comment by Chiiruno** [comment]
This might be helpful in some way.
https://github.com/antonpaquin/IsItAnime

**Comment by bakape** [comment]
Depends on #663
