### ISSUE TITLE
Captcha ban time

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#665]
Looking through the code, it seems it only bans for 2 days which is reasonable, but some anons are complaining about it lasting like 2 months.
Might be worth it to double check the code.

**Comment by bakape** [comment]
Some anons are retarded https://meguca.org/html/bans/all

**Comment by Chiiruno** [comment]
Did some anon mistake an actual ban for a captcha ban?
If so, I'll close.

**Comment by bakape** [comment]
There was spam, so yes.
