### ISSUE TITLE
TOR/I2P domain

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#673]
Internet censorship is scary, I think meguca needs a .onion and a .i2p.
Disabling image uploading for TOR/I2P could work if CP is a problem, I guess.

**Comment by bakape** [comment]
Do people actually use i2p?

**Comment by bakape** [comment]
https://www.makeuseof.com/tag/create-hidden-service-tor-site-set-anonymous-website-server/
https://linuxsecurityblog.com/2015/04/20/setting-up-a-darknet-website-with-i2p-on-ubuntu/

**Comment by Chiiruno** [comment]
I wouldn't say it's used as much as TOR, but it would be a good backup for if TOR manages to get censored/shut down. There's some comfy I2P eepsites too.

**Comment by bakape** [comment]
Okay then. Also, this week has been full of shit, so I have not had much progress on rewriting the DB SQL. Only 3 files out of the howeverthefuckmanywehave rewritten.

**Comment by Chiiruno** [comment]
I and many other anons appreciate the hard work.
Meguca is a faily large project, I certainly would have a lot of trouble trying to redo the entire SQL structure.

**Comment by bakape** [comment]
Not the structure, just the way queries are built and executed. But I'm also writing some small DB changes and unit tests as I go.

**Comment by Chiiruno** [comment]
We should still do this, @bakape 
I'd hate to not be able to get to meguca one day because the nameservers get fucked for some legal reason/internet DNS attack.

**Comment by bakape** [comment]
How do you even register one? Can I leave this to you?

**Comment by Chiiruno** [comment]
Sure, I'll look into it.
If there needs to be anything like a private key though, you should generate that yourself, for security reasons.
I'll post updates.

**Comment by Chiiruno** [comment]
Looks like you can easily generate a TOR address with [this software](https://github.com/lachesis/scallion). I suggest using `scallion [whatever] meguca`
You'll need to generate that yourself, again for security reasons.

**Comment by Chiiruno** [comment]
Basically you just enable the TOR service and point the torrc config file to the server. See: https://www.makeuseof.com/tag/create-hidden-service-tor-site-set-anonymous-website-server/
```
# Hidden Service
HiddenServiceDir C:\Users\Name\tor_service
HiddenServicePort 80 127.0.0.1:80
```

**Comment by Chiiruno** [comment]
As for I2P, see: https://linuxsecurityblog.com/2015/04/20/setting-up-a-darknet-website-with-i2p-on-ubuntu/
As with TOR, you'll have to get into the config yourself.

**Comment by Chiiruno** [comment]
Following >8chan's model and disabling TORposting for the clearnet site while enabling it for the .onion would probably be a good idea.

**Comment by bakape** [comment]
What are the benefits to this?

**Comment by Chiiruno** [comment]
To TOR/I2P in general? The ability to circumvent restrictive internet firewalls and moderate privacy.
To following 8chan's model? Stopping bots using TOR from spamming via the clearnet domain, as well as improving privacy by ensuring all TOR posts are through the .onion.
I2P only works through the I2P domain thankfully, so setup will be minimal there.

**Comment by Chiiruno** [comment]
As for a later TOR-domain-only posting commit, I think checking if the client requesting to post is doing it through the TOR domain should be sufficient.

**Comment by Chiiruno** [comment]
Also, once you have the .onion and .i2p domains going, adding them to the info tab would be a good idea.

**Comment by Chiiruno** [comment]
Tying into #729, we should move a lot of the server config to a config file so that we can just add the I2P/TOR domain to it instead of further spamming the server configuration form.

**Comment by bakape** [comment]
Not a concern of meguca - deployment specific.
