### ISSUE TITLE
meguTV cuts the last ~2 seconds off the end of each video

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#689]
It also makes short videos impossible to watch.

**Comment by Chiiruno** [comment]
I am using Firefox, if this isn't an issue on chromium-based browsers or IE.

**Comment by Chiiruno** [comment]
Isn't this still a problem?

**Comment by bakape** [comment]
Yes, but I can't be assed to implement buffering on both sides. Non-trivial
by any means.
