### ISSUE TITLE
Meguca can't be built without altering $PATH and $GOPATH

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#703]
Meguca can't be built without the `$PATH` and `$GOPATH` being altered.
I believe the solution is to separate the client and the server into two separate repositories.
If you're up for this, or think it's a good idea, I'll put together the server and client repositories you can base the new repositories off of.
I think as far as the client repository goes, keeping the C++ and Rust (whenever you merge that) client in the same repository shouldn't be an issue, but the server should probably be in it's own.
I imagine the repositories will be named `meguca-server` and `meguca-client`.

If there's a smarter or better way, please do tell.

Also see for context: [nixpkgs/pull/39482](https://github.com/NixOS/nixpkgs/pull/39482)

**Comment by Chiiruno** [comment]
Actually, looking more into it, this seems unnecessary.

**Comment by bakape** [comment]
Rust is ded. I remember how shit it was. Maybe in another 5 years.
Also, the client and server will reuse some C++ code.

**Comment by Chiiruno** [comment]
Well that's a shame, I haven't used Rust in a while either, I thought it would have improved by now.
I guess that makes sense about client and server, since you're rewriting the server eventually in C++.

**Comment by bakape** [comment]
>rewriting the server eventually in C++
No no no no. Go has a good C FFI. Everyday logic in Go and the hotspots in
C++.

**Comment by Chiiruno** [comment]
>Everyday logic in Go and the hotspots in C++.
Well, that's smart. Get the speed where you need it, get the quality-of-life where you need it.
However, if you're already doing that, why not use C or even bare ASM in some parts?
