### ISSUE TITLE
Add tegaki to new post form

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#704]
I can't into JS for the life of me or figure out how to pipe this into the upload container, so here's a [bare-bones diff](https://github.com/bakape/meguca/files/1999249/tegaki.txt) of what I was thinking of.

**Comment by bakape** [comment]
Well, tell me, when you do and have it tested. You will probably need to look into downloading images from a canvas.

**Comment by Chiiruno** [comment]
I wonder if I could use the paste commit you just merged.

**Comment by bakape** [comment]
Probably a roundabout way to do it. Just use a canvas.

**Comment by Chiiruno** [comment]
Yeah, fuck this. Making JS with with TS is cancer and I'm not going to write a fucking tegaki drawer.

**Comment by bakape** [comment]
>fuck this

Now you speak my language.
