### ISSUE TITLE
Store commands in proper tables, not JSON

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#705]
Less error-prone and more database-side validation possible.

**Comment by bakape** [comment]
>Is this going to require a major rewrite?

Not too major. 

>If it does, do you already have an idea on how to do it?

A table with something like 
```sql
post_id bigint,
index smallint, --For ordering
type smallint,
data jsonb
```
See #706 for a reading example.

**Comment by Chiiruno** [comment]
The JSON functions in `common/commands.go` would have to be changed to SQL builder functions, right?
If you could give me a general idea of what go files will need to be edited, that would really help me get started on this.

**Comment by Chiiruno** [comment]
Oh good, I was thinking you were trying to get me to do it.
I was pretty sure I would have to break half of meguca before getting it working.
![sakurako](https://user-images.githubusercontent.com/30435868/40197806-1273968e-59da-11e8-83cb-7c9c457ce713.png)

**Comment by bakape** [comment]
After much trial and error, I have concluded the current JSON format is better for commands. 
@Chiiruno Please fix whatever you broke in the JSON of commands and resubmit the PR.
