### ISSUE TITLE
Format code

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#718]
The formatting and tabs are kind of uneven for the client, WASM client, and server.
Picking a formatter and putting a `format.sh` script in `scripts/` would help a lot, and make the code a lot prettier.
Code should be formatted before being pulled.

Inspiration:
https://golang.org/pkg/fmt/
https://www.npmjs.com/package/typescript-formatter
http://astyle.sourceforge.net/

**Comment by bakape** [comment]
I am against altering code by hooking into the commit process. It can make your own commit much harder to recognize. As for formatting, just set format on save in your editor. 
Go should use gofmt or goimports.
I will add a tsfmt.json for Typescript.
For C++ there is a .clang-format file in the project root.

**Comment by bakape** [comment]
Close this, if you this answers your question.

**Comment by Chiiruno** [comment]
>I am against altering code by hooking into the commit process. It can make your own commit much harder to recognize.

Fair enough, I think that answers my question.
