### ISSUE TITLE
Ensure all functions are tested for correct functionality

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#724]
Using [coveralls](https://coveralls.io) would be good for ensuring every function is at least called.

**Comment by Chiiruno** [comment]
Could also migrate from travis to [semaphore](https://semaphoreci.com/).

**Comment by bakape** [comment]
I've tried using coveralls at one point. Don't remember why I quit. Feel
free to implement it, but I find coverage is not as important in statically
typed languages.

**Comment by Chiiruno** [comment]
Except #725, anyway.

**Comment by bakape** [comment]
Merged. Let's see, if it even works.

**Comment by Chiiruno** [comment]
I'll have another commit for this, I found the problem.

**Comment by bakape** [comment]
I don't think it's working.

**Comment by Chiiruno** [comment]
Please see #726

**Comment by Chiiruno** [comment]
You might want to revert my coveralls commit, it ended up being ridiculous.

**Comment by bakape** [comment]
What happened anyway?

**Comment by Chiiruno** [comment]
It was just too difficult to put into the make process because this project has many packages.
A few other things too, if you end up wanting to go through with adding coveralls, you could probably use parts of some of my commits on the pull I linked yesterday.

**Comment by bakape** [comment]
Nah. Maxing coverage only matters for dynamic typelets.
