### ISSUE TITLE
'synced' will get pushed down if song title is too long

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#728]
Or if the window is too small.
![image](https://user-images.githubusercontent.com/30435868/40576607-074fd394-60bf-11e8-8e1f-eb3361696792.png)

**Comment by bakape** [comment]
That's normal, unless you know of some CSS magic to fix it for static size
fixed poitiom banners.

**Comment by Chiiruno** [comment]
I'm afraid not.

**Comment by bakape** [comment]
Oh, if you have nothing to do, you might try https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
Will probably require removing all the `float: right` properties.

**Comment by Chiiruno** [comment]
I'll look into it.

**Comment by Chiiruno** [comment]
Yeah, I can't into CSS.
What I imagine will work is something similar to the `#board-navigation` thing in `overlays.mixless` for `.banner-float`.

**Comment by bakape** [comment]
Ideally we still need to think of some solution without float, which is not meant for this and often breaks layouts. I'll mull this over later.

**Comment by Chiiruno** [comment]
Closed in 2a8562bc60f8500d71371ac2969e0e57a2780b1b
