### ISSUE TITLE
Youtube/Hooktube links will format itself

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#734]
We need to strip or disable formatting when it's a Youtube/Hooktube/Soundcloud/whatever link, since it nukes itself.

**Comment by bakape** [comment]
What?

**Comment by Chiiruno** [comment]
`?v=__3423` will become `?v=3423` in bold.

**Comment by bakape** [comment]
Oh, that. Just need move the link parsing right after code parsing then.
Think you can do it?

**Comment by Chiiruno** [comment]
I'm having a hard time finding the ideal place to do that.
Could you link me to a file and line where I could start and work my around?
I'm thinking `templates/body.go`.
Also I'm not entirely sure, but I would have to do the client and C++ client too right?

**Comment by bakape** [comment]
Okay, I'll put this on my TODO list then.

>but I would have to do the client and C++ client too right?

C++, Go and TS.

**Comment by Chiiruno** [comment]
Sorry, I'll eventually learn my way around.

**Comment by bakape** [comment]
I gave this some thought and did not come up with a sane solution. without major trade offs. I think the best thing to do would be to change the bold formatting marker (__) to something that almost never produces false positives, like ``, ~~ and **. Thoughts?

**Comment by Chiiruno** [comment]
-- and __ are definitely out the window, maybe try \\ or && or @@?

**Comment by Chiiruno** [comment]
`` is a good one too.

**Comment by bakape** [comment]
@@ probably.
