### ISSUE TITLE
Pyu disconnects

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#741]
Seems to happen EXACTLY in an hour, this is probably related to the user-specific pyu timer.

**Comment by Chiiruno** [comment]
@bakape If the site completely crashes, if you can, don't revert yet, I should be able to fix this.
No idea why it would corrupt the DB if that's what's going on though, maybe it's fucking up the program itself somehow instead and that fucks up the DB.

**Comment by Chiiruno** [comment]
Also what's weirder is that this wasn't an issue with local testing, could it be same IPs overwriting each other somehow?

**Comment by Chiiruno** [comment]
It may be that #pyu stalls the DB for a little bit since there's a good amount of PSQL commands.

**Comment by Chiiruno** [comment]
Crash candidates: https://github.com/bakape/meguca/commit/64e73c2ec82bb060f94d4aab17fc7106a8621c61#diff-dc141ab8267bbbe9e712bc826a1d9e38R155

**Comment by Chiiruno** [comment]
It's not during a #pyu command, so this definitely has something to do with the hour pyu timer.

**Comment by Chiiruno** [comment]
https://github.com/bakape/meguca/commit/64e73c2ec82bb060f94d4aab17fc7106a8621c61#diff-08e7384b5190f59ac0f884467384ccffR762
https://github.com/bakape/meguca/commit/64e73c2ec82bb060f94d4aab17fc7106a8621c61#diff-08e7384b5190f59ac0f884467384ccffR767
Also maybe the indexes somehow?

**Comment by Chiiruno** [comment]
This may happen an hour after every #pyu, this why it happens in chunks of 4 or more disconnections.
I'm not sure why the timer would do that though, did I get the logic wrong? Is it something else? The SQL should be valid.

**Comment by Chiiruno** [comment]
Is the reason it corrupted the DB last time is because of the large volumes of #pyu?

**Comment by Chiiruno** [comment]
I can't reproduce this locally, if you get the chance and don't revert immediately, please do some print debugging on your end since I can't reproduce this locally.

**Comment by Chiiruno** [comment]
It's also possible that the code itself is fine, but somehow the way it interacts with database updates is bad?
The reason why the DB hasn't been corrupted (yet?) may be cf122c72a139e835cd28211c4c0de0e86c85539f

**Comment by bakape** [comment]
Don't worry, cgo issue with signal handlers. Probably a coincidence with this patch. Fucking GraphicsMagick. We need to rewrite the thumbnailer to pure FFmpeg.

**Comment by bakape** [comment]
Okay, no. You are causing a segfault or something.

**Comment by Chiiruno** [comment]
Gah
Do you have any idea where?
Can you give me any information?

**Comment by Chiiruno** [comment]
Also has the DB been corrupted at all? I'm really curious about that.

**Comment by Chiiruno** [comment]
`500 json: error calling MarshalJSON for type common.Command: invalid character '}' looking for beginning of value`
Same thing as before, is this after recompiling with previous code?

**Comment by bakape** [comment]
Give me your email. I'll send over the error log.

**Comment by Chiiruno** [comment]
It's on my profile page. okinan@chiru.no

**Comment by Chiiruno** [comment]
Did you send? I haven't received anything.

**Comment by Chiiruno** [comment]
>123M
Oh boy, this'll be interesting.

**Comment by bakape** [comment]
It's just not rotated. Only the last few thousand lines matter.

**Comment by Chiiruno** [comment]
Is this related?
```
signal 11 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag
```
Disconnects seemed to happen every around every minute.
I can't find anything that particularly has to do with the pyu command though...

Except this.
```
goroutine 2108 [runnable]:
database/sql.(*Rows).awaitDone(0xc42141de00, 0xa562c0, 0xc421f698c0, 0x0, 0x0)
	/home/meguca/.local/go/src/database/sql/sql.go:2579
created by database/sql.(*Rows).initContextClose
	/home/meguca/.local/go/src/database/sql/sql.go:2572 +0x9c
```

**Comment by Chiiruno** [comment]
I think somehow the new #pyu command fucks with the update sql every minute function in db/util.

**Comment by Chiiruno** [comment]
https://github.com/bakape/meguca/blob/e257b2f2bf1c1997a81090369f646d28c3bd468d/go/src/meguca/db/upkeep.go#L19
https://github.com/bakape/meguca/blob/e257b2f2bf1c1997a81090369f646d28c3bd468d/go/src/meguca/db/upkeep.go#L37

**Comment by Chiiruno** [comment]
https://github.com/bakape/meguca/blob/e257b2f2bf1c1997a81090369f646d28c3bd468d/go/src/meguca/db/upkeep.go#L38
>`logError("open post cleanup", closeDanglingPosts())`

Uh, I wonder if that can fuck with #pyu, since it's a command that writes to the DB?
But wouldn't that also apply for #roulette?

**Comment by Chiiruno** [comment]
However, it would start sometime after an hour, so maybe this is the problem.
https://github.com/bakape/meguca/blob/e257b2f2bf1c1997a81090369f646d28c3bd468d/go/src/meguca/db/upkeep.go#L42

**Comment by Chiiruno** [comment]
https://github.com/bakape/meguca/commit/64e73c2ec82bb060f94d4aab17fc7106a8621c61#diff-dc141ab8267bbbe9e712bc826a1d9e38R158
Only thing I can think of is maybe removing `.Add(-time.Second)`, but I don't really think that will fix this, especially since it's clearly an hourly task fucking something up, and then the minute tasks start fucking up.

**Comment by Chiiruno** [comment]
@bakape I can't really see it, do you see what might be the problem taking everything I just said?
Any ideas for a solution?

**Comment by Chiiruno** [comment]
Maybe https://github.com/bakape/meguca/blob/e257b2f2bf1c1997a81090369f646d28c3bd468d/go/src/meguca/db/upkeep.go#L48 is affecting https://github.com/bakape/meguca/blob/e257b2f2bf1c1997a81090369f646d28c3bd468d/go/src/meguca/db/migrations.go#L682 or https://github.com/bakape/meguca/blob/e257b2f2bf1c1997a81090369f646d28c3bd468d/go/src/meguca/db/migrations.go#L687 somehow and that's causing the segfault?

I don't see anything on `runMinuteTasks()` that would cause those disconnects, though.
Are there any other things that run each minute?

**Comment by Chiiruno** [comment]
At any rate, if you can't see anything from those posts, would you mind writing some printf checks in various parts of the code to see what's segfaulting? I can't reproduce on my own so it'll have to be live.

**Comment by bakape** [comment]
[stack.log](https://github.com/bakape/meguca/files/2111380/stack.log)
Let's try analyzing this isolaed stack trace. First of all this is clearly a SIGSEGV (11). Now just need to find why. This line `
000000c4210d5768:  000000000082e6f8 <meguca/db.closeDanglingPosts+1256>  0000000000010206 ` seems suspicious, so your guess about the scheduled tasks is probably right. Why though?

**Comment by Chiiruno** [comment]
`closeDanglingPosts`
Oh boy, I had a feeling about that one.
I really have no idea though, the only thing I can think of is maybe it's somehow closing a half-completed #pyu command?
