### ISSUE TITLE
8chan-like TOR system

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#746]
TORposting is nice, but the problem is anons also use that to shitpost excessively.
A nice solution to allowing TOR, while stopping (immediate) board destruction would be to clear bans for all TOR IPs every month.
Since there's no "do this every month" timer in upkeep.go, and it would be unreasonable to expect the server to actually stay up for entire months at a time (realistically), perhaps using a timestamp in the DB for when the last TOR ban clear was and have that be checked every hour, or even day?

**Comment by Chiiruno** [comment]
An alternative would be to convert bans to 1-day bans for TOR IPs, and maybe add in a server option to disable TORposting for a bit if something like CP spam happens.
Ties into #673

**Comment by bakape** [comment]
Idea: clear 1 ban randomly with a random chance every hour (weights adjustable in configs).

**Comment by Chiiruno** [comment]
Mmmm, that sounds really inconsistent, I think I get what you're going for, but maybe not what's needed here.
On that note, clearing all bans every ~6 months might be a good idea too.

**Comment by bakape** [comment]
I basically don'y want people on TOR  to receive a pardon from bans like
that so easily. How do you detect TOR IPs anyway?

**Comment by Chiiruno** [comment]
Who knows, but considering the rest of the web is able to do it so easily, there's probably some list of TOR nodes that updates somewhere, we can just use that.
What do you think would be a good balance between allowing TORposting and ensuring TORposting can't be messed up by one autistic anon?
IIRC 8chan had a good model for that.

**Comment by Chiiruno** [comment]
I'd say that's already taken care of reasonably enough with the current captcha system.
Arguably because meguca asks more often, it's better, you have a good anti-spam system, it just doesn't ask up-front, which is what we maybe need for TOR IPs.

**Comment by bakape** [comment]
Depends on #663

**Comment by Chiiruno** [comment]
Idea: Tor-specific mode
- Depends on #910
- Temporarily ban TOR nodes as per #910, but allow viewing of board/posts
- Unban after X amount of time (Have it depend on when spam activity seems to drop via some sort of spam detection?)

**Comment by Chiiruno** [comment]
No longer depends on #910 
Might want to rethink this.

**Comment by Chiiruno** [comment]
Too much work, little need, pointless complexity.
Closing.
