### ISSUE TITLE
Add login limit to account

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#747]
Probably add a cooldown of 1 hour after 5 attempts. `<< 1` each next attempt to a max of 1 day. 
Need to track and cleanup logins in a table.

**Comment by Chiiruno** [comment]
Don't count if successful attempt.

**Comment by bakape** [comment]
What would this accomplish?

**Comment by Chiiruno** [comment]
You're the one who added it, I just added another constraint so that we don't count successful login attempts.
Feel free to close if you think this is unnecessary now.

**Comment by bakape** [comment]
I did?

**Comment by Chiiruno** [comment]
Yes.

**Comment by Chiiruno** [comment]
You added this issue, for clarity.

**Comment by bakape** [comment]
Ah, right. This prevents session spam.

**Comment by Chiiruno** [comment]
Fixed in https://github.com/Chiiruno/meguca_old/issues/45

**Comment by bakape** [comment]
No longer applicable with v7.
