### ISSUE TITLE
Reprogram wasm client with D

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#749]
https://github.com/CyberShadow/dscripten-tools
You may find D a bit more enjoyable to do the client, unlike Rust.
Has a (configurable) GC too, so you don't need to worry about a lot of memory management issues.

**Comment by bakape** [comment]
Rewrite about half of it and I'll take you seriously.

**Comment by Chiiruno** [comment]
Toolchain isn't mature yet, and I still can't stop flip flopping between D and Rust, so this is gay and I'm closing it.
