### ISSUE TITLE
Stop top banner for overflowing

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#758]
https://github.com/bakape/hydron/blob/master/client/main.less#L5-L27
Basically, have to make the banner a flexbox with no horizontal margins and padding and then make all the elements inside have margin-${left/right}: auto, according to the side they should flow to. Then have the middle one have overflow-x: auto.

**Comment by Chiiruno** [comment]
@bakape Do the thing!
![flail](https://user-images.githubusercontent.com/30435868/42072217-045e7e62-7b25-11e8-89d1-3ef001e23e05.gif)
