### ISSUE TITLE
Top banner when squished is ugly

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#762]
This is a bit ugly, perhaps this should be ellipsis, or something else?
![image](https://user-images.githubusercontent.com/30435868/42107033-97c593cc-7b9b-11e8-8f60-6d8242e75e6e.png)

**Comment by bakape** [comment]
Browser?

**Comment by Chiiruno** [comment]
Falkon, which is qtwebengine based.
I'll test what it does on Firefox and Chromium I guess.

**Comment by Chiiruno** [comment]
Firefox
![image](https://user-images.githubusercontent.com/30435868/42107353-a51caf5a-7b9c-11e8-95b7-686a0159838a.png)

Chromium
![image](https://user-images.githubusercontent.com/30435868/42107414-df094d22-7b9c-11e8-9a85-4293f954848f.png)
