### ISSUE TITLE
Top banner is off-center

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#763]
For the display, anyway, maybe it needs an offset instead of just putting it in the center between the larger right panel and the smaller left panel?
![image](https://user-images.githubusercontent.com/30435868/42107157-f8af9c50-7b9b-11e8-9ffc-c2c7a4a12dfa.png)

**Comment by bakape** [comment]
Problem with is that the offset is dynamic and would require JS to implement. I don't want to add even more JS.

**Comment by Chiiruno** [comment]
Are there any other options?
Basically with JS, you have to grab the window size and adjust the offset value in the CSS with it, right?

**Comment by Chiiruno** [comment]
What about faking the size of the left banner panel to match the right panel??

**Comment by bakape** [comment]
That would limit the maximum size of the header. Who cares that it's off
center, really?

**Comment by Chiiruno** [comment]
I mean, it's not that big of a deal, but honestly you'd be surprised who cares about things being off-center, if you really want to think about it.
Would a JS fix really be that much work? I guess you want to focus on the C++ client?
I can try my hand at it, all I really have to do is dynamically adjust the offset in the CSS with JS, right?

**Comment by bakape** [comment]
Pretty much.

**Comment by GoatSalad** [comment]
![image](https://user-images.githubusercontent.com/35391843/42118631-1090bb30-7bdb-11e8-85f3-e9ad65f8db99.png)
Disabling "margin-right" will properly center the banner between the left and right navigation tools, but still won't properly align the banner with the actual center of the screen.

I wonder if aligning it with the actual center would make sense though. There would be a lot of space wasted to the left of the banner unless the board navigation is as long as the stuff to the right, and that's almost always not the case.

**Comment by Chiiruno** [comment]
That's a good point, and is why I'm a bit conflicted.
On one hand, my autism demands it centered, on the other hand, wasted space is retarded.
