### ISSUE TITLE
Catalog does not parse formatted text

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#764]
Both /all/ and the board catalog.
![image](https://user-images.githubusercontent.com/30435868/42123137-51445fce-7c12-11e8-8bc2-e32f4d854aec.png)

**Comment by bakape** [comment]
RIght now catalog does not parse anything. It is all plaintext.

**Comment by Chiiruno** [comment]
Any ideas on how we could change this?

**Comment by bakape** [comment]
Adapt article rendering code for boards.

**Comment by Chiiruno** [comment]
Perhaps getting a list of OPs and then calling renderArticle in `templates/article.qtpl` for each?

**Comment by bakape** [comment]
Something of that sort, but there will need to be either HTML or CSS changes to make it more presentable as a catalog.

**Comment by Chiiruno** [comment]
What file renders the board that I could do something like call renderArticle from and implement the logic?
Something in templates, right?

**Comment by bakape** [comment]
board.qtpl
