### ISSUE TITLE
Uploading VP9 webm does not workwith some videos

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#775]
I encode a webm with ffmpeg, vp9 as the video codec, following [this guide](https://trac.ffmpeg.org/wiki/Encode/VP9).
I'll update this post with the error when I run across this again.
IIRC, it mainly happened with non-vp9 source videos.

**Comment by bakape** [comment]
Please open an issue on bakape/thumbnailer, if you ever run into this again.

**Comment by Chiiruno** [comment]
@bakape Now that you mention it, the error did mention graphics magick and there being invalid data or something.
