### ISSUE TITLE
Switch from SHA1 to BLAKE2

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#779]
![image](https://user-images.githubusercontent.com/30435868/42476784-a4e96d0c-8394-11e8-8f21-ce2cb135e979.png)

**Comment by bakape** [comment]
>bigger hashes
>migrating everything we have

Yeah, no.

**Comment by Chiiruno** [comment]
I figured bigger hashes would mean less chance of collisions, but okay.

**Comment by bakape** [comment]
SHA1 already has a low chance of accidental collision.

**Comment by Chiiruno** [comment]
Yes, but BLAKE2 will improve that by a few orders of magnitude, while improving hashing speed. (Even if that's pointless because you're just hashing images and videos.)

**Comment by Chiiruno** [comment]
At any rate, if you want to reopen this, I was going to start on this and write a simple script in ./scripts to convert all SHA-1 hashes in the images folder to BLAKE2.

**Comment by bakape** [comment]
There is no reason for this, because our collisions must also be of a
supported file type. This makes collisions very very unlikely.

**Comment by Chiiruno** [comment]
Does this require a lot of work on the thumbnailer too?
I think this should stay open as an eventual target, but okay. Not a big deal.

**Comment by bakape** [comment]
No, not a lot. I simply don't see a lot of point the switch for such little
gain. Not that we will  still need to generate SHA1 hashes for the API and
imagesearch.

**Comment by Chiiruno** [comment]
Did you mean "Note that we will"?

**Comment by bakape** [comment]
It's 4 in the morning. I can mean whatever the damn I want.

**Comment by Chiiruno** [comment]
It's that I'm dumb and can't read what you're saying.
Are you saying that I should note that we still need to generate SHA1 hashes, or are you saying that won't be necessary in the future?

**Comment by Chiiruno** [comment]
I hope your email got that edit or I'm going to sound dumber.

**Comment by bakape** [comment]
BLAKE is pointless and dum. Don't do it.

**Comment by Chiiruno** [comment]
Have a nice oyasumi, silly.
