### ISSUE TITLE
Drag and drop fetch image from url

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#783]
Right now you have a CORS error, doing something similar to what I did with HookTube and having meguca fetch the url itself would fix it.
Not sure what to do about local images. Maybe add an if statement if the url begins with `file:///`, `localhost`, `127.0.0.1`, or `::1`?

**Comment by bakape** [comment]
Considering the URL can be from an internal network, I doubt this is apt.

**Comment by Chiiruno** [comment]
what did he mean by this?

**Comment by bakape** [comment]
Meguca might not have access to that URL.

**Comment by Chiiruno** [comment]
Yeah, that's the problem.
The client, however, might. Thus `file://`... and such.
If we did a switch for that and the other condition being meguca downloads the image itself, then we might be able to get both working.

**Comment by bakape** [comment]
So you want to make the server a fallback?

**Comment by Chiiruno** [comment]
Yes.

**Comment by bakape** [comment]
Okay.

**Comment by Chiiruno** [comment]
You can't access the filesystem directly with javascript, so that's a good thing in general.
I think what we can do is implement a fetch API for both meguca and hydron, both sharing the same `/api/fetch_image/${path}`.
For hydron, just send the local image from the local directory.
For meguca, fetch from `${url}` instead.

**Comment by Chiiruno** [comment]
Of course, since the client is local, it will be able to access `127.0.0.1:8010/api/${path}`.

**Comment by Chiiruno** [comment]
https://stackoverflow.com/questions/1138529/accessing-clients-localhost-from-javascript-online
No, still violates CSP, but we can still apply this concept with hydron.

>The local machine also needs a proxy set up that maps "http://localhost:8080/whatever" to the yahoo pages with your Ajax code. In order for the code to work, you must load it in the browser using the domain same domain that it tries to access.

So, hydron spoofs localhost to be meguca, basically.

**Comment by Chiiruno** [comment]
https://stackoverflow.com/questions/24718762/access-an-api-from-local-server
First answer here is informative. Can we do anything with headers here in localhost's (hydron) case?
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#The_HTTP_response_headers

**Comment by bakape** [comment]
That's already done. It's why it works in the first place.

**Comment by Chiiruno** [comment]
Yeah. Dragging and dropping works with Chromium.
I'm not sure whether that's a good or bad thing in terms of security, but I guess not it's a Fucking Firefox issue. IIRC Firefox doesn't allow connections to localhost to prevent malicious scripts on separate sites from communicating with each other.

**Comment by Chiiruno** [comment]
You dropped Firefox right? I'm getting sick of FF's shit so I guess I'll just do the same.
I think I'll close this issue in favor of #784

**Comment by Chiiruno** [comment]
Turns out I was wrong. Not Firefox's fault, but instead you have to enable `127.0.0.1` in umatrix.
