### ISSUE TITLE
Ability to change image name and specify URL to image

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#784]
Like in 4chan-x, you can specify a URL to the image you want to upload, and change the name of the image as well.
For the URL part, just send the link and have meguca download it, for the name change part, should be simple to implement in the TS.

**Comment by Chiiruno** [comment]
API call for fetching images: `/api/fetch-image/${url}`

**Comment by bakape** [comment]
Reveals the server IP - security vulnerability.
