### ISSUE TITLE
Remember image from before captcha completion

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#788]
Currently if you start a post by say, dragging a hydron image, and are marked for captcha, after completion the post does not remember the image.

**Comment by Chiiruno** [comment]
The problem is because the post form is looking for an image blob, like a local file or a clipboard image, not a hydron URL.
I think I have an idea on what to do.

**Comment by Chiiruno** [comment]
Bingo.
![image](https://user-images.githubusercontent.com/30435868/43611687-8f408894-966f-11e8-8cab-5f5ac4ebc3c7.png)

**Comment by Chiiruno** [comment]
Well, I think I got close to the problem anyway.
I messed with the drop event, the posting model, and even the uploadForm in view, I of course messed with upload in posting too, not a lot that I can get to work, or even debug.
Unless the drop mime type is the problem on why it won't remember after captcha completion, I'm not sure what is.
I do know that with some log debugging, I found that say, pasting an image calls uploadFile twice, and remembers the image.
@bakape thoughts?

**Comment by bakape** [comment]
Well, this would be a 100 times easier, if we did not have deadposting, so
maybe step one would be eliminating that. Remember the two column thing?
What if we do that, but only for open posts not currently visible on the
screen?

**Comment by Chiiruno** [comment]
I'm not sure I want to eliminate deadposting for a bug this small.
At the same time, I don't want to rewrite the entire upload process. Sounds like hell.
Not sure.

**Comment by bakape** [comment]
Deadposting needs a rework or substitute either way. It really complicates
a lot of subsystems.

**Comment by Chiiruno** [comment]
And at that point, you might as well just do it with the C++ client.
Or library, or whatever.

**Comment by bakape** [comment]
Testing this huge behaviour change before that would be better.

**Comment by Chiiruno** [comment]
Well, I'm not confident enough with the client to rewrite the entire upload form and all the resulting bugs that come from it, but if you have some part I can do to make things easier for you, I'll try my hand at that.

**Comment by Chiiruno** [comment]
>use a custom upload form with a backing File variable and a hidden <input type=file> upload form for OpenFile forms.

>Honestly, you can rewrite the client-side completely. The client-server interaction is very minimal. >Here's the algo:
>1) Take file SHA1 hash and try to upload that.
>a) If 403, you need a captcha
>b) If success, goto 3
>2) Upload the actual file
>a) If 403, you need a captcha
>3) Use the token returned by 1 or 2 in either a post creation call or image insertion call through the websocket.
