### ISSUE TITLE
Image upload error with certain files

### ISSUE THREAD

**Issue by ghost** [bakape/meguca#789]
![image](https://user-images.githubusercontent.com/30435868/42717951-4b3d37e6-86ca-11e8-941b-f5b12e37cfc5.png)

This seems to be happening to multiple anons, including me.

**Comment by bakape** [comment]
I need a sample GIF.

**Comment by Chiiruno** [comment]
![83045a4c20b5f83d3bdaa91d94084ebc248f7c33](https://user-images.githubusercontent.com/30435868/42738240-21c337ee-8846-11e8-9d4a-6aaf8f0877e8.gif)

**Comment by Chiiruno** [comment]
Actually, I just realized I should have made this on thumbnailer, but whatever.

**Comment by Chiiruno** [comment]
Did you fix the issue?

**Comment by bakape** [comment]
The one posted here works, so I assume the others do too.

**Comment by Chiiruno** [comment]
Okay, I'll test it out.
Thanks for the fix.

**Comment by bakape** [comment]
Also see, if the one that was segfaulting still does.

**Comment by Chiiruno** [comment]
Yes, I'm working on that right now.
