### ISSUE TITLE
HookTube is kill

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#793]
We need to do something else to ensure YouTube JS is not executed on the meguca page.

Ideas:
- Have the client fetch the googlevideo link directly
- Have the server do the above if the client can't
- Have the link (of course) go to YouTube to ensure anons can use their mpv+youtube-dl combo
- YouTube embed will use googlevideo link instead of the YouTube player

**Comment by bakape** [comment]
So you plan to reimplement hooktube in meguca?

**Comment by Chiiruno** [comment]
Pretty much, yeah.
I wouldn't call it a proxy, though.
