### ISSUE TITLE
Youtube proxy spams errors

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#801]
```
internal server error: youtube proxy on id=`H1pM4H--mrM`: Error extracting sts from embedded url response: common.StatusError{Err:(*errors.errorString)(0xc4223840a0), Code:500}
````

@Chiiruno 
I don't know what this is, but please fix this.

**Comment by Chiiruno** [comment]
Does this crash the server?

**Comment by bakape** [comment]
No, it spams my email. Either some code is wrong or some user error is not handled correctly. I can give you more samples, if need be.

**Comment by Chiiruno** [comment]
Disney blocks [this video](https://www.youtube.com/watch?v=H1pM4H--mrM) at least for your server's location. I'll look into it more, for now you can add this error case to your list of ignored errors, since it's non-crucial.

**Comment by Chiiruno** [comment]
Yeah, I can't even download with youtube-dl.
Looks like it's a block for everybody.
In that case, this isn't a bug, just add the error to common.errors and add it to your list of errors to not email.

**Comment by Chiiruno** [comment]
@bakape On another note, I just saw the changes you made the the server portion of YouTube handling, do you have any ideas on how we might translate those into the client better?

**Comment by Chiiruno** [comment]
Actually, now that I think about it, you don't need to add it to your list of errors, this should be a warning, not an error.

**Comment by Chiiruno** [comment]
No, that's retarded, I didn't add any checks for this specific set of ytdl errors, so that would be pointless, and not allow real errors to show.

**Comment by bakape** [comment]
Maybe we should just go back to noembed? This video blocking issues is definitely limiting.

**Comment by Chiiruno** [comment]
That's like saying we should cut off our arm to get rid of a tick.
This video blocking isn't a problem with this, if you used noembed this would still happen, sans the error.
You cannot view the video on YouTube.

**Comment by Chiiruno** [comment]
At any rate, what do you suggest we do to fix this issue? It's going to happen on noembed too, so I think the best we can do is check if the error includes `Error extracting sts from embedded url response` and don't log it if it does.

**Comment by bakape** [comment]
I don't understand why this would happen with noembed too. It is their
server that gathers metadata and not hours, so regional restrictions should
not apply.

**Comment by bakape** [comment]
Okay, so what do we do?

**Comment by Chiiruno** [comment]
>At any rate, what do you suggest we do to fix this issue? It's going to happen on noembed too (sans the error), **so I think the best we can do is check if the error includes Error extracting sts from embedded url response and don't log it if it does.**

I'll get to this either later tonight or tomororw.
