### ISSUE TITLE
Start on boot

### ISSUE THREAD

**Issue by serverok** [bakape/meguca#803]
What is the best way to start Meguca on boot on Debian ?

**Comment by bakape** [comment]
Systemd service, maybe. I just use monit.

**Comment by Chiiruno** [comment]
Try to replicate [this systemd service](https://github.com/NixOS/nixpkgs/blob/8cf4a4725c1389553228e314432dacb622a29781/nixos/modules/services/web-servers/meguca.nix).
You may want to look at related issues, I am currently [pushing an update](https://github.com/NixOS/nixpkgs/pull/43792) to that.

**Comment by Chiiruno** [comment]
Anyway, if you need some help, I answer any questions you have about creating a systemd service, which I think Debian uses.

**Comment by serverok** [comment]
@Chiiruno  I don't understand this

https://github.com/Chiiruno/nixpkgs/blob/e0a9c50ff186faba68531a3317086ad44cbb0e8c/nixos/modules/services/web-servers/meguca.nix

What  language it is ?  

Is there any simple systemd service file for that ? I tried creating one, but it did not work. 

@bakape 

Can you post monit config for it ?

**Comment by Chiiruno** [comment]
@serverok Look at [this line and below](https://github.com/Chiiruno/nixpkgs/blob/e0a9c50ff186faba68531a3317086ad44cbb0e8c/nixos/modules/services/web-servers/meguca.nix#L106), you can look up sample systemd services and do something similar, since IIRC NixOS service modules have the same variables.

**Comment by bakape** [comment]
@serverok 
```
check process meguca with pidfile $MEGUCA_ROOT/.pid
  start program = "/bin/su -c 'cd $MEGUCA_ROOT; ./meguca start' meguca"
  stop program  = "/bin/su -c 'cd $MEGUCA_ROOT; ./meguca stop' meguca"

if failed port 8000 protocol HTTP
  request /api/health-check
  with timeout 10 seconds
  then restart
```
where $MEGUCA_ROOT is the root directory of meguca.

**Comment by serverok** [comment]
Thanks @bakape
