### ISSUE TITLE
Have YouTube embed revert to noembed for age restricted videos

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#809]
Right now, if a video is age restricted, the client will get the 500 status code.
There are two options
- Find a way to tell if a video is age restricted, but not blocked
- Use noembed if status code == 500

**Comment by bakape** [comment]
2) Will create inconsistency in the UI.

**Comment by Chiiruno** [comment]
Perhaps, but if that's the only way, that may be the way we have to go.
I'm not sure there's a way to check through ytdl, and I'd rather not have meguca fetch the YouTube URL twice, but maybe the error message might say something that I can use.

**Comment by bakape** [comment]
Best investigate ytdl first and, if no such functionality exists, modify
it.

**Comment by Chiiruno** [comment]
At any rate, here's two issues on their repo so we can get more information, and possibly submit a PR.
https://github.com/rylio/ytdl/issues/51
https://github.com/rylio/ytdl/issues/52

**Comment by Chiiruno** [comment]
Looking more into how YouTube does things, our only option is to use noembed if statuscode == 500.
It may create inconsistency in the UI, but it's far more convenient, and will also solve the livestream problem for a large part.

**Comment by Chiiruno** [comment]
As well as videos that are blocked in latvia, but not other places in the world.

**Comment by Chiiruno** [comment]
Unfortunately, getting a YouTube API key would be short lived, while we could do more things with it, the problem is that YouTube will eventually D&C meguca, or straight up cut off the API key.

**Comment by Chiiruno** [comment]
Here's a diff of what I've been attempting for reverting to noembed for statuscode == 500. Not sure what I'm doing wrong, I've tried with async/await, promises, callbacks, for some reason I just can't figure out why parseInt is failing.
```diff
diff --git a/client/posts/embed.ts b/client/posts/embed.ts
index 5d671ac2..c0f98705 100644
--- a/client/posts/embed.ts
+++ b/client/posts/embed.ts
@@ -44,7 +44,18 @@ for (let p of ["YouTube", "SoundCloud", "Vimeo", "Coub", "BitChute"]) {
 	formatters[id] = formatProvider(id)
 	switch (id) {
 		case provider.YouTube:
-			fetchers[id] = fetchYouTube
+			async (el: Element) => {
+				const ref = el.getAttribute("href"),
+				res = await fetch("/api/youtube-data/" +
+					strip(ref.split(".be/").pop().split("embed/").pop().split("watch?v=")))
+
+				if (res.status == 200) {
+					fetchers[id] = fetchYouTube(ref, res)
+				} else {
+					fetchers[id] = fetchNoEmbed(id)
+				}
+			}
+
 			break
 		case provider.BitChute:
 			fetchers[id] = fetchBitChute
@@ -69,66 +80,46 @@ function formatProvider(type: provider): (s: string) => string {
 }
 
 // fetcher for the YouTube provider
-async function fetchYouTube(el: Element): Promise<void> {
-	const ref = el.getAttribute("href"),
-	id = strip(ref.split(".be/").pop().split("embed/").pop().split("watch?v=")),
-	res = await fetch(`/api/youtube-data/${id}`),
-	[title, thumb, video, videoHigh] = (await res.text()).split("\n")
-
-	switch (res.status) {
-	case 200:
+function fetchYouTube(ref: string, res: Response): (el: Element) => Promise<void> {
+	return async (el: Element) => {
+		const [title, thumb, video, videoHigh] = (await res.text()).split("\n")
 		el.textContent = format(title, provider.YouTube)
-		break
-	case 415:
-		el.textContent = format("Error 415: YouTube video is a livestream", provider.YouTube)
-		el.classList.add("errored")
-		return
-	case 500:
-		el.textContent = format("Error 500: YouTube is not available", provider.YouTube)
-		el.classList.add("errored")
-		return
-	default:
-		const errmsg = `Error ${res.status}: ${res.statusText}`
-		el.textContent = format(errmsg, provider.YouTube)
-		el.classList.add("errored")
-		console.error(errmsg)
-		return
-	}
 
-	if (!title) {
-		el.textContent = format("Error: Title does not exist", provider.YouTube)
-		el.classList.add("errored")
-		return
-	}
+		if (!title) {
+			el.textContent = format("Error: Title does not exist", provider.YouTube)
+			el.classList.add("errored")
+			return
+		}
 
-	if (!thumb) {
-		el.textContent = format("Error: Thumbnail does not exist", provider.YouTube)
-		el.classList.add("errored")
-		return
-	}
+		if (!thumb) {
+			el.textContent = format("Error: Thumbnail does not exist", provider.YouTube)
+			el.classList.add("errored")
+			return
+		}
 
-	if (!video) {
-		el.textContent = format("Error: Empty googlevideo URL", provider.YouTube)
-		el.classList.add("errored")
-		return
-	}
+		if (!video) {
+			el.textContent = format("Error: Empty googlevideo URL", provider.YouTube)
+			el.classList.add("errored")
+			return
+		}
 
-	if (!videoHigh) {
-		el.textContent = format("Error: Empty googlevideo (high res) URL", provider.YouTube)
-		el.classList.add("errored")
-		return
-	}
+		if (!videoHigh) {
+			el.textContent = format("Error: Empty googlevideo (high res) URL", provider.YouTube)
+			el.classList.add("errored")
+			return
+		}
 
-	el.setAttribute("data-html", encodeURIComponent(
-		`<video width="480" height="270" poster="`
-		+ thumb + `" ` + (ref.includes("loop=1") ? "loop " : '')
-		+ `controls><source src="` + video
-		+ (!ref.includes(`t=`) ? check("start") : '') + check("t")
-		+ `" type="video/webm">Your browser does not support the video tag.</video>`
-	))
+		el.setAttribute("data-html", encodeURIComponent(
+			`<video width="480" height="270" poster="`
+			+ thumb + `" ` + (ref.includes("loop=1") ? "loop " : '')
+			+ `controls><source src="` + video
+			+ (!ref.includes(`t=`) ? check("start") : '') + check("t")
+			+ `" type="video/webm">Your browser does not support the video tag.</video>`
+		))
 
-	function check(s: string): string {
-		return ref.includes(`${s}=`) ? `#t=` + strip(ref.split(`${s}=`)) : ''
+		function check(s: string): string {
+			return ref.includes(`${s}=`) ? `#t=` + strip(ref.split(`${s}=`)) : ''
+		}
 	}
 }
 
```

**Comment by bakape** [comment]
>YouTube will eventually send a cease and desist letter to meguca, and probably straight up cut off the API key.

Why would that happen? 

>parseInt

Where exactly? Have you tried putting a breakpoint there to examine?

**Comment by Chiiruno** [comment]
If you apply the diff, something about declaring the element in that async function fucks something up in fetchers[id].
I've tried a lot of different combinations, no idea why it does this.

**Comment by Chiiruno** [comment]
>Why would that happen?

A lot of requests, and honestly it's dumb to have to replace the API key all the time just because YouTube does stupid shit. We still wouldn't be able to do livestreams, for whatever that's worth without noembed too.

It's your call, whether to close this or if you think reverting to noembed on non-200 statuscode is a reasonable compromise.

**Comment by bakape** [comment]
Okay, I will look at your patch after some more work on #821.

**Comment by bakape** [comment]
If this still applies, could you make a PR? Patches don't work against a moving target.

**Comment by Chiiruno** [comment]
May not apply, I'll ask for your opinion on something related in a near PR.

**Comment by Chiiruno** [comment]
Or, rather, how you would do it.

**Comment by bakape** [comment]
Nope. I'm not not adding a JS dep ust for this.

**Comment by Chiiruno** [comment]
Okay, are you against putting something into the <script> tag that calls a .js file for this, only when this is detected, or is that out too?

**Comment by bakape** [comment]
Oh, async loading is reasonable.

**Comment by Chiiruno** [comment]
Okay, I'm not entirely sure how to do this.
I guess I could just insert <script> and whatever else is needed along with the iframe we create, but I feel that would load the js file over and over again if it doesn't get cached.
Is there somewhere in the client I can set the <script videoPlayer="whatever.js"> to nothing and then to the thing again, or what?

**Comment by Chiiruno** [comment]
I could also do this with the template generation maybe, and just have the page always load the js.
Note: I only planned on doing this with this instance in particular, every other video would have the normal video player, if you're still against adding a node dep.

**Comment by bakape** [comment]
>I could also do this with the template generation maybe
What do you mean?

I'd just conditionally insert a <script> into head and bind a promise to
the Element.onload callback. That way you will only need to load it once
and the load is conditional.

**Comment by Chiiruno** [comment]
Okay, that will work, and I just check if <script> in head already has it.

>What do you mean?
Does template generation not mess with head?

**Comment by bakape** [comment]
You mean server-side templates?

**Comment by Chiiruno** [comment]
Yes.

**Comment by bakape** [comment]
But then that JS would have to be loaded always on each page. I only find
this acceptable with conditional async script loading. But honestly, why
not just open it on youtube?

**Comment by Chiiruno** [comment]
I'd rather stay away from YouTube JS as much as possible.
Anyway, I'm doing async script loading, don't worry.

**Comment by Chiiruno** [comment]
Are there any resources online I can use to fix this?
```
Uncaught Error: See almond README: incorrect module build, no module name
    at define (almond.js:1)
    at hls.js@latest:1
    at hls.js@latest:1
```
I'm having a hard time finding any way to fix it other than editing a version of it and putting that in meguca/www for async load.
If only I could add https://github.com/video-dev/hls.js as a node module, this would be 50 times easier.

**Comment by Chiiruno** [comment]
Actually, oddly enough, it seems like including it didn't do a damn thing.
