### ISSUE TITLE
Country Flag Not showing

### ISSUE THREAD

**Issue by serverok** [bakape/meguca#810]
Any idea why country Flags are not showing 

https://imageboard.uberchan.org/b/

I have enabled itin admin area

![screenshot from 2018-07-24 09-12-42](https://user-images.githubusercontent.com/34412323/43115743-837d142c-8f22-11e8-905e-a4a5efec978b.png)

**Comment by bakape** [comment]
That's only affects posts made after the setting was enabled. Meguca does not store such poster information by default.

**Comment by serverok** [comment]
@bakape 

The Country Flag was enabled on the board before any new post were added.

I made a test post just now

https://imageboard.uberchan.org/b/53

That too have no country Flag, is that anything to do with CloudFlare ? My config.json is

```
root@ACCUCL623:/meguca# cat config.json 
{
	"ssl": false,
	"reverseProxied": true,
	"gzip": false,
	"imagerMode": 0,
	"cacheSize": 128,
	"address": "127.0.0.1:8000",
	"database": "user=meguca password=meguca dbname=meguca sslmode=disable",
	"certPath": "",
	"reverseProxyIP": ""
}
root@ACCUCL623:/meguca# 
```

**Comment by bakape** [comment]
Oh, you need to download GeoLite2-Country.mmdb from Maxmind and place it inside the meguca root dir. Then restart the server. Guess that is not actually documented anywhere. Hold on.

**Comment by serverok** [comment]
Done this

```
wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
tar xvf GeoLite2-Country.tar.gz 
mv GeoLite2-Country_20180703/GeoLite2-Country.mmdb /meguca/GeoLite2-Country.mmdb
chown -R meguca:meguca /meguca/GeoLite2-Country.mmdb
```
