### ISSUE TITLE
if err != nil spam

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#815]
Let's implement a function in common that does this with an interface for things to log, for most cases where it's just `return err` or some variant.
Something like:
```
// Have a variant for fatal like errCheckFatal or errCheckF, or just add a 'fatal' bool
func errCheck(err error, vars ...interface{}) {
  if err !=nil {
    log.Warning("whatever: ", err)
  }
}
```

Probably not the ideal solution, but there has to be a better way than spamming an `err != nil` check everywhere.

**Comment by bakape** [comment]
But then how will you early return after an error?

**Comment by Chiiruno** [comment]
That's the problem I'm facing too.
Any ideas?

**Comment by bakape** [comment]
What we can do is implement deferred error returns for our most common error handling patterns, i. e., storing an error, NOPing all operations after error and then returning it on caller request.

**Comment by Chiiruno** [comment]
I feel like there's a library for this. I'll do some research.

**Comment by bakape** [comment]
See https://github.com/bakape/hydron/blob/master/db/util.go#L51-L98 for an
example. But that would be a pretty big refactor and likely break shit left
and right. Hmm.
