### ISSUE TITLE
Multiple YouTube requests for the same video

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#819]
Currently, each time the client asks for info on a YouTube video to embed, we have the server fetch the video each time for each client request.
A possible optimization would be to put the info in the DB once, have it be deleted whenever the post (or posts, depending on how we do this) is deleted, and have the YouTube function in the router module check if the ID is in the DB, and if it is, fetch from the DB instead of from YouTube.

Table name: youtube (or youtube_info)
Values:
- id
- title
- thumbnail
- video
- video_high

**Comment by bakape** [comment]
No table needed, imo. Just cache them like noscript captchas. Maybe we can
even reuse some logic.

Also, could you see, if you can select the title language on request? Got
some in French today.

On 30 Jul 2018 9:17 pm, "チルノ" <notifications@github.com> wrote:

Currently, each time the client asks for info on a YouTube video to embed,
we have the server fetch the video each time for each client request.
A possible optimization would be to put the info in the DB once, have it be
deleted whenever the post (or posts, depending on how we do this) is
deleted, and have the YouTube function in the router module check if the ID
is in the DB, and if it is, fetch from the DB instead of from YouTube.

Table name: youtube (or youtube_info)
Values:

   - id
   - title
   - thumbnail
   - video
   - video_high

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bakape/meguca/issues/819>, or mute the thread

**Comment by Chiiruno** [comment]
I don't think YouTube has multiple titles in different languages, and at least ytdl doesn't give you the option.

**Comment by bakape** [comment]
YouTube does. French titles just it is then.

**Comment by Chiiruno** [comment]
I'll see if I can't do some URL magic.
Should we default to English?

**Comment by bakape** [comment]
config.DefaultLanguage, then English.

**Comment by Chiiruno** [comment]
We may be able to append `?gl=EN&hl=en` to the end of the URL.
Going to youtube.jp results in `?gl=JP&hl=ja`, should I put US instead of EN for the `gl`, for at least the English fallback?
I wonder if there's an international one?

**Comment by Chiiruno** [comment]
Okay, it follows locale, similar to Linux locale.
So, we have to use `?gl=US&hl=en` because it's en_US.whatever (probably UTF-8)

**Comment by Chiiruno** [comment]
We may also be able to use en_IE.UTF-8 instead to use gay units instead of free units and other Euro stuff for whatever reason.

**Comment by Chiiruno** [comment]
Okay, [DefaultLang](https://github.com/bakape/meguca/blob/ad20148778a9b92bf4484e807b606b5276c0484c/go/src/meguca/config/config.go#L86) uses en_GB as it's default, so we'll go with that for the English fallback.

**Comment by Chiiruno** [comment]
@bakape About caching youtube info, do you think that's more efficient? I'm hesitant since I feel it might clog up memory after a while. (Although the same concern could be voiced, maybe a bit less so, for noscript captchas, though)

**Comment by bakape** [comment]
We can use a simple LRU cache using a linked list for storage and hashmap for quick lookup. Basic algo:

1) Unlock mutex & defer lock
2) Check, if data is cached.
3) If have data, move to top of list and patch last use time. 
4) If don't have data, fetch data and and perform 3) async in a separate goroutine.  
5) Check 2 least recently used entries in linked list and drop them (doing this here prevents a need for a cleanup routine), if either  
  a) Their last used time is over max
  b) List length is over max.

Thoughts?

**Comment by Chiiruno** [comment]
Looks good to me, we'll see if implementation is any different.
I'm a little worried about a DoS attack using mass youtube links, though, especially with a mutex, and the processing power needed to check and move, though.

**Comment by Chiiruno** [comment]
Speaking of mass API attacks, maybe we should do calls to the API in batches per post, at least as far as the client is concerned.

**Comment by Chiiruno** [comment]
For instance, in embed, instead of calling /api/youtube-data or whatever it was each time a link is encountered in the post, get a list of them, map duplicates, and only fetch once instead of multiple times for duplicate API calls.
Same can go for commands I think.

**Comment by bakape** [comment]
I don't see any obvious gains here. Most you will be saving on is mutex
contention.

**Comment by Chiiruno** [comment]
I guess it just sums down to this: Would you rather have 100 API calls for the same thing, or would you have the client only do it once, while getting the result of 100?

**Comment by bakape** [comment]
As long as you check the cache there isn't much of a difference. One is a
bit better at lock contention, but at the cost of implementation
complexity. I'd say either is fine.

**Comment by Chiiruno** [comment]
I think we got mixed up because this issue went into another issue, but it's still related I guess.
I started talking about the client, you know how you can put a link like 40 times?
Instead of having the client call /api/youtube-data 100 times, or whatever, have the client check for duplicates, and only check once for each unique youtube ID.
How can we do this is the client sanely? I also think this may apply to other client API calls.

**Comment by Chiiruno** [comment]
For now, we can either have the client do the deduplication, or we can have the client send a post in it's entirety on clicking done, or the shortcut of course. I think it was 'commit'.
Then, the server can do the deduplication, but we might as well have the client do it since the nature of meguca is liveposting, and because of that we can't really guard against that kind of API attack, at least not as far as I'm aware.
That said, we might actually be able to catch that on post commit, and have the server do the deduplication, thoughts?

**Comment by bakape** [comment]
>have the client do the deduplication
NEVER TRUST THE FUCKING CLIENT

>might actually be able to catch that on post commit, and have the server
do the deduplication
That was my first thought.

**Comment by Chiiruno** [comment]
#872 supersedes deduplicating links, commands, and embeds
#873 supersedes caching youtube embed info

**Comment by bakape** [comment]
Don't you mean this issue is superseded by those 2?

**Comment by Chiiruno** [comment]
Yes, who knows why I typed that.
