### ISSUE TITLE
Testing if SMTP works

### ISSUE THREAD

**Issue by serverok** [bakape/meguca#824]
I added SMTP server, how  i verify SMTP is working ?

When a user report an image, what happens, admin will get a email noification ?

**Comment by bakape** [comment]
No, reports currently don't have any notifications. The email notices are
only for development-related errors.

**Comment by serverok** [comment]
Thanks. When an image get reported, is there anyway admin knows about this report now ?

**Comment by Chiiruno** [comment]
We could probably add an option to report bans or reports maybe?
Would be especially useful for reporting illegal stuff like CP.

**Comment by serverok** [comment]
Yes, that will be great. It is important to deal with stuff like CP.

**Comment by Chiiruno** [comment]
I'll get @bakape 's opinion on it, and what should be emailed.
We may end up only doing emailing for reporting illegal stuff.

**Comment by serverok** [comment]
Email can include include link to reported image/post and the report text. Admin can click on the link, then delete the post if required.

**Comment by bakape** [comment]
For reports it is best to use SSE or active polling. It's simply plenty of
work I've put off for later (C++ client or so). If Chiiru wants to
implement it now, I don't mind.

**Comment by Chiiruno** [comment]
I was just thinking of doing something simple like if it's an 'illegal' report, purposefully error and have the email handler shoot, without halting the entire program.

**Comment by bakape** [comment]
Oh, that can work. We can tie it in with a more solid report system later.
