### ISSUE TITLE
Empty image frame

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#830]
Every now and then, an image someone uploads doesn't show, and instead is an empty image frame.
I think the console error said something about it not existing on the server.
My theory is that the client is trying to load the image before it exists, and doesn't retry on on async function to eventually load it properly.

**Comment by bakape** [comment]
It's Cloudflare lagging. Best we can do is check again after a second. Need an attempt counter not to infinite loop on actual 404 images. Want to take this?

**Comment by Chiiruno** [comment]
I would do it on a time basis, where if it isn't there within a minute, then give up. Probably check every 2 seconds for the first 10 seconds, then after that every 10 seconds for the rest of the minute.
Maybe we should apply a similar logic to the uploading process itself too, so anons don't get stuck with an upload that never ends.
Not sure I want to take this, at least not within the week, but I won't rule it out either. If you have the time and want to do it, then feel free.

**Comment by bakape** [comment]
Not in the nearest future. I want to work on our caches and hydron next.
Would be nice to have more hands around.

**Comment by Chiiruno** [comment]
>work on our caches ... next
Oh, that'll mesh with my YouTube issue.
What were you planning on?

**Comment by bakape** [comment]
>Oh, that'll mesh with my YouTube issue.
Nah. Completely orthogonal. I don't know how much I'll actually do in one swoop.

**Comment by Chiiruno** [comment]
>Completely orthogonal

My YouTube issue is gonna use a noscript-like cache though, right?
If you're working on caches, wouldn't that end up affecting it?
I was just saying working on the cache was a good idea.

**Comment by bakape** [comment]
>If you're working on caches, wouldn't that end up affecting it?
Nah. I meant ban caches and HTML/JSON caches.

**Comment by Chiiruno** [comment]
I see.
Ganbare!

**Comment by Chiiruno** [comment]
This seems to be related:
```
Failed to load resource: the server responded with a status of 502 ()
This happened after the thumbnail loaded, but I tried to hover over the image for the bigger size, and it gave me the default image icon, still can't find where in the source this is happening.
```
Is the server propagating it's image fast enough, or is it saying it's available before it's actually written?

**Comment by Chiiruno** [comment]
Oh right, cloudflare is lagging, duh.

**Comment by bakape** [comment]
We need to catch all 502s and retry again in a second or so. Keep retrying
till a cap is reached.
