### ISSUE TITLE
Display upload error in new window, if it contains HTML

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#833]
To prevent stuff like this 
![capture](https://user-images.githubusercontent.com/7851952/43910595-e9ef843e-9c05-11e8-84d8-0238c7bba9a2.png)

**Comment by Chiiruno** [comment]
IP shows in the fucked up HTML.
![shit](https://user-images.githubusercontent.com/30435868/43987791-3ed91762-9cec-11e8-9aa0-5b920e60bed6.jpg)

**Comment by bakape** [comment]
Yes, that is likely the Cloudflare captcha page.
