### ISSUE TITLE
Button and route to display link to image + parent thread/post 

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#837]
>It would be grate if one could us a site like Reddit to drive traffic to ones website, however access to the full size image/video with a link to the original thread would be needed, like they do on the imgur website.  Can this be implemented on the meguca image board?  Pls see attached screenshot to understand what I mean.  I don’t know how you would do this on the meguca image board, but this would most definitely be a fantastic way to drive traffic to ones website!!!

Could just add a share button and link to a simple HTML template route.

**Comment by Robbotto** [comment]
I think you are right.
