### ISSUE TITLE
Alert: No post open

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#848]
![image](https://user-images.githubusercontent.com/30435868/44310734-d47f2f80-a3a0-11e8-96ef-1ac7bec7e217.png)

**Comment by bakape** [comment]
What exactly did you do and in what order?

**Comment by Chiiruno** [comment]
I copy and pasted some code, erased because I messed up the formatting, then posted.
Then, in another post, I said "Yup" and it did a floating captcha and then errored with that alert.

**Comment by bakape** [comment]
Oh, I get what's happening. Basically you typed fast enough to get the client to submit some post modification messages before a confirmation about post allocation was received. Never happened to me because my connection isn't burger-tier.

**Comment by Chiiruno** [comment]
My connection is pretty good over here, so it's probably just a high ping from burgerland to latvia.

**Comment by bakape** [comment]
The server is behind cloudflare though.

**Comment by Chiiruno** [comment]
Not websockets, just static assets like images AFAIK.

**Comment by bakape** [comment]
Everything is now. Thank the DDoSes.

**Comment by Chiiruno** [comment]
How can fucking cloudflare even do websockets?
Do you have the server on a cloudflare server?

**Comment by Chiiruno** [comment]
Oh, I'm retarded.
You have the connection itself go through cloudflare as a proxy.

**Comment by bakape** [comment]
Google reverse proxy.
