### ISSUE TITLE
Duplicate post issue

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#850]
I noticed that I just uploaded an image, but somehow I also blancposted at the same time.
I don't know what I did to cause this.
Probably related to the unified upload form.

**Comment by bakape** [comment]
All userscripts disabled?

**Comment by Chiiruno** [comment]
Yes.

**Comment by bakape** [comment]
What method was used to upload the image?

**Comment by Chiiruno** [comment]
I think it was drag&drop, but I'm not sure.

**Comment by bakape** [comment]
Tell me, if this ever happens again. It also matters, if there was any text
submitted prior to that. The paths for these are different.

**Comment by Chiiruno** [comment]
There was not any text before, IIRC.

**Comment by bakape** [comment]
Okay, still need reproduction steps.

**Comment by Chiiruno** [comment]
Open post, drag&drop (or select image), type something right after.
At least, that's what I did.
No guarantee you will get a local result, probably due to cloudflare.

**Comment by bakape** [comment]
We are off cloudflare again.

**Comment by Chiiruno** [comment]
Then this probably won't show up.
I'll close until this pops back up.
