### ISSUE TITLE
Server can return YouTube livestream

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#852]
As seen with https://www.youtube.com/watch?v=dhCeseXZEKA
I need to figure out another way to check if a video is a livestream other than duration.

**Comment by bakape** [comment]
What?

**Comment by Chiiruno** [comment]
Try it locally, you'll have a 10 hour video.
It doesn't work live because of CORS issues, the URL only allows the server IP to use it.

**Comment by Chiiruno** [comment]
https://www.chromestatus.com/feature/5629709824032768

**Comment by Chiiruno** [comment]
Anyway, this should return 415, instead of 200. Will research.
