### ISSUE TITLE
Allow CORS for image server

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#854]
So that we can just drag&drop images from meguca, into meguca.
``Failed to load https://images.meguca.org/assets/images/src/dd0ac4c1cdeceaf05b5506c1e189866a5f2a60c2.jpg: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://meguca.org' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.``

**Comment by Chiiruno** [comment]
@bakape Still isn't working on meguca, did you restart the imager server too?

**Comment by bakape** [comment]
It's CF. Try a fresh image. Don't want to purge caches just for this.

**Comment by Chiiruno** [comment]
Okay.
