### ISSUE TITLE
Ban HTML broken on live updates

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#857]
`<b class="admin banned" banned="">USER WAS BANNED FOR THIS POST BY "admin" FOR 1 MINUTE: k</b>`

**Comment by Chiiruno** [comment]
That's not broken, but I apparently should use data attributes instead.
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

Also, a real problem is that system bans show up empty, I need to add a check if system.

**Comment by bakape** [comment]
What is broken is ban notices not showing up until you refresh.

**Comment by Chiiruno** [comment]
Has nobody refreshed or something?
Everything should be live.
Not sure what to do about ban notices, since it kicks you from the server, but it shows for everyone else, or should.

**Comment by bakape** [comment]
>but it shows for everyone else
Does not. That's the problem.

**Comment by Chiiruno** [comment]
Okay.
Probably related:
```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at PostView.<anonymous> (view.ts:270)
    at Generator.next (<anonymous>)
    at main.js:6
    at new Promise (<anonymous>)
    at __awaiter (main.js:2)
    at PostView.renderStatus (view.ts:256)
    at PostView.renderBanned (view.ts:318)
    at Post.setBanned (model.ts:212)
    at m (client.ts:143)
    at handle (client.ts:40)
```
