### ISSUE TITLE
Refactor and optimise moderation on-post storage and propagation

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#862]
The code has really bloated with the recent additions. Perhaps moving post moderation values to a separate table is for the best too.

**Comment by Chiiruno** [comment]
>Perhaps moving post moderation values to a separate table is for the best too.

In the client, right? The db already has `mod_log`, which is what the client receives from when the server fetches a few entries from the db.

**Comment by Chiiruno** [comment]
Unless you mean `banned`, `deleted`, and `meidoVision`, but I don't see the point of moving those, unless you want to turn `mod_log` into some mixture of entries and post values.
Honestly, what should be done I think is have each post have it's own set of mod-log entries server-side, and completely remove the `mod_log` table in favor of a more integrated set.

**Comment by Chiiruno** [comment]
Well, they round up to the nearest 0, so it's not very precise.

**Comment by bakape** [comment]
>In the client, right? The db already has mod_log, which is what the client receives from when the server fetches a few entries from the db.

The DB. Jut contemplating for now.

**Comment by Chiiruno** [comment]
Then consider this:
>Honestly, what should be done I think is have each post have it's own set of mod-log entries server-side, and completely remove the mod_log table in favor of a more integrated set.

Probably have them in a text[] field like 8ball that contains jsonified modlogentry(s).
Have a constraint where every 7 days after their creation, they're deleted, but not necessarily the post.

**Comment by bakape** [comment]
I opted for partially duplicating the entries for post and mod-log storage.
That way they can have separate lifetimes and can be deleted independently.

**Comment by Chiiruno** [comment]
>infinite moderations log entries per post.

That's something I was trying to avoid, because if we sync that to the client, we'd have to include all of them on the post and that would be really spammy if some meido decides she wants to ban the same anon 50 times, or some meido does literally everything to that post. And if we didn't do that, it would be wasteful because what's the point of having those entries if you don't use them.

I guess look at my above post, it seems a little more reasonable.

**Comment by bakape** [comment]
> if some meido decides she wants to ban the same anon 50 times
Then everybody looking at the post should see that and report the meido
higher up.

**Comment by bakape** [comment]
> sync that to the client,
That is fine. Post JSON weighs far more than that.

**Comment by Chiiruno** [comment]
Okay, fair enough. I guess if this is really what you want to do.
If so, please consider this versus another table, since we can eliminate extra mod-log DB calls and easily sync to the client like you want to.

>I have a good idea: Keep the mod-log as it is, but have each post have it's own text[] array of JSON ModLogEntrys containing the 3 relevant ModLogEntrys.
That way we can have quick lookup per-post, and also be able to sync to the client without much effort, and less db calls.

**Comment by Chiiruno** [comment]
sans the "3 relevant ModLogEntrys" for "all relevant ModLogEntrys"

**Comment by Chiiruno** [comment]
If we do it the way I specified above, we could also eliminate DB calls in templates, since the Post struct will contain the JSONified ModLogEntries that we can just unmarshal.

**Comment by bakape** [comment]
I'm reading the mod log into the post struct in `db/reader.go`. Templates
need not access the DB like this, as the entries are retrieved and cached.
Considering storing them in JSON, I feel structured data in tables is
always better and more durable to errors. The overhead of an extra optional
DB query for moderated posts in comparison to  storing JSON arrays on the
post and querying those fields each post read is questionable.

**Comment by Chiiruno** [comment]
Why not insert an entry into the `posts` table in `logModeration`? Wouldn't need to call the db for mod-log entries every time you read a post, then.

**Comment by bakape** [comment]
When I said "read post" I meant "read post from DB".

>Why not insert an entry into the posts table in logModeration
I'm doing something similar to that. The difference is that the insertion
is not happening in logModeration() itself because that deals with
moderation that does not affect posts as well and that they are written to
a new separate table.

**Comment by Chiiruno** [comment]
Okay, that answers my questions. Sounds good.
Ganbare!

**Comment by bakape** [comment]
Hmm, maybe I should put it inside logModeration after all.

**Comment by Chiiruno** [comment]
You can concat and append arrays in SQL right?
Just JSONify the entry and insert into the `text[]` field in `posts`.

**Comment by bakape** [comment]
JSON is dynamically typed.
