### ISSUE TITLE
Broken with Go 1.11

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#864]
Why is this happening?
Is it local to me? The test apparently passed on the commit.
```
go list -f '{{.Deps}}' meguca | tr -d '[]' | xargs go get -v
meguca/server
# meguca/server
go/src/meguca/server/html.go:39:3: undefined: templates.WriteIndexWasm
go/src/meguca/server/html.go:110:3: undefined: templates.WriteIndexWasm
make: *** [Makefile:76: server_deps] Error 123
```

**Comment by Chiiruno** [comment]
Yeah, this is really weird.
`WriteIndexWasm` is definitely generated.

**Comment by Chiiruno** [comment]
quicktemplate did have a new commit recently, not sure if this is related.
https://github.com/valyala/quicktemplate/commit/ff58753897b6cbb02abc005b244fd77814b67acd

**Comment by bakape** [comment]
`make generate`

**Comment by Chiiruno** [comment]
Uh, yeah, still no dice.

**Comment by bakape** [comment]
`make dist_clean all`

**Comment by Chiiruno** [comment]
Nope.

**Comment by bakape** [comment]
What's the output of `git diff`?

**Comment by Chiiruno** [comment]
There is no diff.
I'm making sure this isn't just nix fucking something up, give me a moment.

**Comment by Chiiruno** [comment]
Well, that's somewhat surprising. It's not nix.
wakarimasen lol
Can you build locally? Does it do fine?

**Comment by Chiiruno** [comment]
I did a rebuild, and it seems to work: https://travis-ci.org/bakape/meguca/jobs/423244316
I don't know. Do you think there's something wrong with the repo?
Could also be a Go issue, but I don't understand why Go wouldn't be able to see that `WriteIndexWasm` exists?

`go version go1.11 linux/amd64`

**Comment by bakape** [comment]
Right. Last I tried meguca was broken with Go 1.11. Mind finding out how to fox this?

**Comment by Chiiruno** [comment]
I can try sure, but I have no idea where to start.
Tips?

**Comment by bakape** [comment]
No clue. Maybe a compiler regression. Best bet is massive googleling.

**Comment by Chiiruno** [comment]
I'll see what I can do.
At the very least, I know it's related to go modules.

**Comment by Chiiruno** [comment]
Did meguca compile with Go 1.10?

**Comment by Chiiruno** [comment]
@bakape Found it.
https://golang.org/doc/go1.11
>WebAssembly
Go 1.11 adds an experimental port to WebAssembly (js/wasm).

>Go programs currently compile to one WebAssembly module that includes the Go runtime for goroutine scheduling, garbage collection, maps, etc. As a result, the resulting size is at minimum around 2 MB, or 500 KB compressed. Go programs can call into JavaScript using the new experimental syscall/js package. Binary size and interop with other languages has not yet been a priority but may be addressed in future releases.

>As a result of the addition of the new GOOS value "js" and GOARCH value "wasm", Go files named *_js.go or *_wasm.go will now be ignored by Go tools except when those GOOS/GOARCH values are being used. If you have existing filenames matching those patterns, you will need to rename them.

>More information can be found on the WebAssembly wiki page.
