### ISSUE TITLE
Post contents aren't updated when submitting a post

### ISSUE THREAD

**Issue by destrotheguca** [bakape/meguca#867]
Any characters that are typed between the time that the first character of a post is typed, and the moment that the post is made live, will not be included in the submitted post unless another change to the post's text occurs before submission.

* Open the Reply container
* Type some characters in quick succession, before the post is assigned a post number
* After the post number has been assigned, do not change the text anymore (adding a picture won't prevent you from reproducing this)
* Press Done (or Alt+S, this occurs regardless) and watch as Meguca devours all but the first character of your post

This should be avoided if on post submission, the live post will actually update with the text box's contents, instead of just relying on the most recent update that was noted *on the live post's text contents changing*.

**Comment by bakape** [comment]
I'll look into this.

**Comment by bakape** [comment]
Need to reproduce this. Might be a client<->server data race.

**Comment by Chiiruno** [comment]
I can reproduce this, exactly as stated in the OP.
Likely due to geographical differences. You won't be able to produce this locally, and possibly you won't be able to live either since you're close to the server.
Try using TOR or a VPN, then you'll be able to reproduce on the server.

**Comment by Chiiruno** [comment]
I can reproduce this locally actually if I only do two characters really fast.
Probably related to websockets and appending characters.

**Comment by bakape** [comment]
Oh, I get it. We need run this.parseInput() before the rest of this.closePost() is executed. I'll this, when  get home.

**Comment by bakape** [comment]
No, better do this on post allocation and the same for a buffered image.
