### ISSUE TITLE
Cache youtube embed info in server

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#873]
Supersedes #819

**Comment by Chiiruno** [comment]
I think I was going to use cache for this, similar to caching the generating HTML.

**Comment by Chiiruno** [comment]
That's right, and to deduplicate youtube links.

**Comment by Chiiruno** [comment]
@bakape Caching saves json formatted data to disk drive, right?
Caching in this case would be pointless if memory-only.

**Comment by bakape** [comment]
Best use the database for this.
