### ISSUE TITLE
error 123 when compile 

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#880]
![2018-09-10_215644](https://user-images.githubusercontent.com/11831096/45310906-6c5bdd80-b549-11e8-8107-538c6d628a4d.jpg)
Debian 9 latest x64, VMware Virtualization

**Comment by bakape** [comment]
What go version are you using?

**Comment by serofir** [comment]
i following your instructions (docs/installation.md) >go1.9.2.linux-amd64

**Comment by serofir** [comment]
Now, we got brand new error.
![2018-09-11_090455](https://user-images.githubusercontent.com/11831096/45335584-e455f200-b5a1-11e8-9012-bc0959bce356.jpg)

**Comment by Chiiruno** [comment]
Run `make update_deps` and say if it does this again after trying to build again, please.

**Comment by Chiiruno** [comment]
You shouldn't be running make as root.
Please go into a less privileged user and go ahead and just delete both your go folder (probably in your home directory) and meguca, then re-pull meguca.
Then run `make`.
Your trying to build from the latest master, correct?
You're still using go 1.11, correct?

**Comment by Chiiruno** [comment]
Also update_deps (https://github.com/bakape/meguca/blob/master/Makefile#L78) exists, not sure why it's failing.
You're not using the docker image, are you?

**Comment by Chiiruno** [comment]
Tell me your OS and version too, please.

**Comment by Chiiruno** [comment]
Sorry, I just reread the OP.
This is in a VM then, hm.

**Comment by serofir** [comment]
>You shouldn't be running make as root.
Why not? I can try, but why it doesn't work with root?
>Your trying to build from the latest master, correct? 
>Yes.
>You're still using go 1.11, correct? 
>Yes.
>You're not using the docker image, are you?
No.

**Comment by serofir** [comment]
![2018-09-11_093138](https://user-images.githubusercontent.com/11831096/45336501-b2468f00-b5a5-11e8-8ca5-1eaf57d00f81.jpg)

**Comment by Chiiruno** [comment]
I have no idea whether or not go builds correctly in root, but this doesn't matter because it's a VM anyway.
Give me a moment to look at the affected line.

**Comment by Chiiruno** [comment]
Yeah, unless you're somehow compiling still with the wrong go version, we shouldn't have that error in thumbnailer.
Try deleting your go folder in home and the meguca repo, re-pull and make.
If that doesn't work, we may need to change the installation doc, in the meantime you can try on a different distro perhaps. I know arch linux can compile meguca, and I have a package for meguca on NixOS if you're just looking to host.

**Comment by serofir** [comment]
I deleted the golang for the fourth time, and removed the old "go" folder from root. Removed the line from / etc / profile. Deleted the meguca. Launched apt autoremove. Got reinstalled GO, installed meguca. And when I try to compile, I get an error again.

**Comment by serofir** [comment]
![2018-09-11_100329](https://user-images.githubusercontent.com/11831096/45337555-72ce7180-b5aa-11e8-8d79-29f7ff2e95e4.jpg)

**Comment by Chiiruno** [comment]
Alright, sorry for putting you through so much trouble.
I know that thumbnailer does pull, and build correctly, so this has to be a system problem, but I'm not entirely sure what.
Looks like we'll have to update the installation docs, I'll look into this later, and make an issue now.
In the meantime, please try one of the alternatives (try an Arch Linux VM) listed above.

@bakape Any ideas why things aren't working here?

**Comment by bakape** [comment]
You probably have multiple Go versions installed somewhere on your system. That error indicates the compiler does not support type aliases.

**Comment by Chiiruno** [comment]
Is that actually possible with debian?
He did do autoremove.

**Comment by bakape** [comment]
Yes, if he did something funny with GOROOT, PATH and/or GOPATH. Go can
actually be installed wherever you want.

**Comment by Chiiruno** [comment]
># Install Go
wget -O- https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz | tar xpz -C /usr/local
echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
source /etc/profile

Probably because he did this again with 1.11 then.
Perhaps we need to update the installation docs with different go/postgres/etc versions.

**Comment by Chiiruno** [comment]
@serofir Try to change the stuff you changed to the correct Go version (1.11), log out, then log back in, it should work then.

**Comment by bakape** [comment]
Uninstall the one from the apt repository. That Go version is too old.
Install as described in the docs, but download Go version 1.11.

**Comment by serofir** [comment]
Already try it today.
But I can retry, if you want.

**Comment by serofir** [comment]
Well, I remove Go folder, remove Go with apt. Clean all, reboot server. Delete Meguca folder, try to install again Go.
![Uploading 2018-09-11_130929.jpg…]()

**Comment by serofir** [comment]
After all i try to make (America great) again.
![2018-09-11_131123](https://user-images.githubusercontent.com/11831096/45344100-a7e7bd80-b5c4-11e8-9d2d-739a3bd09b22.jpg)
But something goes wrong.
![2018-09-11_131152](https://user-images.githubusercontent.com/11831096/45344140-b930ca00-b5c4-11e8-8981-ac27fbfcc91b.jpg)

**Comment by bakape** [comment]
Those are connectivity issues. Try again.

**Comment by serofir** [comment]
After all I install meguca, then I try to start, and it's don't work again.
![2018-09-11_132826](https://user-images.githubusercontent.com/11831096/45344923-b33be880-b5c6-11e8-8835-d03ea234ad47.jpg)

**Comment by bakape** [comment]
You did not pass your DB password. See '. /meguca - - help'.

**Comment by serofir** [comment]
Got it.
It seems to be work as well.
Thank you, for answer for my stupid questions.
