### ISSUE TITLE
Allow unban by meido/meido++ if it's their own ban

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#885]
This way we can allow a meido/meido++ to unban a post if banned in error.

**Comment by bakape** [comment]
Sounds reasonable. 

Blocked by #862

**Comment by Chiiruno** [comment]
Actually, before I waste my time on this, is there any real reason meido++ shouldn't be able to unban any ban?
If you can ban, you should be able to unban. If it's a rebellious staff issue or something silly, the BO or even admin of the site can always demeido or demote the staff.
Thoughts, @bakape ?

**Comment by bakape** [comment]
Good point. Yeah, we can just lower the unban level.

**Comment by Chiiruno** [comment]
I'll submit a PR.
