### ISSUE TITLE
Recent change in quoting

### ISSUE THREAD

**Issue by runforitkyle** [bakape/meguca#887]
Could we please have the new quoting style as an optional change?
 I feel like many users prefer the newline for a quote on an empty line and like the inline quoting for lines where there is already text.
 Much of the time a quote is used it is on a single post to reply to that post and the user would want to go to a newline so the QoL fix reduces the efficiency of posting.

Old style without pressing enter
>>4822218
No fun allowed

New style without pressing enter
>>4822218No fun allowed

 An extra keystroke may not be much but it is still a change that makes things harder the majority of the time.
I posted a strawpoll the other day and had 10 users in favour of the old style and 0 users in favour of the new style. So I feel that it'd make sense to have this as an optional feature
 You're welcome to delete this if you think it is just dumb complaining.

**Comment by bakape** [comment]
>4822218No fun allowed

That should not be happening. Need reproduction steps, your browser version and OS. 

@Chiiruno You broke it.

**Comment by runforitkyle** [comment]
Reproduction:
Be on an empty line, click a post number to quote it, the input for text is immediately after the number instead of the expected newline.
Browser version:
62.0 (64-bit) Firefox Quantum
OS:
Windows 10

**Comment by Chiiruno** [comment]
Like I said in my PR OP, it's intentional.
I've been waiting to see what you think, and I guess you just fixed it.

**Comment by bakape** [comment]
It was breaking habitual posting patterns too much.

**Comment by Chiiruno** [comment]
Honestly, for me too.
I thought you thought it was fine since you merged it, though.

**Comment by bakape** [comment]
Honestly, I don't know. There are pros and cons for any complex approach, so I just cut down on complexity for now.
