### ISSUE TITLE
Delay image processing, if lacking memory

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#891]
Need to think on how to make this less restrictive and still work even with how the runtime does not instantly release memory to the OS. Might want to use `runtime.MemStats` for this.

**Comment by Chiiruno** [comment]
Can't you force the GC at certain points in Go?
Just force a GC collection before image processing if low.

**Comment by Chiiruno** [comment]
https://golang.org/pkg/runtime/#GC

**Comment by Chiiruno** [comment]
To avoid massive collections, perhaps find other points in the code where we can do this too.

**Comment by bakape** [comment]
>it may also block the entire program
Nope nope nope.
Yeah, the best solution is probably rewriting thumbnailer to have a pure C
interface and have the Go interface be just a wrapper around it. There are
about 3 issues on this on thumbnailer.

**Comment by bakape** [comment]
After that we can rewrite the meguca imager to be mostly C++ and only
import the DB handing Go parts as a static library.

**Comment by bakape** [comment]
Cancelled in favour of #913
