### ISSUE TITLE
How to completely delete threads and posts, with the media?

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#894]
How to completely delete threads and posts, with the media?
For example, to remove a spam thread with a CP file (image, webm, mp4, etc) or/and a link to CP site.
How to remove from the admin area without putting it in the trash?
How to delete a file from the disk?
When I try to remove threads and posts, they are simply replaced with a basket icon, but they can still be viewed, and the files still remain on the disk, and available at the link,. CP is prohibited in all countries, I would like to protect my site from illegal content. How can I do it?

**Comment by foxishholo** [comment]
See #892
