### ISSUE TITLE
Middle click causing paste or qoutes

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#895]
>If you click middle mouse button on meguca it directly opens new post and copy/paste text you have saved in your clipboard. Never known that was a thing

I don't know how this is happening, but you clearly broke it. Omedetou!

**Comment by bakape** [comment]
That is probably best. It's very unintuitive, as the middle mouse button is used for other stuff like new tab links and hardly anyone uses it for pasting.

**Comment by bakape** [comment]
Wait, maybe we should keep it, but not commit the text instantly and still trim the text to prevent overflow?

**Comment by bakape** [comment]
I'm not too sure anymore.

**Comment by Chiiruno** [comment]
Second option seems more reasonable.
Let's try that, and if it's still a problem, we'll remove the keybind.

**Comment by bakape** [comment]
Wait, are you doing this, or should I quickly fix this?

**Comment by Chiiruno** [comment]
If you're up for it, go ahead.
