### ISSUE TITLE
How to protect my instance against wipe?

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#897]
Is it possible to set limits or other protection?
You can see my screenshots, it's result of wipe, possibly 1-2 minutes. (Very fast)
Also, how to clean this :picrelated
"Delete all from this IP" - doesn't help.
Because each post from diffirent IP (proxy)
P.S.: Default captcha doesn't help.
Probably due to the fact that the script uses the Captcha Recognition Services
![2018-09-24_102058](https://user-images.githubusercontent.com/11831096/45937707-82a37800-bfe4-11e8-9751-21fdc0aaa5bd.jpg)
![2018-09-24_102037](https://user-images.githubusercontent.com/11831096/45937708-833c0e80-bfe4-11e8-9ca2-c89d7206d24f.jpg)

**Comment by bakape** [comment]
>wipe

You mean a spam script? Hmm, I could add a server-wide toggle to require a captcha on the first post, instead of only requiring it after exceeding the spam score.

**Comment by bakape** [comment]
Wait, no. They are creating new threads. Those should always require a captcha (if turned on). Are you sure the captchas where turned on while this happened?

**Comment by serofir** [comment]
Yep, it turned on.
Also another question.
I tried to clean it, but I could not delete all the messages in bulk.
Is it possible to disable transparent moderation?
And it is possible to create the ability to delete all messages for a certain period, for example? Or the ability to delete all messages from one ip, (yes, there is not one, unfortunately) completely, without these red basket icons?
![2018-09-24_105549](https://user-images.githubusercontent.com/11831096/45957981-181c2780-c038-11e8-888d-1f16c2f0fb32.jpg)

**Comment by serofir** [comment]
I now need to somehow remove 8000 threads, I do not know how to do it quickly.
If someone interested about my opinion, I want to have feature to set limits on the number of creating threads from one Ip.
For example, no more than 1 thread per hour, for one ip.
And if everything is very bad, then add global limits on the creation of threads for the board.
For example, no more than 10 threads per hour for board / b /.

**Comment by bakape** [comment]
>And it is possible to create the ability to delete all messages for a certain period

That is too niche and you can do it  simply with sql. 
`psql -d $db_name -c "delete from threads where id between $highest_id and $lowest_id" `
where $db_name is the name of the database meguca is using (default is 'meguca')
$highest_id is the id of the newest thread to delete
$lowest_id  is the id of the oldest thread to delete

As for preventing the problem, more advanced captchas are planned with #662 . I'll probably work on that next around this weekend.

**Comment by Chiiruno** [comment]
Perhaps implement a purge by same IP option for admin only?
Seems like a good middle ground.

**Comment by bakape** [comment]
Considering the threads are from the same IP, I don't think that will have
much effect. Prevention would be best.
