### ISSUE TITLE
Right parenthesis at end of URL is always exluded from the hyperlink

### ISSUE THREAD

**Issue by ghost** [bakape/meguca#902]
In other words, Wikipedia URLs with parenthesis tend to fuck up.
For example, if we wanted to show:
https://en.wikipedia.org/wiki/Magia_(Kalafina_song)
Instead, we get a link to
https://en.wikipedia.org/wiki/Magia_(Kalafina_song
followed by a close-parenthesis, that isn't part of the URL. (Can't demonstrate as the Github markup doesn't let me fool it.)

I understand & appreciate why they are excluded from the URL in the general case, this issue is solely regarding the exclusion of right-parenthesis _where it's rather obvious that it should be included in the URL_.

**Comment by destrotheguca** [comment]
The obvious suggestion (however correct / incorrect it may be) that should at least fix the issue for _most_ instances - including probably all Wikipedia URLs - would just be to search and see if there are an equal number of left- and right-parenthesis in the URL (before removal of the final one). 
If there is, and they're balanced correctly like the URL in the issue body, don't remove the last one despite being at the end of the URL.

**Comment by bakape** [comment]
Yeah, sounds  fine.
