### ISSUE TITLE
Nginx config problem

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#908]
How to set up a meguca with nginx?
Meguca was working without NGINX normally, but when many people came to the site, the server was hanging and turn off. So I decided to install nginx. Maybe it was wrong decision, lol.

default.conf (sites-enabled)

http://codepad.org/XGn8pV6q

When I go to the site, I see the default message Nginx.

I  ran meguca with the command :

`./meguca -r -a :8000 -d "user=meguca password=1234567 dbname=meguca sslmode=disable binary_parameters=yes"`

Also I tried to run with SSL support, don't know it correct or not

`./meguca -a :80 -S "/etc/letsencrypt/live/mydomain.com/cert.pem" -g -c 256 -d "user=meguca password=1234567 dbname=meguca sslmode=require binary_parameters=yes"`

Are there any errors in this line?

Also in config file, there are

```
`        location /.well-known/ {
                alias /home/meguca/server/www/.well-known/;
        }
        location / {
                return 301 https://$server_name$request_uri;
        }`

So there is no /server/www/ directory
and /home/meguca 404 error too
i have meguca in /meguca directory
and there is no /server/www directory.

Question is, how to setup nginx with meguca to work correctly, and with support letsencrypt ssl?
```

**Comment by bakape** [comment]
Use the sample config in ./docs and adapt it to your own needs. See
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/ and
https://nginx.org/en/docs/ for more info.

**Comment by serofir** [comment]
>sample config
It's not working at all.

**Comment by bakape** [comment]
Well, yes. It's to be used as an example for your own config.

**Comment by serofir** [comment]
```

server {
        listen 80;
        server_name meguca.org images.meguca.org;
        location /.well-known/ {
                alias /home/meguca/server/www/.well-known/;
        }
        location / {
                return 301 https://$server_name$request_uri;
        }
}
```

Here, I don't have "home/meguca/server/www/.well-known/;" folder
I have /meguca/www/ folder
server folder doesn't exist, and ".well-know" too

I tried to use different paths for different folders, but to no avail.

There has always been an error of endless redirect

then I decided to remove this 

`        location / {
                return 301 https://$server_name$request_uri;
        }
}`

And now, i have 404 error.
So what should I do next?
What should I do to make it work?

**Comment by bakape** [comment]
No clue. Either way this is a deployment problem specific to your server
and not meguca.

**Comment by serofir** [comment]
Of course, it's problem with my nginx conf.
All I need is a working configuration file.
From working meguca instance.
If I see example, I fix my conf, and it will work fine.

**Comment by bakape** [comment]
The one I use is for a split 2 VPS setup, so I don't know, if it will be of much use to you.

**Comment by serofir** [comment]
Possible yes, i have some unused VPS.

**Comment by bakape** [comment]
This is the one meguca.org uses. Don't know, if this will help you any.
```
upstream meguca {
	server 127.0.0.1:8000;
}

upstream imager {
        server <internal_IP>:8000;
}


# Additional WebSocket proxying support
map $http_upgrade $connection_upgrade {
	default upgrade;
	'' close;
}

server {
        listen 80;
        server_name meguca.org images.meguca.org;
        location /.well-known/ {
                alias /home/meguca/server/www/.well-known/;
        }
        location / {
                return 301 https://$server_name$request_uri;
        }
}

server {
	# SSL
	listen 443 ssl;
	server_name meguca.org images.meguca.org;
	ssl_certificate /etc/letsencrypt/live/meguca.org/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/meguca.org/privkey.pem;

	# Gzip compression
	gzip on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_types text/plain text/css application/json application/javascript application/x-javascript text/javascript application/octet-stream;


	location / {
		proxy_pass http://meguca/;
		client_body_timeout 600s;
		proxy_read_timeout 36000s;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		# WebSockets support
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}

	location /api/upload {
		proxy_pass http://imager;
                client_max_body_size 100m;
                client_body_timeout 600s;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location /api/upload-hash {
                proxy_pass http://imager;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

	location /api/create-thread {
                proxy_pass http://imager;
                client_max_body_size 100m;
                client_body_timeout 600s;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

	location /api/create-reply {
                proxy_pass http://imager;
                client_max_body_size 100m;
                client_body_timeout 600s;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }


	location /assets/images {
                proxy_pass http://imager;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```
