### ISSUE TITLE
Ability to undelete posts by same IP

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#909]
When the thread is moving fast, and you have lock to bottom enabled, it's possible to hit the wrong button at the same time the page moves.
Perhaps having an option to undelete posts that have been deleted by same IP either as a menu option or some html page might be a good idea.
On the other hand, why bother? Thoughts?

**Comment by bakape** [comment]
I see the use case but the question is, if it's worth the effort to
implement. If you have spare effort, be my guest.

**Comment by Chiiruno** [comment]
Yeah, I'll probably do it.
I've gotten a bunch of other stuff done, so I'll put this on my list for whenever I get back to developing for meguca, which will probably be within a month.

**Comment by Chiiruno** [comment]
Yeah, not worth the effort.
