### ISSUE TITLE
Need something like auto-install script, or docker-container

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#912]
I catch myself thinking nice idea.
What would be great is to able quickly install meguсa.
For example, using a script, as it was in the first version.
Or installation using a docker-container, with a built-in nginx reverse proxy, etc.
I am convinced that many users, those as stupid as I, or even more stupid, could discover the wonderful imageboard engine meguca, without any without technical knowledge.

**Comment by bakape** [comment]
>script
I have found the hard way that such scripts need to account for far too many variables, break between release versions and quickly become unmaintainable while also confusing the user. docs/installation.md serves as a good enough setup example without these limitations. 
>docker-container
Docker containers are meant to be stateless. Meguca utilizes several databases during operation and the process is inherently stateful. Separating these out of the container and getting Docker to play nice with state is more work than setting up meguca by hand. 
 >without technical knowledge
I have also learned the hard way that I don't want to actively support people with neither minimal sysadmin skills nor a desire to learn them. These people also typically abandon their venture in no time at all.

@Chiiruno might be interested in creating a Nix config file for meguca and that is probably as close to an auto deployment as you get.

**Comment by Chiiruno** [comment]
https://github.com/NixOS/nixpkgs/blob/30783a52bc047257c8b2aedb16b54b6315db2951/nixos/modules/services/web-servers/meguca.nix
https://github.com/NixOS/nixpkgs/blob/78b357924ad71c895045de09ab6646d389b90e23/pkgs/servers/meguca/default.nix
We already more or less have auto-deployment on Nix and NixOS, and that's as far as I'm willing to go.
With all due respect, stupid people who don't want to learn can fuck off.

If you don't want NixOS, a good option would be a VM image that has meguca already set up on it, but I'm not making or supporting it.

**Comment by bakape** [comment]
@Chiiruno What are these .nix files lacking in terms of automation?

**Comment by Chiiruno** [comment]
As far as NixOS goes, nothing.
As far as Nix goes, nothing unless you don't install Nix on whatever OS you're on.

**Comment by bakape** [comment]
Case closed: use Nix, if you really need automatic deployment.
