### ISSUE TITLE
Flags disabled because "github.com/mholt/archiver" broke API

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#914]

**Comment by Chiiruno** [comment]
Well, shit. I'll get on this tomorrow.

**Comment by bakape** [comment]
Also, we need to migrate to
Go modules to prevent shit like this. I
already pinned all the npm deps.

**Comment by bakape** [comment]
You could migrate now or wait a week or so till I have everything done for
migrating meguca to Go modules, so we can pin the archiver version.

**Comment by bakape** [comment]
Oh, nevermind. Didn't see the PR.
