### ISSUE TITLE
502 Bad Gateway preventing posting

### ISSUE THREAD

**Issue by ghost** [bakape/meguca#915]
Just in case it hasn't been acknowledged yet. Some semi-usual image fuckery, but the main issue is whenever I start typing:
`<html>`
`<head><title>502 Bad Gateway</title></head>`
`<body bgcolor="white">`
`<center><h1>502 Bad Gateway</h1></center>`
`<hr><center>nginx/1.10.3</center>`
`</body>`
`</html>`
The above appears in an alert.
Tested on & off VPN, on Firefox, Waterfox, Chromium, Firefox (mobile).
Some other slut reported the same issue in the thread earlier, so it shouldn't be that my mere presence is breaking things.

**Comment by bakape** [comment]
The image server was stuck in an error loop. Should be fixed now. Can you
confirm?

**Comment by destrotheguca** [comment]
All appears to be working as normal, no issues with images / posting on my end anymore.
