### ISSUE TITLE
Post quoting from board page is broken

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#923]
Clicking on the post number bugs out and prevents quoting till page refresh.

**Comment by Chiiruno** [comment]
I don't think we should be replying from the board page anyway.
What's the point of this?

**Comment by bakape** [comment]
Used to work like this: 
1) Click on post on board page.
2) Page goes to link.
3) Page loads.
4) Reply to clicked posts is opened.

**Comment by bakape** [comment]
Its stored `openQuote` inside of localStorage before the click and then checked that on page load. Somehow broken now.
