### ISSUE TITLE
Bugs after update

### ISSUE THREAD

**Issue by serofir** [bakape/meguca#927]
When i log in to admin panel, i see sh*t.
![2018-11-24_173948](https://user-images.githubusercontent.com/11831096/48967833-b3b61e00-f010-11e8-88f3-151f6d840de7.jpg)
![2018-11-24_174133](https://user-images.githubusercontent.com/11831096/48967839-badd2c00-f010-11e8-9dbc-61ee58723a12.jpg)

**Comment by bakape** [comment]
Is that before or after you submit the form?

**Comment by serofir** [comment]
After.

**Comment by bakape** [comment]
Okay, that's the captcha then.

**Comment by bakape** [comment]
Can not reproduce. 
1. Post your OS + version and browser + version!
2. Is this the master branch of meguca? 
3. Run `make update_deps server` and see, if that fixes the problem!
4. Does this happen with other browsers on the machine?

**Comment by serofir** [comment]
1.Debian 9.3, Waterfox 56.2.5, SRWare Iron  63.0.3300.0
2.Master branch.
3.Does not fix problem
4.Yes.

**Comment by bakape** [comment]
Can not reproduce with any browser. Not sure, if machine or server issue. Could you try going to meguca.org and seeing, if creating an account there produces the same behaviour?

**Comment by serofir** [comment]
After clean install, all work fine.
Possible problem with my db.
