### ISSUE TITLE
like hell

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#941]
@Chiiruno 

Affected videos: 
https://www.youtube.com/watch?v=0fJqX_0fJ5w
https://www.youtube.com/watch?v=MSc5dJqjmhY
https://www.youtube.com/watch?v=4KMmqQDP6gw

Errors:
```
internal server error: YouTube [4KMmqQDP6gw]: Error %!d(string=150):Cette vidéo a été bloquée dans votre pays par l'utilisateur qui l'a mise en ligne.: common.StatusError{Err:(*errors.errorString)(0xc0028b2e90), Code:500}
```

Please either fix, ignore or make them non-500 errors.

**Comment by Chiiruno** [comment]
Yeah, just ignore.
I'm having a hard time compiling meguca now that cgo is a thing and nix can be really dumb sometimes, so this might have to wait until I get an upstream issue fixed.

**Comment by bakape** [comment]
Cgo has been a thing for meguca for a long long time though.

**Comment by Chiiruno** [comment]
It's either a nix problem or some random cache problem then, I don't know.
I submitted an issue upstream.

**Comment by bakape** [comment]
Please fix this or I'll just drop all of this and integrate the youtube API.

**Comment by bakape** [comment]
Wait, what was wrong with noembed again?

**Comment by Chiiruno** [comment]
Uhh lemme see if Go will work yet.

**Comment by Chiiruno** [comment]
I wish nix would get it's shit together, go wasn't having this problem before.
I may just submit a commit without testing.
We could also just ignore all youtube errors, nothing that part of the code generates is really going to be an issue if it errors.

**Comment by bakape** [comment]
I just want to stop getting French error mails. Do whatever you feel is appropriate.

**Comment by Chiiruno** [comment]
There's nothing I can do about that, unless you want me to add bloat and pipe it through google translate.
Probably should just ignore all youtube errors.

**Comment by Chiiruno** [comment]
In the meantime, did you make any changes to the makefile recently?
It might not be nix directly causing this.
https://github.com/golang/go/issues/24674

**Comment by Chiiruno** [comment]
Actually, before I do ignore all youtube errors, I'm gonna submit a commit, if it doesn't work then reopen this.

**Comment by bakape** [comment]
Post error message.

**Comment by Chiiruno** [comment]
Nah, it's fucking Nix.
Maybe I'll compile on a VM or something.

Here.
`go get runtime/cgo: open /nix/store/j2hrpgwraja6wqkaqlhlvad888xx8m5m-go-1.11.2/share/go/pkg/linux_amd64/runtime/cgo.a: read-only file system`
I did a test with an older commit, still no dice.

**Comment by Chiiruno** [comment]
@bakape Is there anything in the makefile or otherwise go-related that is using the `-i` flag?
That seems to be my problem here, although it may be an insane nix default too.

**Comment by bakape** [comment]
>-i
Which exactly?

**Comment by Chiiruno** [comment]
go build?

**Comment by bakape** [comment]
Does not seem like it, but pretty sure Go would use that flag internally
after `go get`.

**Comment by Chiiruno** [comment]
Oh duh, I thought `go build` because I tried that and it failed too, but I forgot that calls `go get` for found dependencies.
Not really sure what is using the `-i` flag, or if it's just a compiled default that perhaps shouldn't be a default in nix.

**Comment by Chiiruno** [comment]
Anyway, it compiles if I add `-pkgdir /tmp` to anything go.
