### ISSUE TITLE
Thread watcher notifications are limited on Firefox

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#942]
Chromium ![image](https://user-images.githubusercontent.com/30435868/50385886-9c676080-06a2-11e9-8e1f-cff4eb7a0077.png)
Firefox ![screenshot_20181223_110643](https://user-images.githubusercontent.com/30435868/50385910-e81a0a00-06a2-11e9-9684-5e0f174cc458.png)

**Comment by bakape** [comment]
Disabled work mode and thumbnail hiding?

**Comment by Chiiruno** [comment]
Yeah.

**Comment by Chiiruno** [comment]
If I click on it, of course it takes me to the page, the problem is the missing image and possibly the missing meguca.org, but that might just be chromium-specific.

**Comment by bakape** [comment]
See client/page/thread_watcher.ts and check, if FF supports all the opts
used. Reference:
https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification
Also check for any bugs in FF's implementation and possible workarounds.

**Comment by Chiiruno** [comment]
Looks like Notification.image is fucked on firefucks.
https://developer.mozilla.org/en-US/docs/Web/API/notification/image
I'll look for a workaround, because I know that images do work in push notifications in Firefox.

**Comment by Chiiruno** [comment]
May need to use Notification.icon for firefox instead.
I can't test this until Nix gets it's shit together.

**Comment by Chiiruno** [comment]
Tested with console: `new Notification("test", {icon: "https://images.meguca.org/assets/images/src/ff38e020fe74b917c57be4bae0be4e59d01ac458.png"});`
It works, I'll submit a PR, no guarantee it functions correctly until upstream unfucks Go.
