### ISSUE TITLE
Make captchouli another instance

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#962]
Make captchouli another instance like imager that restarts on error.
That way this stops happening, just email the error so debugging is possible.
As far as I can tell, captchouli would be better as a separate instance so it doesn't mess with imager.

**Comment by Chiiruno** [comment]
Also make regular captcha as fallback if this happens again.

**Comment by bakape** [comment]
The problem is that meguca does not actually restart on SIGTERM and you need to SIGKILL it. Fucking graphicsmagick. So, how is your work on the Rust thumbnailer?
