### ISSUE TITLE
Limit maximum websocket connection ammount per IP

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#965]
OOM DoS attack protection. @Chiiruno what would be a good limit? 
We could also maybe somehow count connections toward the spam counter.

**Comment by Chiiruno** [comment]
10-16.
Not sure if linking to spam counter is really needed.

**Comment by Chiiruno** [comment]
Actually, maybe 8 might be the best.

**Comment by Chiiruno** [comment]
You may want to rethink the auto ban, this is going to fuck anons who go "回レ回レ回レ回レ回レ回レ回レ回レ回レ回レ回レ回レ回レ回レ" and etc.
This can happen if it's a large paste, the server will take the paste and ignore the extra character in the post, but will contribute to the spam counter.

**Comment by bakape** [comment]
You need to instantly paste 2K chars then erase that and repeat 4-5 times to trigger it IIRC.

**Comment by Chiiruno** [comment]
Fixed by b3a16a490653fb0cb3deebe96a3579a981729dd3

**Comment by bakape** [comment]
OOOOOOOH
