### ISSUE TITLE
Remove hyphens from Google search when clicking NP banner

### ISSUE THREAD

**Issue by ghost** [bakape/meguca#971]
Most of the time they're fine (though useless) when separating artist & title, though if the track title has a hyphen followed by anything other than a space, by including it you're practically requesting for Google to give you the wrong results.

Example: `MOSAIC.WAV x Satsuki ga Tenkomori - I refuse! -Dempa ga Tenkomo remix-`
Thanks to `-Dempa` being included, we've just removed any chance of finding the correct song.

**Comment by bakape** [comment]
Would be easier to just make sure that no hyphen is preceded by a space and not followed by a space.

**Comment by Chiiruno** [comment]
We should just remove the hyphen completely I think, Google is smart enough to figure it out without it.

**Comment by bakape** [comment]
Fair point.
