### ISSUE TITLE
OpenCV 3-4 possibly broken for captchouli

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#975]
Not sure if 3 is broken, but I think 4 might be.
![image](https://user-images.githubusercontent.com/30435868/51654665-8decbd00-1f5e-11e9-8cd1-5e46da855bdc.png)

**Comment by bakape** [comment]
I have 3, so I assume it's 4. We might just need to add a `cv::` in front
of each of those.

**Comment by bakape** [comment]
Closed with 77aa9e1f9fa163c383188c55dff7ef2925d5983e
