### ISSUE TITLE
Captchouli number pad integration

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#979]
There's 9 squares, so might as well try to see if we can make the number pad work with it, probably similar to other shortcuts. Apparently google's recaptcha already has this integration.\
Probably use 'enter' for completing it.
t.yasuna

**Comment by bakape** [comment]
10 lines of JS event handler or so.

**Comment by bakape** [comment]
>May want to lock post form until captchouli submission success.
Not required.

**Comment by Chiiruno** [comment]
I think the captchouli auto focuses it away anyway, so hopefully you're right.

**Comment by bakape** [comment]
Nope.

**Comment by bakape** [comment]
Too PITA to implement due to focus problems.
