### ISSUE TITLE
Fork bomb client system on global ban

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#981]
1. Delete all settings and drop IndexedDB, because why not? 
  1.1. Need to ensure IDB is dropped in a try-catch, so it does not abort this. 
2. Open new meguca tab that executes (2-3).
3. Start pushing arrays to an array in an infinite while loop. 

@Chiiruno Need input

**Comment by Chiiruno** [comment]
This should only activate if the ban is by admin, as well as maybe even an extra safety measure like a checkbox that says 'Fork bomb', so that this doesn't happen to anons who don't deserve it.
This doesn't really do anything to anons using custom clients or scripting through the websocket/POST/GET API.

**Comment by Chiiruno** [comment]
Also if you're going to fork bomb anyway, why not async load a mining script and use all cores to get some dumb bitcoin out of it?
Actually, XMR might be the better choice.

**Comment by Chiiruno** [comment]
This might be a good thing, but please be aware that this kind of thing will get the site labeled as malware/malicious.

**Comment by Chiiruno** [comment]
Regardless of whether this is miner or fork bomb, ad blockers will probably block this, and it's not particularly hard to block this with umatrix either.
Will need to investigate how to bypass both.

**Comment by bakape** [comment]
>This should only activate if the ban is by admin

Global bans are only for admin. 

>This doesn't really do anything to anons using custom clients or scripting through the websocket/POST/GET API.

They still get banned. 

>Also if you're going to fork bomb anyway, why not async load a mining script and use all cores to get some dumb bitcoin out of it?
Actually, XMR might be the better choice.

YES. Adding to list.

>This might be a good thing, but please be aware that this kind of thing will get the site labeled as malware/malicious.

Fair point. On a related note, how do you moderate an anonymous imageboard effectively?

**Comment by Chiiruno** [comment]
Global bans are also for system, lat.
I don't want to get my computer frozen because I somehow tripped the spam thing, like I've done before.

**Comment by Chiiruno** [comment]
>Fair point. On a related note, how do you moderate an anonymous imageboard effectively?

By making at least sakuya or some other anon a meido++.
Too many things are by context and previous culture on imageboards, AI is currently ineffective.

**Comment by bakape** [comment]
Humans go on power trips. 
t. human

Thoughts on distributed moderation through opt-in filter lists? Maybe also always generate thread-level IP-based ID's on posts, just don't show them unless ID's are enabled?

**Comment by Chiiruno** [comment]
Both sound fine for the most part, will need to change a lot of server-side stuff.

**Comment by Chiiruno** [comment]
I would be worried about democratic moderation too though, see: reddit.

**Comment by Chiiruno** [comment]
For the sake of consistency, maybe this should be a local-only commit to meguca in the same vein as #983 , if you still decide to go with that.

**Comment by Chiiruno** [comment]
This is incredibly dumb.
Should at least check if the ban is by system or not.

**Comment by bakape** [comment]
Bans should hold power not be a messaging system.

**Comment by Chiiruno** [comment]
How does this stop BR-kun from just closing the tab and reopening with a new IP?
Also chances are this will get meguca and anyone who uses it on a malware domain list.

**Comment by bakape** [comment]
>How does this stop BR-kun from just closing the tab and reopening with a new IP?

It increases his workload, decreases throughput and possibly crashes his machine.

>Also chances are this will get meguca and anyone who hosts it on a malware domain list.

Shoganai.

**Comment by Chiiruno** [comment]
That only really applies to a spammer that spams every second.
BR-kun is more contextual.

**Comment by bakape** [comment]
Horizontal scaling is never a bad thing.

**Comment by Chiiruno** [comment]
In most cases, sure, but having the User Experience®™ suffer for a niche issue like this is a shit idea.

**Comment by Chiiruno** [comment]
Anyway, my suggestion is to at least have the client check whether the ban is by system or by a meido++/BO/admin.

**Comment by bakape** [comment]
Only system that arguably does not warrant a crash is roulette. But
shooting yourself in the head should also have more weight to it. Hmm.
