### ISSUE TITLE
Better sort server config options in templates

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#985]
Kind of messy, maybe there's a better way.
Depends on #984

**Comment by Chiiruno** [comment]
Or, maybe instead of sorting, have visual groupings for related options.

**Comment by bakape** [comment]
They are already grouped into tabs and manually sorted.

**Comment by bakape** [comment]
What do you suggest?

**Comment by Chiiruno** [comment]
Like I said, visual groupings.
It's hard to tell where one group of options starts and the other ends.
Like a box around it or something.

**Comment by bakape** [comment]
So something like putting `<hr>` in the list?

**Comment by Chiiruno** [comment]
Probably, yeah.
I'm not exactly a GUI expert.

**Comment by bakape** [comment]
You can probably just add an extra `inputType` (or whatever it was called)
into specs.go and then  space the things appropriately with those.

**Comment by Chiiruno** [comment]
I'll look into it, then.

**Comment by Chiiruno** [comment]
Not sure that's going to work out, here's an example.
![screenshot_20190209_094646](https://user-images.githubusercontent.com/30435868/52522790-a8f24900-2c4f-11e9-8e16-3327e73ce93d.png)

example patch
[dumb.zip](https://github.com/bakape/meguca/files/2847960/dumb.zip)

**Comment by bakape** [comment]
Pushed this to `dev/group-options` so you can decide how to group/rearrange the options.  Please work on that branch. 

![screenshot_20190211_012934](https://user-images.githubusercontent.com/7851952/52541347-89b50200-2d9c-11e9-9cec-b6e8dc67272b.png)

**Comment by Chiiruno** [comment]
Okay, thanks for the help.
