### ISSUE TITLE
Temporary per-board (or per-thread) IP whitelist

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#991]
>Needs a temporary whitelist mode. Whitelist active connections, and exclude banned posters.
That will deal with the VPN issue until they stop being dicks, at the cost of disallowing returning posters for a bit.

Should solve the VPN and spammer issue in a fairly easy way.
Have a meido++ be able to toggle.
Dunno what to do about meido++ abuse, could have a mod-log entry and have admin check for abuse.

**Comment by the8472** [comment]
Automatic range bans (via whois lookup) as a larger ban-hammer seems less invasive than a whitelist. That way you can knock out a whole ISP at a time.

**Comment by medukatheguca** [comment]
Could have a "request entry" option for non-whitelisted IPs trying to enter during a lockdown. Would show information like the country and a mandatory message that can be reviewed by meidos. Any empty or non-convincing messages could just be ignored.

**Comment by bakape** [comment]
Whitelists generally are too exclusive and defeat the purpose. I'd prefer a more automated solution.

**Comment by bakape** [comment]
Dead issue.
