### ISSUE TITLE
web server unable to start after updating deps

### ISSUE THREAD

**Issue by parkrangeranime** [bakape/meguca#993]
I went to update the server by first `./meguca stop`'ing and then pulling the new changes. After that I did `make update_deps all`as usual and everything built successfully. However, when I attempted to start the server again I was met with the following error message: 
`2019-02-26 07:13:05   INFO listening on https://127.0.0.1:8000`
`2019-02-26 07:13:05  FATAL error starting web server: open : no such file or directory`
I double checked to see if the postgres (11.2) and nginx (1.14.2) services were still running and they were. My go version is 1.11.5. I'm not sure what to do.

**Comment by bakape** [comment]
Does switching to the revision you had earlier produce the same error?

**Comment by parkrangeranime** [comment]
Correct, even when trying again on a completely fresh server. Which means I am definitely doing something wrong but I don't know what.

**Comment by bakape** [comment]
Post the CLI args and configuration file (if any), you start meguca with.

**Comment by parkrangeranime** [comment]
config.json: https://ghostbin.com/paste/kk8zx
launch arguments (as root): `./meguca &`

**Comment by bakape** [comment]
Seems I forgot to add SSL key parameter support to the config file. Will do this later this evening. For now you can pass them as CLI arguments with `--ssl-cert` and `--ssl-key`.

**Comment by bakape** [comment]
Added `keyPath` to the configuration file. Add this field to your config file and point it to the key file.
