### ISSUE TITLE
TypeError: p is undefined

### ISSUE THREAD

**Issue by Chiiruno** [bakape/meguca#994]
![screenshot_20190226_140529](https://user-images.githubusercontent.com/30435868/53442757-9ad25580-39cf-11e9-89ee-d5f3c0e008e0.png)

**Comment by Chiiruno** [comment]
Nothing in console, by the way.

**Comment by Chiiruno** [comment]
Seems to be caused by posting, or viewing images.

**Comment by bakape** [comment]
Fixed.

**Comment by Chiiruno** [comment]
Not quite, just posted this.
![screenshot_20190226_141628](https://user-images.githubusercontent.com/30435868/53443387-31534680-39d1-11e9-9c84-bbde07843e22.png)
Could be one-off.

**Comment by Chiiruno** [comment]
It works on a refresh, though.

**Comment by Chiiruno** [comment]
This was after the refresh you told me to do, mind you.

**Comment by Chiiruno** [comment]
![screenshot_20190226_141939](https://user-images.githubusercontent.com/30435868/53443545-9018c000-39d1-11e9-9db0-8321782b79f6.png)
Nope, happens with other images before refresh.

**Comment by Chiiruno** [comment]
Shit, nothing in console.

**Comment by Chiiruno** [comment]
![screenshot_20190226_142752](https://user-images.githubusercontent.com/30435868/53444025-b68b2b00-39d2-11e9-8760-aab49677a40b.png)
