### ISSUE TITLE
Client sent an HTTP request to an HTTPS server.

### ISSUE THREAD

**Issue by parkrangeranime** [bakape/meguca#995]
When starting meguca, it is impossible to connect to the site. I'm not sure what causes this except that it is something with Go. Happens on every browser. I am on go version 1.12. I don't think this is an NGINX problem as I can serve static web pages just fine. 
A blank webpage displaying "Client sent an HTTP request to an HTTPS server." is all that is displayed and when searching for that only two results came up.

My config.json:
```
{
    "ssl": true,
    "reverseProxied": false,
    "gzip": true,
    "imagerMode": 0,
    "cacheSize": 128,
    "address": "127.0.0.1:8000",
    "database": "user=server password=dbdb dbname=server sslmode=require binary_parameters=yes",
    "certPath": "/etc/letsencrypt/live/server.org/fullchain.pem",
    "keyPath": "/etc/letsencrypt/live/server.org/privkey.pem",
    "reverseProxyIP": ""
}
```
And my launch options (as root): `./meguca start`

**Comment by bakape** [comment]
Set address to `:8000`, ensure you have no firewall or iptables rules for
accessing this port and try to connect to `https:<your_server_ip>:8000`.
Then post results.

**Comment by parkrangeranime** [comment]
Setting address to :8000 and connecting to the site as site.org:8000 does work, and just trying site.org does not

**Comment by bakape** [comment]
That means your nginx ix misconfigured. See the sample configuration file in the `docs` directory.

**Comment by parkrangeranime** [comment]
It is fixed now, thank you.

**Comment by bakape** [comment]
Be sure to also set `reverseProxied` to true or you'll ban localhost one day.

**Comment by tpchibanda** [comment]
the username admin and password gophish is not working
